// Code generated by protoc-gen-go.
// DO NOT EDIT!

package datastore

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type Property_Meaning int32

const (
	Property_NO_MEANING       Property_Meaning = 0
	Property_BLOB             Property_Meaning = 14
	Property_TEXT             Property_Meaning = 15
	Property_BYTESTRING       Property_Meaning = 16
	Property_ATOM_CATEGORY    Property_Meaning = 1
	Property_ATOM_LINK        Property_Meaning = 2
	Property_ATOM_TITLE       Property_Meaning = 3
	Property_ATOM_CONTENT     Property_Meaning = 4
	Property_ATOM_SUMMARY     Property_Meaning = 5
	Property_ATOM_AUTHOR      Property_Meaning = 6
	Property_GD_WHEN          Property_Meaning = 7
	Property_GD_EMAIL         Property_Meaning = 8
	Property_GEORSS_POINT     Property_Meaning = 9
	Property_GD_IM            Property_Meaning = 10
	Property_GD_PHONENUMBER   Property_Meaning = 11
	Property_GD_POSTALADDRESS Property_Meaning = 12
	Property_GD_RATING        Property_Meaning = 13
	Property_BLOBKEY          Property_Meaning = 17
	Property_ENTITY_PROTO     Property_Meaning = 19
	Property_INDEX_VALUE      Property_Meaning = 18
)

var Property_Meaning_name = map[int32]string{
	0:  "NO_MEANING",
	14: "BLOB",
	15: "TEXT",
	16: "BYTESTRING",
	1:  "ATOM_CATEGORY",
	2:  "ATOM_LINK",
	3:  "ATOM_TITLE",
	4:  "ATOM_CONTENT",
	5:  "ATOM_SUMMARY",
	6:  "ATOM_AUTHOR",
	7:  "GD_WHEN",
	8:  "GD_EMAIL",
	9:  "GEORSS_POINT",
	10: "GD_IM",
	11: "GD_PHONENUMBER",
	12: "GD_POSTALADDRESS",
	13: "GD_RATING",
	17: "BLOBKEY",
	19: "ENTITY_PROTO",
	18: "INDEX_VALUE",
}
var Property_Meaning_value = map[string]int32{
	"NO_MEANING":       0,
	"BLOB":             14,
	"TEXT":             15,
	"BYTESTRING":       16,
	"ATOM_CATEGORY":    1,
	"ATOM_LINK":        2,
	"ATOM_TITLE":       3,
	"ATOM_CONTENT":     4,
	"ATOM_SUMMARY":     5,
	"ATOM_AUTHOR":      6,
	"GD_WHEN":          7,
	"GD_EMAIL":         8,
	"GEORSS_POINT":     9,
	"GD_IM":            10,
	"GD_PHONENUMBER":   11,
	"GD_POSTALADDRESS": 12,
	"GD_RATING":        13,
	"BLOBKEY":          17,
	"ENTITY_PROTO":     19,
	"INDEX_VALUE":      18,
}

func (x Property_Meaning) Enum() *Property_Meaning {
	p := new(Property_Meaning)
	*p = x
	return p
}
func (x Property_Meaning) String() string {
	return proto.EnumName(Property_Meaning_name, int32(x))
}
func (x Property_Meaning) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Property_Meaning) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Property_Meaning_value, data, "Property_Meaning")
	if err != nil {
		return err
	}
	*x = Property_Meaning(value)
	return nil
}

type Property_FtsTokenizationOption int32

const (
	Property_HTML Property_FtsTokenizationOption = 1
	Property_ATOM Property_FtsTokenizationOption = 2
)

var Property_FtsTokenizationOption_name = map[int32]string{
	1: "HTML",
	2: "ATOM",
}
var Property_FtsTokenizationOption_value = map[string]int32{
	"HTML": 1,
	"ATOM": 2,
}

func (x Property_FtsTokenizationOption) Enum() *Property_FtsTokenizationOption {
	p := new(Property_FtsTokenizationOption)
	*p = x
	return p
}
func (x Property_FtsTokenizationOption) String() string {
	return proto.EnumName(Property_FtsTokenizationOption_name, int32(x))
}
func (x Property_FtsTokenizationOption) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Property_FtsTokenizationOption) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Property_FtsTokenizationOption_value, data, "Property_FtsTokenizationOption")
	if err != nil {
		return err
	}
	*x = Property_FtsTokenizationOption(value)
	return nil
}

type EntityProto_Kind int32

const (
	EntityProto_GD_CONTACT EntityProto_Kind = 1
	EntityProto_GD_EVENT   EntityProto_Kind = 2
	EntityProto_GD_MESSAGE EntityProto_Kind = 3
)

var EntityProto_Kind_name = map[int32]string{
	1: "GD_CONTACT",
	2: "GD_EVENT",
	3: "GD_MESSAGE",
}
var EntityProto_Kind_value = map[string]int32{
	"GD_CONTACT": 1,
	"GD_EVENT":   2,
	"GD_MESSAGE": 3,
}

func (x EntityProto_Kind) Enum() *EntityProto_Kind {
	p := new(EntityProto_Kind)
	*p = x
	return p
}
func (x EntityProto_Kind) String() string {
	return proto.EnumName(EntityProto_Kind_name, int32(x))
}
func (x EntityProto_Kind) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *EntityProto_Kind) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EntityProto_Kind_value, data, "EntityProto_Kind")
	if err != nil {
		return err
	}
	*x = EntityProto_Kind(value)
	return nil
}

type Index_Property_Direction int32

const (
	Index_Property_ASCENDING  Index_Property_Direction = 1
	Index_Property_DESCENDING Index_Property_Direction = 2
)

var Index_Property_Direction_name = map[int32]string{
	1: "ASCENDING",
	2: "DESCENDING",
}
var Index_Property_Direction_value = map[string]int32{
	"ASCENDING":  1,
	"DESCENDING": 2,
}

func (x Index_Property_Direction) Enum() *Index_Property_Direction {
	p := new(Index_Property_Direction)
	*p = x
	return p
}
func (x Index_Property_Direction) String() string {
	return proto.EnumName(Index_Property_Direction_name, int32(x))
}
func (x Index_Property_Direction) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Index_Property_Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Index_Property_Direction_value, data, "Index_Property_Direction")
	if err != nil {
		return err
	}
	*x = Index_Property_Direction(value)
	return nil
}

type CompositeIndex_State int32

const (
	CompositeIndex_WRITE_ONLY CompositeIndex_State = 1
	CompositeIndex_READ_WRITE CompositeIndex_State = 2
	CompositeIndex_DELETED    CompositeIndex_State = 3
	CompositeIndex_ERROR      CompositeIndex_State = 4
)

var CompositeIndex_State_name = map[int32]string{
	1: "WRITE_ONLY",
	2: "READ_WRITE",
	3: "DELETED",
	4: "ERROR",
}
var CompositeIndex_State_value = map[string]int32{
	"WRITE_ONLY": 1,
	"READ_WRITE": 2,
	"DELETED":    3,
	"ERROR":      4,
}

func (x CompositeIndex_State) Enum() *CompositeIndex_State {
	p := new(CompositeIndex_State)
	*p = x
	return p
}
func (x CompositeIndex_State) String() string {
	return proto.EnumName(CompositeIndex_State_name, int32(x))
}
func (x CompositeIndex_State) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *CompositeIndex_State) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(CompositeIndex_State_value, data, "CompositeIndex_State")
	if err != nil {
		return err
	}
	*x = CompositeIndex_State(value)
	return nil
}

type Snapshot_Status int32

const (
	Snapshot_INACTIVE Snapshot_Status = 0
	Snapshot_ACTIVE   Snapshot_Status = 1
)

var Snapshot_Status_name = map[int32]string{
	0: "INACTIVE",
	1: "ACTIVE",
}
var Snapshot_Status_value = map[string]int32{
	"INACTIVE": 0,
	"ACTIVE":   1,
}

func (x Snapshot_Status) Enum() *Snapshot_Status {
	p := new(Snapshot_Status)
	*p = x
	return p
}
func (x Snapshot_Status) String() string {
	return proto.EnumName(Snapshot_Status_name, int32(x))
}
func (x Snapshot_Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Snapshot_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Snapshot_Status_value, data, "Snapshot_Status")
	if err != nil {
		return err
	}
	*x = Snapshot_Status(value)
	return nil
}

type Query_Hint int32

const (
	Query_ORDER_FIRST    Query_Hint = 1
	Query_ANCESTOR_FIRST Query_Hint = 2
	Query_FILTER_FIRST   Query_Hint = 3
)

var Query_Hint_name = map[int32]string{
	1: "ORDER_FIRST",
	2: "ANCESTOR_FIRST",
	3: "FILTER_FIRST",
}
var Query_Hint_value = map[string]int32{
	"ORDER_FIRST":    1,
	"ANCESTOR_FIRST": 2,
	"FILTER_FIRST":   3,
}

func (x Query_Hint) Enum() *Query_Hint {
	p := new(Query_Hint)
	*p = x
	return p
}
func (x Query_Hint) String() string {
	return proto.EnumName(Query_Hint_name, int32(x))
}
func (x Query_Hint) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Query_Hint) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Query_Hint_value, data, "Query_Hint")
	if err != nil {
		return err
	}
	*x = Query_Hint(value)
	return nil
}

type Query_Filter_Operator int32

const (
	Query_Filter_LESS_THAN             Query_Filter_Operator = 1
	Query_Filter_LESS_THAN_OR_EQUAL    Query_Filter_Operator = 2
	Query_Filter_GREATER_THAN          Query_Filter_Operator = 3
	Query_Filter_GREATER_THAN_OR_EQUAL Query_Filter_Operator = 4
	Query_Filter_EQUAL                 Query_Filter_Operator = 5
	Query_Filter_IN                    Query_Filter_Operator = 6
	Query_Filter_EXISTS                Query_Filter_Operator = 7
)

var Query_Filter_Operator_name = map[int32]string{
	1: "LESS_THAN",
	2: "LESS_THAN_OR_EQUAL",
	3: "GREATER_THAN",
	4: "GREATER_THAN_OR_EQUAL",
	5: "EQUAL",
	6: "IN",
	7: "EXISTS",
}
var Query_Filter_Operator_value = map[string]int32{
	"LESS_THAN":             1,
	"LESS_THAN_OR_EQUAL":    2,
	"GREATER_THAN":          3,
	"GREATER_THAN_OR_EQUAL": 4,
	"EQUAL":                 5,
	"IN":                    6,
	"EXISTS":                7,
}

func (x Query_Filter_Operator) Enum() *Query_Filter_Operator {
	p := new(Query_Filter_Operator)
	*p = x
	return p
}
func (x Query_Filter_Operator) String() string {
	return proto.EnumName(Query_Filter_Operator_name, int32(x))
}
func (x Query_Filter_Operator) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Query_Filter_Operator) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Query_Filter_Operator_value, data, "Query_Filter_Operator")
	if err != nil {
		return err
	}
	*x = Query_Filter_Operator(value)
	return nil
}

type Query_Order_Direction int32

const (
	Query_Order_ASCENDING  Query_Order_Direction = 1
	Query_Order_DESCENDING Query_Order_Direction = 2
)

var Query_Order_Direction_name = map[int32]string{
	1: "ASCENDING",
	2: "DESCENDING",
}
var Query_Order_Direction_value = map[string]int32{
	"ASCENDING":  1,
	"DESCENDING": 2,
}

func (x Query_Order_Direction) Enum() *Query_Order_Direction {
	p := new(Query_Order_Direction)
	*p = x
	return p
}
func (x Query_Order_Direction) String() string {
	return proto.EnumName(Query_Order_Direction_name, int32(x))
}
func (x Query_Order_Direction) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Query_Order_Direction) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Query_Order_Direction_value, data, "Query_Order_Direction")
	if err != nil {
		return err
	}
	*x = Query_Order_Direction(value)
	return nil
}

type Error_ErrorCode int32

const (
	Error_BAD_REQUEST                  Error_ErrorCode = 1
	Error_CONCURRENT_TRANSACTION       Error_ErrorCode = 2
	Error_INTERNAL_ERROR               Error_ErrorCode = 3
	Error_NEED_INDEX                   Error_ErrorCode = 4
	Error_TIMEOUT                      Error_ErrorCode = 5
	Error_PERMISSION_DENIED            Error_ErrorCode = 6
	Error_BIGTABLE_ERROR               Error_ErrorCode = 7
	Error_COMMITTED_BUT_STILL_APPLYING Error_ErrorCode = 8
	Error_CAPABILITY_DISABLED          Error_ErrorCode = 9
	Error_TRY_ALTERNATE_BACKEND        Error_ErrorCode = 10
	Error_SAFE_TIME_TOO_OLD            Error_ErrorCode = 11
)

var Error_ErrorCode_name = map[int32]string{
	1:  "BAD_REQUEST",
	2:  "CONCURRENT_TRANSACTION",
	3:  "INTERNAL_ERROR",
	4:  "NEED_INDEX",
	5:  "TIMEOUT",
	6:  "PERMISSION_DENIED",
	7:  "BIGTABLE_ERROR",
	8:  "COMMITTED_BUT_STILL_APPLYING",
	9:  "CAPABILITY_DISABLED",
	10: "TRY_ALTERNATE_BACKEND",
	11: "SAFE_TIME_TOO_OLD",
}
var Error_ErrorCode_value = map[string]int32{
	"BAD_REQUEST":                  1,
	"CONCURRENT_TRANSACTION":       2,
	"INTERNAL_ERROR":               3,
	"NEED_INDEX":                   4,
	"TIMEOUT":                      5,
	"PERMISSION_DENIED":            6,
	"BIGTABLE_ERROR":               7,
	"COMMITTED_BUT_STILL_APPLYING": 8,
	"CAPABILITY_DISABLED":          9,
	"TRY_ALTERNATE_BACKEND":        10,
	"SAFE_TIME_TOO_OLD":            11,
}

func (x Error_ErrorCode) Enum() *Error_ErrorCode {
	p := new(Error_ErrorCode)
	*p = x
	return p
}
func (x Error_ErrorCode) String() string {
	return proto.EnumName(Error_ErrorCode_name, int32(x))
}
func (x Error_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *Error_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Error_ErrorCode_value, data, "Error_ErrorCode")
	if err != nil {
		return err
	}
	*x = Error_ErrorCode(value)
	return nil
}

type Action struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *Action) Reset()         { *this = Action{} }
func (this *Action) String() string { return proto.CompactTextString(this) }
func (*Action) ProtoMessage()       {}

type StringProto struct {
	Value            *string `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StringProto) Reset()         { *this = StringProto{} }
func (this *StringProto) String() string { return proto.CompactTextString(this) }
func (*StringProto) ProtoMessage()       {}

func (this *StringProto) GetValue() string {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return ""
}

type Integer32Proto struct {
	Value            *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Integer32Proto) Reset()         { *this = Integer32Proto{} }
func (this *Integer32Proto) String() string { return proto.CompactTextString(this) }
func (*Integer32Proto) ProtoMessage()       {}

func (this *Integer32Proto) GetValue() int32 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type Integer64Proto struct {
	Value            *int64 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Integer64Proto) Reset()         { *this = Integer64Proto{} }
func (this *Integer64Proto) String() string { return proto.CompactTextString(this) }
func (*Integer64Proto) ProtoMessage()       {}

func (this *Integer64Proto) GetValue() int64 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type BoolProto struct {
	Value            *bool  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *BoolProto) Reset()         { *this = BoolProto{} }
func (this *BoolProto) String() string { return proto.CompactTextString(this) }
func (*BoolProto) ProtoMessage()       {}

func (this *BoolProto) GetValue() bool {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return false
}

type DoubleProto struct {
	Value            *float64 `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *DoubleProto) Reset()         { *this = DoubleProto{} }
func (this *DoubleProto) String() string { return proto.CompactTextString(this) }
func (*DoubleProto) ProtoMessage()       {}

func (this *DoubleProto) GetValue() float64 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type BytesProto struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *BytesProto) Reset()         { *this = BytesProto{} }
func (this *BytesProto) String() string { return proto.CompactTextString(this) }
func (*BytesProto) ProtoMessage()       {}

func (this *BytesProto) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type VoidProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *VoidProto) Reset()         { *this = VoidProto{} }
func (this *VoidProto) String() string { return proto.CompactTextString(this) }
func (*VoidProto) ProtoMessage()       {}

type PropertyValue struct {
	Int64Value       *int64                        `protobuf:"varint,1,opt,name=int64Value" json:"int64Value,omitempty"`
	BooleanValue     *bool                         `protobuf:"varint,2,opt,name=booleanValue" json:"booleanValue,omitempty"`
	StringValue      *string                       `protobuf:"bytes,3,opt,name=stringValue" json:"stringValue,omitempty"`
	DoubleValue      *float64                      `protobuf:"fixed64,4,opt,name=doubleValue" json:"doubleValue,omitempty"`
	Pointvalue       *PropertyValue_PointValue     `protobuf:"group,5,opt,name=PointValue" json:"pointvalue,omitempty"`
	Uservalue        *PropertyValue_UserValue      `protobuf:"group,8,opt,name=UserValue" json:"uservalue,omitempty"`
	Referencevalue   *PropertyValue_ReferenceValue `protobuf:"group,12,opt,name=ReferenceValue" json:"referencevalue,omitempty"`
	XXX_unrecognized []byte                        `json:"-"`
}

func (this *PropertyValue) Reset()         { *this = PropertyValue{} }
func (this *PropertyValue) String() string { return proto.CompactTextString(this) }
func (*PropertyValue) ProtoMessage()       {}

func (this *PropertyValue) GetInt64Value() int64 {
	if this != nil && this.Int64Value != nil {
		return *this.Int64Value
	}
	return 0
}

func (this *PropertyValue) GetBooleanValue() bool {
	if this != nil && this.BooleanValue != nil {
		return *this.BooleanValue
	}
	return false
}

func (this *PropertyValue) GetStringValue() string {
	if this != nil && this.StringValue != nil {
		return *this.StringValue
	}
	return ""
}

func (this *PropertyValue) GetDoubleValue() float64 {
	if this != nil && this.DoubleValue != nil {
		return *this.DoubleValue
	}
	return 0
}

func (this *PropertyValue) GetPointvalue() *PropertyValue_PointValue {
	if this != nil {
		return this.Pointvalue
	}
	return nil
}

func (this *PropertyValue) GetUservalue() *PropertyValue_UserValue {
	if this != nil {
		return this.Uservalue
	}
	return nil
}

func (this *PropertyValue) GetReferencevalue() *PropertyValue_ReferenceValue {
	if this != nil {
		return this.Referencevalue
	}
	return nil
}

type PropertyValue_PointValue struct {
	X *float64 `protobuf:"fixed64,6,req,name=x" json:"x,omitempty"`
	Y *float64 `protobuf:"fixed64,7,req,name=y" json:"y,omitempty"`
}

func (this *PropertyValue_PointValue) Reset() { *this = PropertyValue_PointValue{} }

func (this *PropertyValue_PointValue) GetX() float64 {
	if this != nil && this.X != nil {
		return *this.X
	}
	return 0
}

func (this *PropertyValue_PointValue) GetY() float64 {
	if this != nil && this.Y != nil {
		return *this.Y
	}
	return 0
}

type PropertyValue_UserValue struct {
	Email             *string `protobuf:"bytes,9,req,name=email" json:"email,omitempty"`
	AuthDomain        *string `protobuf:"bytes,10,req,name=auth_domain" json:"auth_domain,omitempty"`
	Nickname          *string `protobuf:"bytes,11,opt,name=nickname" json:"nickname,omitempty"`
	Gaiaid            *int64  `protobuf:"varint,18,req,name=gaiaid" json:"gaiaid,omitempty"`
	ObfuscatedGaiaid  *string `protobuf:"bytes,19,opt,name=obfuscated_gaiaid" json:"obfuscated_gaiaid,omitempty"`
	FederatedIdentity *string `protobuf:"bytes,21,opt,name=federated_identity" json:"federated_identity,omitempty"`
	FederatedProvider *string `protobuf:"bytes,22,opt,name=federated_provider" json:"federated_provider,omitempty"`
}

func (this *PropertyValue_UserValue) Reset() { *this = PropertyValue_UserValue{} }

func (this *PropertyValue_UserValue) GetEmail() string {
	if this != nil && this.Email != nil {
		return *this.Email
	}
	return ""
}

func (this *PropertyValue_UserValue) GetAuthDomain() string {
	if this != nil && this.AuthDomain != nil {
		return *this.AuthDomain
	}
	return ""
}

func (this *PropertyValue_UserValue) GetNickname() string {
	if this != nil && this.Nickname != nil {
		return *this.Nickname
	}
	return ""
}

func (this *PropertyValue_UserValue) GetGaiaid() int64 {
	if this != nil && this.Gaiaid != nil {
		return *this.Gaiaid
	}
	return 0
}

func (this *PropertyValue_UserValue) GetObfuscatedGaiaid() string {
	if this != nil && this.ObfuscatedGaiaid != nil {
		return *this.ObfuscatedGaiaid
	}
	return ""
}

func (this *PropertyValue_UserValue) GetFederatedIdentity() string {
	if this != nil && this.FederatedIdentity != nil {
		return *this.FederatedIdentity
	}
	return ""
}

func (this *PropertyValue_UserValue) GetFederatedProvider() string {
	if this != nil && this.FederatedProvider != nil {
		return *this.FederatedProvider
	}
	return ""
}

type PropertyValue_ReferenceValue struct {
	App         *string                                     `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	NameSpace   *string                                     `protobuf:"bytes,20,opt,name=name_space" json:"name_space,omitempty"`
	Pathelement []*PropertyValue_ReferenceValue_PathElement `protobuf:"group,14,rep,name=PathElement" json:"pathelement,omitempty"`
}

func (this *PropertyValue_ReferenceValue) Reset() { *this = PropertyValue_ReferenceValue{} }

func (this *PropertyValue_ReferenceValue) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *PropertyValue_ReferenceValue) GetNameSpace() string {
	if this != nil && this.NameSpace != nil {
		return *this.NameSpace
	}
	return ""
}

func (this *PropertyValue_ReferenceValue) GetPathelement() []*PropertyValue_ReferenceValue_PathElement {
	if this != nil {
		return this.Pathelement
	}
	return nil
}

type PropertyValue_ReferenceValue_PathElement struct {
	Type *string `protobuf:"bytes,15,req,name=type" json:"type,omitempty"`
	Id   *int64  `protobuf:"varint,16,opt,name=id" json:"id,omitempty"`
	Name *string `protobuf:"bytes,17,opt,name=name" json:"name,omitempty"`
}

func (this *PropertyValue_ReferenceValue_PathElement) Reset() {
	*this = PropertyValue_ReferenceValue_PathElement{}
}

func (this *PropertyValue_ReferenceValue_PathElement) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *PropertyValue_ReferenceValue_PathElement) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *PropertyValue_ReferenceValue_PathElement) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type Property struct {
	Meaning               *Property_Meaning               `protobuf:"varint,1,opt,name=meaning,enum=datastore.Property_Meaning,def=0" json:"meaning,omitempty"`
	MeaningUri            *string                         `protobuf:"bytes,2,opt,name=meaning_uri" json:"meaning_uri,omitempty"`
	Name                  *string                         `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Value                 *PropertyValue                  `protobuf:"bytes,5,req,name=value" json:"value,omitempty"`
	Multiple              *bool                           `protobuf:"varint,4,req,name=multiple" json:"multiple,omitempty"`
	Searchable            *bool                           `protobuf:"varint,6,opt,name=searchable,def=0" json:"searchable,omitempty"`
	FtsTokenizationOption *Property_FtsTokenizationOption `protobuf:"varint,8,opt,name=fts_tokenization_option,enum=datastore.Property_FtsTokenizationOption" json:"fts_tokenization_option,omitempty"`
	Locale                *string                         `protobuf:"bytes,9,opt,name=locale,def=en" json:"locale,omitempty"`
	XXX_unrecognized      []byte                          `json:"-"`
}

func (this *Property) Reset()         { *this = Property{} }
func (this *Property) String() string { return proto.CompactTextString(this) }
func (*Property) ProtoMessage()       {}

const Default_Property_Meaning Property_Meaning = Property_NO_MEANING
const Default_Property_Searchable bool = false
const Default_Property_Locale string = "en"

func (this *Property) GetMeaning() Property_Meaning {
	if this != nil && this.Meaning != nil {
		return *this.Meaning
	}
	return Default_Property_Meaning
}

func (this *Property) GetMeaningUri() string {
	if this != nil && this.MeaningUri != nil {
		return *this.MeaningUri
	}
	return ""
}

func (this *Property) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Property) GetValue() *PropertyValue {
	if this != nil {
		return this.Value
	}
	return nil
}

func (this *Property) GetMultiple() bool {
	if this != nil && this.Multiple != nil {
		return *this.Multiple
	}
	return false
}

func (this *Property) GetSearchable() bool {
	if this != nil && this.Searchable != nil {
		return *this.Searchable
	}
	return Default_Property_Searchable
}

func (this *Property) GetFtsTokenizationOption() Property_FtsTokenizationOption {
	if this != nil && this.FtsTokenizationOption != nil {
		return *this.FtsTokenizationOption
	}
	return 0
}

func (this *Property) GetLocale() string {
	if this != nil && this.Locale != nil {
		return *this.Locale
	}
	return Default_Property_Locale
}

type Path struct {
	Element          []*Path_Element `protobuf:"group,1,rep" json:"element,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (this *Path) Reset()         { *this = Path{} }
func (this *Path) String() string { return proto.CompactTextString(this) }
func (*Path) ProtoMessage()       {}

func (this *Path) GetElement() []*Path_Element {
	if this != nil {
		return this.Element
	}
	return nil
}

type Path_Element struct {
	Type *string `protobuf:"bytes,2,req,name=type" json:"type,omitempty"`
	Id   *int64  `protobuf:"varint,3,opt,name=id" json:"id,omitempty"`
	Name *string `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
}

func (this *Path_Element) Reset() { *this = Path_Element{} }

func (this *Path_Element) GetType() string {
	if this != nil && this.Type != nil {
		return *this.Type
	}
	return ""
}

func (this *Path_Element) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *Path_Element) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

type Reference struct {
	App              *string `protobuf:"bytes,13,req,name=app" json:"app,omitempty"`
	NameSpace        *string `protobuf:"bytes,20,opt,name=name_space" json:"name_space,omitempty"`
	Path             *Path   `protobuf:"bytes,14,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Reference) Reset()         { *this = Reference{} }
func (this *Reference) String() string { return proto.CompactTextString(this) }
func (*Reference) ProtoMessage()       {}

func (this *Reference) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *Reference) GetNameSpace() string {
	if this != nil && this.NameSpace != nil {
		return *this.NameSpace
	}
	return ""
}

func (this *Reference) GetPath() *Path {
	if this != nil {
		return this.Path
	}
	return nil
}

type User struct {
	Email             *string `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	AuthDomain        *string `protobuf:"bytes,2,req,name=auth_domain" json:"auth_domain,omitempty"`
	Nickname          *string `protobuf:"bytes,3,opt,name=nickname" json:"nickname,omitempty"`
	Gaiaid            *int64  `protobuf:"varint,4,req,name=gaiaid" json:"gaiaid,omitempty"`
	ObfuscatedGaiaid  *string `protobuf:"bytes,5,opt,name=obfuscated_gaiaid" json:"obfuscated_gaiaid,omitempty"`
	FederatedIdentity *string `protobuf:"bytes,6,opt,name=federated_identity" json:"federated_identity,omitempty"`
	FederatedProvider *string `protobuf:"bytes,7,opt,name=federated_provider" json:"federated_provider,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (this *User) Reset()         { *this = User{} }
func (this *User) String() string { return proto.CompactTextString(this) }
func (*User) ProtoMessage()       {}

func (this *User) GetEmail() string {
	if this != nil && this.Email != nil {
		return *this.Email
	}
	return ""
}

func (this *User) GetAuthDomain() string {
	if this != nil && this.AuthDomain != nil {
		return *this.AuthDomain
	}
	return ""
}

func (this *User) GetNickname() string {
	if this != nil && this.Nickname != nil {
		return *this.Nickname
	}
	return ""
}

func (this *User) GetGaiaid() int64 {
	if this != nil && this.Gaiaid != nil {
		return *this.Gaiaid
	}
	return 0
}

func (this *User) GetObfuscatedGaiaid() string {
	if this != nil && this.ObfuscatedGaiaid != nil {
		return *this.ObfuscatedGaiaid
	}
	return ""
}

func (this *User) GetFederatedIdentity() string {
	if this != nil && this.FederatedIdentity != nil {
		return *this.FederatedIdentity
	}
	return ""
}

func (this *User) GetFederatedProvider() string {
	if this != nil && this.FederatedProvider != nil {
		return *this.FederatedProvider
	}
	return ""
}

type EntityProto struct {
	Key              *Reference        `protobuf:"bytes,13,req,name=key" json:"key,omitempty"`
	EntityGroup      *Path             `protobuf:"bytes,16,req,name=entity_group" json:"entity_group,omitempty"`
	Owner            *User             `protobuf:"bytes,17,opt,name=owner" json:"owner,omitempty"`
	Kind             *EntityProto_Kind `protobuf:"varint,4,opt,name=kind,enum=datastore.EntityProto_Kind" json:"kind,omitempty"`
	KindUri          *string           `protobuf:"bytes,5,opt,name=kind_uri" json:"kind_uri,omitempty"`
	Property         []*Property       `protobuf:"bytes,14,rep,name=property" json:"property,omitempty"`
	RawProperty      []*Property       `protobuf:"bytes,15,rep,name=raw_property" json:"raw_property,omitempty"`
	Rank             *int32            `protobuf:"varint,18,opt,name=rank" json:"rank,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *EntityProto) Reset()         { *this = EntityProto{} }
func (this *EntityProto) String() string { return proto.CompactTextString(this) }
func (*EntityProto) ProtoMessage()       {}

func (this *EntityProto) GetKey() *Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *EntityProto) GetEntityGroup() *Path {
	if this != nil {
		return this.EntityGroup
	}
	return nil
}

func (this *EntityProto) GetOwner() *User {
	if this != nil {
		return this.Owner
	}
	return nil
}

func (this *EntityProto) GetKind() EntityProto_Kind {
	if this != nil && this.Kind != nil {
		return *this.Kind
	}
	return 0
}

func (this *EntityProto) GetKindUri() string {
	if this != nil && this.KindUri != nil {
		return *this.KindUri
	}
	return ""
}

func (this *EntityProto) GetProperty() []*Property {
	if this != nil {
		return this.Property
	}
	return nil
}

func (this *EntityProto) GetRawProperty() []*Property {
	if this != nil {
		return this.RawProperty
	}
	return nil
}

func (this *EntityProto) GetRank() int32 {
	if this != nil && this.Rank != nil {
		return *this.Rank
	}
	return 0
}

type CompositeProperty struct {
	IndexId          *int64   `protobuf:"varint,1,req,name=index_id" json:"index_id,omitempty"`
	Value            []string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *CompositeProperty) Reset()         { *this = CompositeProperty{} }
func (this *CompositeProperty) String() string { return proto.CompactTextString(this) }
func (*CompositeProperty) ProtoMessage()       {}

func (this *CompositeProperty) GetIndexId() int64 {
	if this != nil && this.IndexId != nil {
		return *this.IndexId
	}
	return 0
}

func (this *CompositeProperty) GetValue() []string {
	if this != nil {
		return this.Value
	}
	return nil
}

type Index struct {
	EntityType       *string           `protobuf:"bytes,1,req,name=entity_type" json:"entity_type,omitempty"`
	Ancestor         *bool             `protobuf:"varint,5,req,name=ancestor" json:"ancestor,omitempty"`
	Property         []*Index_Property `protobuf:"group,2,rep" json:"property,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *Index) Reset()         { *this = Index{} }
func (this *Index) String() string { return proto.CompactTextString(this) }
func (*Index) ProtoMessage()       {}

func (this *Index) GetEntityType() string {
	if this != nil && this.EntityType != nil {
		return *this.EntityType
	}
	return ""
}

func (this *Index) GetAncestor() bool {
	if this != nil && this.Ancestor != nil {
		return *this.Ancestor
	}
	return false
}

func (this *Index) GetProperty() []*Index_Property {
	if this != nil {
		return this.Property
	}
	return nil
}

type Index_Property struct {
	Name      *string                   `protobuf:"bytes,3,req,name=name" json:"name,omitempty"`
	Direction *Index_Property_Direction `protobuf:"varint,4,opt,name=direction,enum=datastore.Index_Property_Direction,def=1" json:"direction,omitempty"`
}

func (this *Index_Property) Reset() { *this = Index_Property{} }

const Default_Index_Property_Direction Index_Property_Direction = Index_Property_ASCENDING

func (this *Index_Property) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *Index_Property) GetDirection() Index_Property_Direction {
	if this != nil && this.Direction != nil {
		return *this.Direction
	}
	return Default_Index_Property_Direction
}

type CompositeIndex struct {
	AppId             *string               `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	Id                *int64                `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Definition        *Index                `protobuf:"bytes,3,req,name=definition" json:"definition,omitempty"`
	State             *CompositeIndex_State `protobuf:"varint,4,req,name=state,enum=datastore.CompositeIndex_State" json:"state,omitempty"`
	OnlyUseIfRequired *bool                 `protobuf:"varint,6,opt,name=only_use_if_required,def=0" json:"only_use_if_required,omitempty"`
	XXX_unrecognized  []byte                `json:"-"`
}

func (this *CompositeIndex) Reset()         { *this = CompositeIndex{} }
func (this *CompositeIndex) String() string { return proto.CompactTextString(this) }
func (*CompositeIndex) ProtoMessage()       {}

const Default_CompositeIndex_OnlyUseIfRequired bool = false

func (this *CompositeIndex) GetAppId() string {
	if this != nil && this.AppId != nil {
		return *this.AppId
	}
	return ""
}

func (this *CompositeIndex) GetId() int64 {
	if this != nil && this.Id != nil {
		return *this.Id
	}
	return 0
}

func (this *CompositeIndex) GetDefinition() *Index {
	if this != nil {
		return this.Definition
	}
	return nil
}

func (this *CompositeIndex) GetState() CompositeIndex_State {
	if this != nil && this.State != nil {
		return *this.State
	}
	return 0
}

func (this *CompositeIndex) GetOnlyUseIfRequired() bool {
	if this != nil && this.OnlyUseIfRequired != nil {
		return *this.OnlyUseIfRequired
	}
	return Default_CompositeIndex_OnlyUseIfRequired
}

type Snapshot struct {
	Ts               *int64 `protobuf:"varint,1,req,name=ts" json:"ts,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Snapshot) Reset()         { *this = Snapshot{} }
func (this *Snapshot) String() string { return proto.CompactTextString(this) }
func (*Snapshot) ProtoMessage()       {}

func (this *Snapshot) GetTs() int64 {
	if this != nil && this.Ts != nil {
		return *this.Ts
	}
	return 0
}

type Transaction struct {
	Handle           *uint64 `protobuf:"fixed64,1,req,name=handle" json:"handle,omitempty"`
	App              *string `protobuf:"bytes,2,req,name=app" json:"app,omitempty"`
	MarkChanges      *bool   `protobuf:"varint,3,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Transaction) Reset()         { *this = Transaction{} }
func (this *Transaction) String() string { return proto.CompactTextString(this) }
func (*Transaction) ProtoMessage()       {}

const Default_Transaction_MarkChanges bool = false

func (this *Transaction) GetHandle() uint64 {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return 0
}

func (this *Transaction) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *Transaction) GetMarkChanges() bool {
	if this != nil && this.MarkChanges != nil {
		return *this.MarkChanges
	}
	return Default_Transaction_MarkChanges
}

type Query struct {
	App                 *string           `protobuf:"bytes,1,req,name=app" json:"app,omitempty"`
	NameSpace           *string           `protobuf:"bytes,29,opt,name=name_space" json:"name_space,omitempty"`
	Kind                *string           `protobuf:"bytes,3,opt,name=kind" json:"kind,omitempty"`
	Ancestor            *Reference        `protobuf:"bytes,17,opt,name=ancestor" json:"ancestor,omitempty"`
	Filter              []*Query_Filter   `protobuf:"group,4,rep" json:"filter,omitempty"`
	SearchQuery         *string           `protobuf:"bytes,8,opt,name=search_query" json:"search_query,omitempty"`
	Order               []*Query_Order    `protobuf:"group,9,rep" json:"order,omitempty"`
	Hint                *Query_Hint       `protobuf:"varint,18,opt,name=hint,enum=datastore.Query_Hint" json:"hint,omitempty"`
	Count               *int32            `protobuf:"varint,23,opt,name=count" json:"count,omitempty"`
	Offset              *int32            `protobuf:"varint,12,opt,name=offset,def=0" json:"offset,omitempty"`
	Limit               *int32            `protobuf:"varint,16,opt,name=limit" json:"limit,omitempty"`
	CompiledCursor      *CompiledCursor   `protobuf:"bytes,30,opt,name=compiled_cursor" json:"compiled_cursor,omitempty"`
	EndCompiledCursor   *CompiledCursor   `protobuf:"bytes,31,opt,name=end_compiled_cursor" json:"end_compiled_cursor,omitempty"`
	CompositeIndex      []*CompositeIndex `protobuf:"bytes,19,rep,name=composite_index" json:"composite_index,omitempty"`
	RequirePerfectPlan  *bool             `protobuf:"varint,20,opt,name=require_perfect_plan,def=0" json:"require_perfect_plan,omitempty"`
	KeysOnly            *bool             `protobuf:"varint,21,opt,name=keys_only,def=0" json:"keys_only,omitempty"`
	Transaction         *Transaction      `protobuf:"bytes,22,opt,name=transaction" json:"transaction,omitempty"`
	Compile             *bool             `protobuf:"varint,25,opt,name=compile,def=0" json:"compile,omitempty"`
	FailoverMs          *int64            `protobuf:"varint,26,opt,name=failover_ms" json:"failover_ms,omitempty"`
	Strong              *bool             `protobuf:"varint,32,opt,name=strong" json:"strong,omitempty"`
	PropertyName        []string          `protobuf:"bytes,33,rep,name=property_name" json:"property_name,omitempty"`
	GroupByPropertyName []string          `protobuf:"bytes,34,rep,name=group_by_property_name" json:"group_by_property_name,omitempty"`
	Distinct            *bool             `protobuf:"varint,24,opt,name=distinct" json:"distinct,omitempty"`
	MinSafeTimeSeconds  *int64            `protobuf:"varint,35,opt,name=min_safe_time_seconds" json:"min_safe_time_seconds,omitempty"`
	SafeReplicaName     []string          `protobuf:"bytes,36,rep,name=safe_replica_name" json:"safe_replica_name,omitempty"`
	XXX_unrecognized    []byte            `json:"-"`
}

func (this *Query) Reset()         { *this = Query{} }
func (this *Query) String() string { return proto.CompactTextString(this) }
func (*Query) ProtoMessage()       {}

const Default_Query_Offset int32 = 0
const Default_Query_RequirePerfectPlan bool = false
const Default_Query_KeysOnly bool = false
const Default_Query_Compile bool = false

func (this *Query) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *Query) GetNameSpace() string {
	if this != nil && this.NameSpace != nil {
		return *this.NameSpace
	}
	return ""
}

func (this *Query) GetKind() string {
	if this != nil && this.Kind != nil {
		return *this.Kind
	}
	return ""
}

func (this *Query) GetAncestor() *Reference {
	if this != nil {
		return this.Ancestor
	}
	return nil
}

func (this *Query) GetFilter() []*Query_Filter {
	if this != nil {
		return this.Filter
	}
	return nil
}

func (this *Query) GetSearchQuery() string {
	if this != nil && this.SearchQuery != nil {
		return *this.SearchQuery
	}
	return ""
}

func (this *Query) GetOrder() []*Query_Order {
	if this != nil {
		return this.Order
	}
	return nil
}

func (this *Query) GetHint() Query_Hint {
	if this != nil && this.Hint != nil {
		return *this.Hint
	}
	return 0
}

func (this *Query) GetCount() int32 {
	if this != nil && this.Count != nil {
		return *this.Count
	}
	return 0
}

func (this *Query) GetOffset() int32 {
	if this != nil && this.Offset != nil {
		return *this.Offset
	}
	return Default_Query_Offset
}

func (this *Query) GetLimit() int32 {
	if this != nil && this.Limit != nil {
		return *this.Limit
	}
	return 0
}

func (this *Query) GetCompiledCursor() *CompiledCursor {
	if this != nil {
		return this.CompiledCursor
	}
	return nil
}

func (this *Query) GetEndCompiledCursor() *CompiledCursor {
	if this != nil {
		return this.EndCompiledCursor
	}
	return nil
}

func (this *Query) GetCompositeIndex() []*CompositeIndex {
	if this != nil {
		return this.CompositeIndex
	}
	return nil
}

func (this *Query) GetRequirePerfectPlan() bool {
	if this != nil && this.RequirePerfectPlan != nil {
		return *this.RequirePerfectPlan
	}
	return Default_Query_RequirePerfectPlan
}

func (this *Query) GetKeysOnly() bool {
	if this != nil && this.KeysOnly != nil {
		return *this.KeysOnly
	}
	return Default_Query_KeysOnly
}

func (this *Query) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *Query) GetCompile() bool {
	if this != nil && this.Compile != nil {
		return *this.Compile
	}
	return Default_Query_Compile
}

func (this *Query) GetFailoverMs() int64 {
	if this != nil && this.FailoverMs != nil {
		return *this.FailoverMs
	}
	return 0
}

func (this *Query) GetStrong() bool {
	if this != nil && this.Strong != nil {
		return *this.Strong
	}
	return false
}

func (this *Query) GetPropertyName() []string {
	if this != nil {
		return this.PropertyName
	}
	return nil
}

func (this *Query) GetGroupByPropertyName() []string {
	if this != nil {
		return this.GroupByPropertyName
	}
	return nil
}

func (this *Query) GetDistinct() bool {
	if this != nil && this.Distinct != nil {
		return *this.Distinct
	}
	return false
}

func (this *Query) GetMinSafeTimeSeconds() int64 {
	if this != nil && this.MinSafeTimeSeconds != nil {
		return *this.MinSafeTimeSeconds
	}
	return 0
}

func (this *Query) GetSafeReplicaName() []string {
	if this != nil {
		return this.SafeReplicaName
	}
	return nil
}

type Query_Filter struct {
	Op       *Query_Filter_Operator `protobuf:"varint,6,req,name=op,enum=datastore.Query_Filter_Operator" json:"op,omitempty"`
	Property []*Property            `protobuf:"bytes,14,rep,name=property" json:"property,omitempty"`
}

func (this *Query_Filter) Reset() { *this = Query_Filter{} }

func (this *Query_Filter) GetOp() Query_Filter_Operator {
	if this != nil && this.Op != nil {
		return *this.Op
	}
	return 0
}

func (this *Query_Filter) GetProperty() []*Property {
	if this != nil {
		return this.Property
	}
	return nil
}

type Query_Order struct {
	Property  *string                `protobuf:"bytes,10,req,name=property" json:"property,omitempty"`
	Direction *Query_Order_Direction `protobuf:"varint,11,opt,name=direction,enum=datastore.Query_Order_Direction,def=1" json:"direction,omitempty"`
}

func (this *Query_Order) Reset() { *this = Query_Order{} }

const Default_Query_Order_Direction Query_Order_Direction = Query_Order_ASCENDING

func (this *Query_Order) GetProperty() string {
	if this != nil && this.Property != nil {
		return *this.Property
	}
	return ""
}

func (this *Query_Order) GetDirection() Query_Order_Direction {
	if this != nil && this.Direction != nil {
		return *this.Direction
	}
	return Default_Query_Order_Direction
}

type CompiledQuery struct {
	Primaryscan       *CompiledQuery_PrimaryScan     `protobuf:"group,1,req,name=PrimaryScan" json:"primaryscan,omitempty"`
	Mergejoinscan     []*CompiledQuery_MergeJoinScan `protobuf:"group,7,rep,name=MergeJoinScan" json:"mergejoinscan,omitempty"`
	IndexDef          *Index                         `protobuf:"bytes,21,opt,name=index_def" json:"index_def,omitempty"`
	Offset            *int32                         `protobuf:"varint,10,opt,name=offset,def=0" json:"offset,omitempty"`
	Limit             *int32                         `protobuf:"varint,11,opt,name=limit" json:"limit,omitempty"`
	KeysOnly          *bool                          `protobuf:"varint,12,req,name=keys_only" json:"keys_only,omitempty"`
	PropertyName      []string                       `protobuf:"bytes,24,rep,name=property_name" json:"property_name,omitempty"`
	DistinctInfixSize *int32                         `protobuf:"varint,25,opt,name=distinct_infix_size" json:"distinct_infix_size,omitempty"`
	Entityfilter      *CompiledQuery_EntityFilter    `protobuf:"group,13,opt,name=EntityFilter" json:"entityfilter,omitempty"`
	XXX_unrecognized  []byte                         `json:"-"`
}

func (this *CompiledQuery) Reset()         { *this = CompiledQuery{} }
func (this *CompiledQuery) String() string { return proto.CompactTextString(this) }
func (*CompiledQuery) ProtoMessage()       {}

const Default_CompiledQuery_Offset int32 = 0

func (this *CompiledQuery) GetPrimaryscan() *CompiledQuery_PrimaryScan {
	if this != nil {
		return this.Primaryscan
	}
	return nil
}

func (this *CompiledQuery) GetMergejoinscan() []*CompiledQuery_MergeJoinScan {
	if this != nil {
		return this.Mergejoinscan
	}
	return nil
}

func (this *CompiledQuery) GetIndexDef() *Index {
	if this != nil {
		return this.IndexDef
	}
	return nil
}

func (this *CompiledQuery) GetOffset() int32 {
	if this != nil && this.Offset != nil {
		return *this.Offset
	}
	return Default_CompiledQuery_Offset
}

func (this *CompiledQuery) GetLimit() int32 {
	if this != nil && this.Limit != nil {
		return *this.Limit
	}
	return 0
}

func (this *CompiledQuery) GetKeysOnly() bool {
	if this != nil && this.KeysOnly != nil {
		return *this.KeysOnly
	}
	return false
}

func (this *CompiledQuery) GetPropertyName() []string {
	if this != nil {
		return this.PropertyName
	}
	return nil
}

func (this *CompiledQuery) GetDistinctInfixSize() int32 {
	if this != nil && this.DistinctInfixSize != nil {
		return *this.DistinctInfixSize
	}
	return 0
}

func (this *CompiledQuery) GetEntityfilter() *CompiledQuery_EntityFilter {
	if this != nil {
		return this.Entityfilter
	}
	return nil
}

type CompiledQuery_PrimaryScan struct {
	IndexName                  *string  `protobuf:"bytes,2,opt,name=index_name" json:"index_name,omitempty"`
	StartKey                   *string  `protobuf:"bytes,3,opt,name=start_key" json:"start_key,omitempty"`
	StartInclusive             *bool    `protobuf:"varint,4,opt,name=start_inclusive" json:"start_inclusive,omitempty"`
	EndKey                     *string  `protobuf:"bytes,5,opt,name=end_key" json:"end_key,omitempty"`
	EndInclusive               *bool    `protobuf:"varint,6,opt,name=end_inclusive" json:"end_inclusive,omitempty"`
	StartPostfixValue          []string `protobuf:"bytes,22,rep,name=start_postfix_value" json:"start_postfix_value,omitempty"`
	EndPostfixValue            []string `protobuf:"bytes,23,rep,name=end_postfix_value" json:"end_postfix_value,omitempty"`
	EndUnappliedLogTimestampUs *int64   `protobuf:"varint,19,opt,name=end_unapplied_log_timestamp_us" json:"end_unapplied_log_timestamp_us,omitempty"`
}

func (this *CompiledQuery_PrimaryScan) Reset() { *this = CompiledQuery_PrimaryScan{} }

func (this *CompiledQuery_PrimaryScan) GetIndexName() string {
	if this != nil && this.IndexName != nil {
		return *this.IndexName
	}
	return ""
}

func (this *CompiledQuery_PrimaryScan) GetStartKey() string {
	if this != nil && this.StartKey != nil {
		return *this.StartKey
	}
	return ""
}

func (this *CompiledQuery_PrimaryScan) GetStartInclusive() bool {
	if this != nil && this.StartInclusive != nil {
		return *this.StartInclusive
	}
	return false
}

func (this *CompiledQuery_PrimaryScan) GetEndKey() string {
	if this != nil && this.EndKey != nil {
		return *this.EndKey
	}
	return ""
}

func (this *CompiledQuery_PrimaryScan) GetEndInclusive() bool {
	if this != nil && this.EndInclusive != nil {
		return *this.EndInclusive
	}
	return false
}

func (this *CompiledQuery_PrimaryScan) GetStartPostfixValue() []string {
	if this != nil {
		return this.StartPostfixValue
	}
	return nil
}

func (this *CompiledQuery_PrimaryScan) GetEndPostfixValue() []string {
	if this != nil {
		return this.EndPostfixValue
	}
	return nil
}

func (this *CompiledQuery_PrimaryScan) GetEndUnappliedLogTimestampUs() int64 {
	if this != nil && this.EndUnappliedLogTimestampUs != nil {
		return *this.EndUnappliedLogTimestampUs
	}
	return 0
}

type CompiledQuery_MergeJoinScan struct {
	IndexName   *string  `protobuf:"bytes,8,req,name=index_name" json:"index_name,omitempty"`
	PrefixValue []string `protobuf:"bytes,9,rep,name=prefix_value" json:"prefix_value,omitempty"`
	ValuePrefix *bool    `protobuf:"varint,20,opt,name=value_prefix,def=0" json:"value_prefix,omitempty"`
}

func (this *CompiledQuery_MergeJoinScan) Reset() { *this = CompiledQuery_MergeJoinScan{} }

const Default_CompiledQuery_MergeJoinScan_ValuePrefix bool = false

func (this *CompiledQuery_MergeJoinScan) GetIndexName() string {
	if this != nil && this.IndexName != nil {
		return *this.IndexName
	}
	return ""
}

func (this *CompiledQuery_MergeJoinScan) GetPrefixValue() []string {
	if this != nil {
		return this.PrefixValue
	}
	return nil
}

func (this *CompiledQuery_MergeJoinScan) GetValuePrefix() bool {
	if this != nil && this.ValuePrefix != nil {
		return *this.ValuePrefix
	}
	return Default_CompiledQuery_MergeJoinScan_ValuePrefix
}

type CompiledQuery_EntityFilter struct {
	Distinct *bool      `protobuf:"varint,14,opt,name=distinct,def=0" json:"distinct,omitempty"`
	Kind     *string    `protobuf:"bytes,17,opt,name=kind" json:"kind,omitempty"`
	Ancestor *Reference `protobuf:"bytes,18,opt,name=ancestor" json:"ancestor,omitempty"`
}

func (this *CompiledQuery_EntityFilter) Reset() { *this = CompiledQuery_EntityFilter{} }

const Default_CompiledQuery_EntityFilter_Distinct bool = false

func (this *CompiledQuery_EntityFilter) GetDistinct() bool {
	if this != nil && this.Distinct != nil {
		return *this.Distinct
	}
	return Default_CompiledQuery_EntityFilter_Distinct
}

func (this *CompiledQuery_EntityFilter) GetKind() string {
	if this != nil && this.Kind != nil {
		return *this.Kind
	}
	return ""
}

func (this *CompiledQuery_EntityFilter) GetAncestor() *Reference {
	if this != nil {
		return this.Ancestor
	}
	return nil
}

type CompiledCursor struct {
	MultiqueryIndex  *int32                     `protobuf:"varint,1,opt,name=multiquery_index" json:"multiquery_index,omitempty"`
	Position         []*CompiledCursor_Position `protobuf:"group,2,rep" json:"position,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (this *CompiledCursor) Reset()         { *this = CompiledCursor{} }
func (this *CompiledCursor) String() string { return proto.CompactTextString(this) }
func (*CompiledCursor) ProtoMessage()       {}

func (this *CompiledCursor) GetMultiqueryIndex() int32 {
	if this != nil && this.MultiqueryIndex != nil {
		return *this.MultiqueryIndex
	}
	return 0
}

func (this *CompiledCursor) GetPosition() []*CompiledCursor_Position {
	if this != nil {
		return this.Position
	}
	return nil
}

type CompiledCursor_Position struct {
	StartKey       *string                               `protobuf:"bytes,27,opt,name=start_key" json:"start_key,omitempty"`
	Indexvalue     []*CompiledCursor_Position_IndexValue `protobuf:"group,29,rep,name=IndexValue" json:"indexvalue,omitempty"`
	Key            *Reference                            `protobuf:"bytes,32,opt,name=key" json:"key,omitempty"`
	StartInclusive *bool                                 `protobuf:"varint,28,opt,name=start_inclusive,def=1" json:"start_inclusive,omitempty"`
}

func (this *CompiledCursor_Position) Reset() { *this = CompiledCursor_Position{} }

const Default_CompiledCursor_Position_StartInclusive bool = true

func (this *CompiledCursor_Position) GetStartKey() string {
	if this != nil && this.StartKey != nil {
		return *this.StartKey
	}
	return ""
}

func (this *CompiledCursor_Position) GetIndexvalue() []*CompiledCursor_Position_IndexValue {
	if this != nil {
		return this.Indexvalue
	}
	return nil
}

func (this *CompiledCursor_Position) GetKey() *Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *CompiledCursor_Position) GetStartInclusive() bool {
	if this != nil && this.StartInclusive != nil {
		return *this.StartInclusive
	}
	return Default_CompiledCursor_Position_StartInclusive
}

type CompiledCursor_Position_IndexValue struct {
	Property *string        `protobuf:"bytes,30,opt,name=property" json:"property,omitempty"`
	Value    *PropertyValue `protobuf:"bytes,31,req,name=value" json:"value,omitempty"`
}

func (this *CompiledCursor_Position_IndexValue) Reset() { *this = CompiledCursor_Position_IndexValue{} }

func (this *CompiledCursor_Position_IndexValue) GetProperty() string {
	if this != nil && this.Property != nil {
		return *this.Property
	}
	return ""
}

func (this *CompiledCursor_Position_IndexValue) GetValue() *PropertyValue {
	if this != nil {
		return this.Value
	}
	return nil
}

type Cursor struct {
	Cursor           *uint64 `protobuf:"fixed64,1,req,name=cursor" json:"cursor,omitempty"`
	App              *string `protobuf:"bytes,2,opt,name=app" json:"app,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Cursor) Reset()         { *this = Cursor{} }
func (this *Cursor) String() string { return proto.CompactTextString(this) }
func (*Cursor) ProtoMessage()       {}

func (this *Cursor) GetCursor() uint64 {
	if this != nil && this.Cursor != nil {
		return *this.Cursor
	}
	return 0
}

func (this *Cursor) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

type Error struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *Error) Reset()         { *this = Error{} }
func (this *Error) String() string { return proto.CompactTextString(this) }
func (*Error) ProtoMessage()       {}

type Cost struct {
	IndexWrites      *int32           `protobuf:"varint,1,opt,name=index_writes" json:"index_writes,omitempty"`
	IndexWriteBytes  *int32           `protobuf:"varint,2,opt,name=index_write_bytes" json:"index_write_bytes,omitempty"`
	EntityWrites     *int32           `protobuf:"varint,3,opt,name=entity_writes" json:"entity_writes,omitempty"`
	EntityWriteBytes *int32           `protobuf:"varint,4,opt,name=entity_write_bytes" json:"entity_write_bytes,omitempty"`
	Commitcost       *Cost_CommitCost `protobuf:"group,5,opt,name=CommitCost" json:"commitcost,omitempty"`
	XXX_unrecognized []byte           `json:"-"`
}

func (this *Cost) Reset()         { *this = Cost{} }
func (this *Cost) String() string { return proto.CompactTextString(this) }
func (*Cost) ProtoMessage()       {}

func (this *Cost) GetIndexWrites() int32 {
	if this != nil && this.IndexWrites != nil {
		return *this.IndexWrites
	}
	return 0
}

func (this *Cost) GetIndexWriteBytes() int32 {
	if this != nil && this.IndexWriteBytes != nil {
		return *this.IndexWriteBytes
	}
	return 0
}

func (this *Cost) GetEntityWrites() int32 {
	if this != nil && this.EntityWrites != nil {
		return *this.EntityWrites
	}
	return 0
}

func (this *Cost) GetEntityWriteBytes() int32 {
	if this != nil && this.EntityWriteBytes != nil {
		return *this.EntityWriteBytes
	}
	return 0
}

func (this *Cost) GetCommitcost() *Cost_CommitCost {
	if this != nil {
		return this.Commitcost
	}
	return nil
}

type Cost_CommitCost struct {
	RequestedEntityPuts    *int32 `protobuf:"varint,6,opt,name=requested_entity_puts" json:"requested_entity_puts,omitempty"`
	RequestedEntityDeletes *int32 `protobuf:"varint,7,opt,name=requested_entity_deletes" json:"requested_entity_deletes,omitempty"`
}

func (this *Cost_CommitCost) Reset() { *this = Cost_CommitCost{} }

func (this *Cost_CommitCost) GetRequestedEntityPuts() int32 {
	if this != nil && this.RequestedEntityPuts != nil {
		return *this.RequestedEntityPuts
	}
	return 0
}

func (this *Cost_CommitCost) GetRequestedEntityDeletes() int32 {
	if this != nil && this.RequestedEntityDeletes != nil {
		return *this.RequestedEntityDeletes
	}
	return 0
}

type GetRequest struct {
	Key              []*Reference `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	Transaction      *Transaction `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	FailoverMs       *int64       `protobuf:"varint,3,opt,name=failover_ms" json:"failover_ms,omitempty"`
	Strong           *bool        `protobuf:"varint,4,opt,name=strong" json:"strong,omitempty"`
	AllowDeferred    *bool        `protobuf:"varint,5,opt,name=allow_deferred,def=0" json:"allow_deferred,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *GetRequest) Reset()         { *this = GetRequest{} }
func (this *GetRequest) String() string { return proto.CompactTextString(this) }
func (*GetRequest) ProtoMessage()       {}

const Default_GetRequest_AllowDeferred bool = false

func (this *GetRequest) GetKey() []*Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *GetRequest) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *GetRequest) GetFailoverMs() int64 {
	if this != nil && this.FailoverMs != nil {
		return *this.FailoverMs
	}
	return 0
}

func (this *GetRequest) GetStrong() bool {
	if this != nil && this.Strong != nil {
		return *this.Strong
	}
	return false
}

func (this *GetRequest) GetAllowDeferred() bool {
	if this != nil && this.AllowDeferred != nil {
		return *this.AllowDeferred
	}
	return Default_GetRequest_AllowDeferred
}

type GetResponse struct {
	Entity           []*GetResponse_Entity `protobuf:"group,1,rep" json:"entity,omitempty"`
	Deferred         []*Reference          `protobuf:"bytes,5,rep,name=deferred" json:"deferred,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (this *GetResponse) Reset()         { *this = GetResponse{} }
func (this *GetResponse) String() string { return proto.CompactTextString(this) }
func (*GetResponse) ProtoMessage()       {}

func (this *GetResponse) GetEntity() []*GetResponse_Entity {
	if this != nil {
		return this.Entity
	}
	return nil
}

func (this *GetResponse) GetDeferred() []*Reference {
	if this != nil {
		return this.Deferred
	}
	return nil
}

type GetResponse_Entity struct {
	Entity  *EntityProto `protobuf:"bytes,2,opt,name=entity" json:"entity,omitempty"`
	Key     *Reference   `protobuf:"bytes,4,opt,name=key" json:"key,omitempty"`
	Version *int64       `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
}

func (this *GetResponse_Entity) Reset() { *this = GetResponse_Entity{} }

func (this *GetResponse_Entity) GetEntity() *EntityProto {
	if this != nil {
		return this.Entity
	}
	return nil
}

func (this *GetResponse_Entity) GetKey() *Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *GetResponse_Entity) GetVersion() int64 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

type PutRequest struct {
	Entity           []*EntityProto    `protobuf:"bytes,1,rep,name=entity" json:"entity,omitempty"`
	Transaction      *Transaction      `protobuf:"bytes,2,opt,name=transaction" json:"transaction,omitempty"`
	CompositeIndex   []*CompositeIndex `protobuf:"bytes,3,rep,name=composite_index" json:"composite_index,omitempty"`
	Trusted          *bool             `protobuf:"varint,4,opt,name=trusted,def=0" json:"trusted,omitempty"`
	Force            *bool             `protobuf:"varint,7,opt,name=force,def=0" json:"force,omitempty"`
	MarkChanges      *bool             `protobuf:"varint,8,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	Snapshot         []*Snapshot       `protobuf:"bytes,9,rep,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *PutRequest) Reset()         { *this = PutRequest{} }
func (this *PutRequest) String() string { return proto.CompactTextString(this) }
func (*PutRequest) ProtoMessage()       {}

const Default_PutRequest_Trusted bool = false
const Default_PutRequest_Force bool = false
const Default_PutRequest_MarkChanges bool = false

func (this *PutRequest) GetEntity() []*EntityProto {
	if this != nil {
		return this.Entity
	}
	return nil
}

func (this *PutRequest) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *PutRequest) GetCompositeIndex() []*CompositeIndex {
	if this != nil {
		return this.CompositeIndex
	}
	return nil
}

func (this *PutRequest) GetTrusted() bool {
	if this != nil && this.Trusted != nil {
		return *this.Trusted
	}
	return Default_PutRequest_Trusted
}

func (this *PutRequest) GetForce() bool {
	if this != nil && this.Force != nil {
		return *this.Force
	}
	return Default_PutRequest_Force
}

func (this *PutRequest) GetMarkChanges() bool {
	if this != nil && this.MarkChanges != nil {
		return *this.MarkChanges
	}
	return Default_PutRequest_MarkChanges
}

func (this *PutRequest) GetSnapshot() []*Snapshot {
	if this != nil {
		return this.Snapshot
	}
	return nil
}

type PutResponse struct {
	Key              []*Reference `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	Cost             *Cost        `protobuf:"bytes,2,opt,name=cost" json:"cost,omitempty"`
	Version          []int64      `protobuf:"varint,3,rep,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *PutResponse) Reset()         { *this = PutResponse{} }
func (this *PutResponse) String() string { return proto.CompactTextString(this) }
func (*PutResponse) ProtoMessage()       {}

func (this *PutResponse) GetKey() []*Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *PutResponse) GetCost() *Cost {
	if this != nil {
		return this.Cost
	}
	return nil
}

func (this *PutResponse) GetVersion() []int64 {
	if this != nil {
		return this.Version
	}
	return nil
}

type TouchRequest struct {
	Key              []*Reference      `protobuf:"bytes,1,rep,name=key" json:"key,omitempty"`
	CompositeIndex   []*CompositeIndex `protobuf:"bytes,2,rep,name=composite_index" json:"composite_index,omitempty"`
	Force            *bool             `protobuf:"varint,3,opt,name=force,def=0" json:"force,omitempty"`
	Snapshot         []*Snapshot       `protobuf:"bytes,9,rep,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *TouchRequest) Reset()         { *this = TouchRequest{} }
func (this *TouchRequest) String() string { return proto.CompactTextString(this) }
func (*TouchRequest) ProtoMessage()       {}

const Default_TouchRequest_Force bool = false

func (this *TouchRequest) GetKey() []*Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *TouchRequest) GetCompositeIndex() []*CompositeIndex {
	if this != nil {
		return this.CompositeIndex
	}
	return nil
}

func (this *TouchRequest) GetForce() bool {
	if this != nil && this.Force != nil {
		return *this.Force
	}
	return Default_TouchRequest_Force
}

func (this *TouchRequest) GetSnapshot() []*Snapshot {
	if this != nil {
		return this.Snapshot
	}
	return nil
}

type TouchResponse struct {
	Cost             *Cost  `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TouchResponse) Reset()         { *this = TouchResponse{} }
func (this *TouchResponse) String() string { return proto.CompactTextString(this) }
func (*TouchResponse) ProtoMessage()       {}

func (this *TouchResponse) GetCost() *Cost {
	if this != nil {
		return this.Cost
	}
	return nil
}

type DeleteRequest struct {
	Key              []*Reference `protobuf:"bytes,6,rep,name=key" json:"key,omitempty"`
	Transaction      *Transaction `protobuf:"bytes,5,opt,name=transaction" json:"transaction,omitempty"`
	Trusted          *bool        `protobuf:"varint,4,opt,name=trusted,def=0" json:"trusted,omitempty"`
	Force            *bool        `protobuf:"varint,7,opt,name=force,def=0" json:"force,omitempty"`
	MarkChanges      *bool        `protobuf:"varint,8,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	Snapshot         []*Snapshot  `protobuf:"bytes,9,rep,name=snapshot" json:"snapshot,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *DeleteRequest) Reset()         { *this = DeleteRequest{} }
func (this *DeleteRequest) String() string { return proto.CompactTextString(this) }
func (*DeleteRequest) ProtoMessage()       {}

const Default_DeleteRequest_Trusted bool = false
const Default_DeleteRequest_Force bool = false
const Default_DeleteRequest_MarkChanges bool = false

func (this *DeleteRequest) GetKey() []*Reference {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *DeleteRequest) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *DeleteRequest) GetTrusted() bool {
	if this != nil && this.Trusted != nil {
		return *this.Trusted
	}
	return Default_DeleteRequest_Trusted
}

func (this *DeleteRequest) GetForce() bool {
	if this != nil && this.Force != nil {
		return *this.Force
	}
	return Default_DeleteRequest_Force
}

func (this *DeleteRequest) GetMarkChanges() bool {
	if this != nil && this.MarkChanges != nil {
		return *this.MarkChanges
	}
	return Default_DeleteRequest_MarkChanges
}

func (this *DeleteRequest) GetSnapshot() []*Snapshot {
	if this != nil {
		return this.Snapshot
	}
	return nil
}

type DeleteResponse struct {
	Cost             *Cost   `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	Version          []int64 `protobuf:"varint,3,rep,name=version" json:"version,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DeleteResponse) Reset()         { *this = DeleteResponse{} }
func (this *DeleteResponse) String() string { return proto.CompactTextString(this) }
func (*DeleteResponse) ProtoMessage()       {}

func (this *DeleteResponse) GetCost() *Cost {
	if this != nil {
		return this.Cost
	}
	return nil
}

func (this *DeleteResponse) GetVersion() []int64 {
	if this != nil {
		return this.Version
	}
	return nil
}

type NextRequest struct {
	Cursor           *Cursor `protobuf:"bytes,1,req,name=cursor" json:"cursor,omitempty"`
	Count            *int32  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Offset           *int32  `protobuf:"varint,4,opt,name=offset,def=0" json:"offset,omitempty"`
	Compile          *bool   `protobuf:"varint,3,opt,name=compile,def=0" json:"compile,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *NextRequest) Reset()         { *this = NextRequest{} }
func (this *NextRequest) String() string { return proto.CompactTextString(this) }
func (*NextRequest) ProtoMessage()       {}

const Default_NextRequest_Offset int32 = 0
const Default_NextRequest_Compile bool = false

func (this *NextRequest) GetCursor() *Cursor {
	if this != nil {
		return this.Cursor
	}
	return nil
}

func (this *NextRequest) GetCount() int32 {
	if this != nil && this.Count != nil {
		return *this.Count
	}
	return 0
}

func (this *NextRequest) GetOffset() int32 {
	if this != nil && this.Offset != nil {
		return *this.Offset
	}
	return Default_NextRequest_Offset
}

func (this *NextRequest) GetCompile() bool {
	if this != nil && this.Compile != nil {
		return *this.Compile
	}
	return Default_NextRequest_Compile
}

type QueryResult struct {
	Cursor           *Cursor           `protobuf:"bytes,1,opt,name=cursor" json:"cursor,omitempty"`
	Result           []*EntityProto    `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`
	SkippedResults   *int32            `protobuf:"varint,7,opt,name=skipped_results" json:"skipped_results,omitempty"`
	MoreResults      *bool             `protobuf:"varint,3,req,name=more_results" json:"more_results,omitempty"`
	KeysOnly         *bool             `protobuf:"varint,4,opt,name=keys_only" json:"keys_only,omitempty"`
	IndexOnly        *bool             `protobuf:"varint,9,opt,name=index_only" json:"index_only,omitempty"`
	SmallOps         *bool             `protobuf:"varint,10,opt,name=small_ops" json:"small_ops,omitempty"`
	CompiledQuery    *CompiledQuery    `protobuf:"bytes,5,opt,name=compiled_query" json:"compiled_query,omitempty"`
	CompiledCursor   *CompiledCursor   `protobuf:"bytes,6,opt,name=compiled_cursor" json:"compiled_cursor,omitempty"`
	Index            []*CompositeIndex `protobuf:"bytes,8,rep,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *QueryResult) Reset()         { *this = QueryResult{} }
func (this *QueryResult) String() string { return proto.CompactTextString(this) }
func (*QueryResult) ProtoMessage()       {}

func (this *QueryResult) GetCursor() *Cursor {
	if this != nil {
		return this.Cursor
	}
	return nil
}

func (this *QueryResult) GetResult() []*EntityProto {
	if this != nil {
		return this.Result
	}
	return nil
}

func (this *QueryResult) GetSkippedResults() int32 {
	if this != nil && this.SkippedResults != nil {
		return *this.SkippedResults
	}
	return 0
}

func (this *QueryResult) GetMoreResults() bool {
	if this != nil && this.MoreResults != nil {
		return *this.MoreResults
	}
	return false
}

func (this *QueryResult) GetKeysOnly() bool {
	if this != nil && this.KeysOnly != nil {
		return *this.KeysOnly
	}
	return false
}

func (this *QueryResult) GetIndexOnly() bool {
	if this != nil && this.IndexOnly != nil {
		return *this.IndexOnly
	}
	return false
}

func (this *QueryResult) GetSmallOps() bool {
	if this != nil && this.SmallOps != nil {
		return *this.SmallOps
	}
	return false
}

func (this *QueryResult) GetCompiledQuery() *CompiledQuery {
	if this != nil {
		return this.CompiledQuery
	}
	return nil
}

func (this *QueryResult) GetCompiledCursor() *CompiledCursor {
	if this != nil {
		return this.CompiledCursor
	}
	return nil
}

func (this *QueryResult) GetIndex() []*CompositeIndex {
	if this != nil {
		return this.Index
	}
	return nil
}

type AllocateIdsRequest struct {
	ModelKey         *Reference `protobuf:"bytes,1,req,name=model_key" json:"model_key,omitempty"`
	Size             *int64     `protobuf:"varint,2,opt,name=size" json:"size,omitempty"`
	Max              *int64     `protobuf:"varint,3,opt,name=max" json:"max,omitempty"`
	XXX_unrecognized []byte     `json:"-"`
}

func (this *AllocateIdsRequest) Reset()         { *this = AllocateIdsRequest{} }
func (this *AllocateIdsRequest) String() string { return proto.CompactTextString(this) }
func (*AllocateIdsRequest) ProtoMessage()       {}

func (this *AllocateIdsRequest) GetModelKey() *Reference {
	if this != nil {
		return this.ModelKey
	}
	return nil
}

func (this *AllocateIdsRequest) GetSize() int64 {
	if this != nil && this.Size != nil {
		return *this.Size
	}
	return 0
}

func (this *AllocateIdsRequest) GetMax() int64 {
	if this != nil && this.Max != nil {
		return *this.Max
	}
	return 0
}

type AllocateIdsResponse struct {
	Start            *int64 `protobuf:"varint,1,req,name=start" json:"start,omitempty"`
	End              *int64 `protobuf:"varint,2,req,name=end" json:"end,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *AllocateIdsResponse) Reset()         { *this = AllocateIdsResponse{} }
func (this *AllocateIdsResponse) String() string { return proto.CompactTextString(this) }
func (*AllocateIdsResponse) ProtoMessage()       {}

func (this *AllocateIdsResponse) GetStart() int64 {
	if this != nil && this.Start != nil {
		return *this.Start
	}
	return 0
}

func (this *AllocateIdsResponse) GetEnd() int64 {
	if this != nil && this.End != nil {
		return *this.End
	}
	return 0
}

type CompositeIndices struct {
	Index            []*CompositeIndex `protobuf:"bytes,1,rep,name=index" json:"index,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (this *CompositeIndices) Reset()         { *this = CompositeIndices{} }
func (this *CompositeIndices) String() string { return proto.CompactTextString(this) }
func (*CompositeIndices) ProtoMessage()       {}

func (this *CompositeIndices) GetIndex() []*CompositeIndex {
	if this != nil {
		return this.Index
	}
	return nil
}

type AddActionsRequest struct {
	Transaction      *Transaction `protobuf:"bytes,1,req,name=transaction" json:"transaction,omitempty"`
	Action           []*Action    `protobuf:"bytes,2,rep,name=action" json:"action,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (this *AddActionsRequest) Reset()         { *this = AddActionsRequest{} }
func (this *AddActionsRequest) String() string { return proto.CompactTextString(this) }
func (*AddActionsRequest) ProtoMessage()       {}

func (this *AddActionsRequest) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *AddActionsRequest) GetAction() []*Action {
	if this != nil {
		return this.Action
	}
	return nil
}

type AddActionsResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *AddActionsResponse) Reset()         { *this = AddActionsResponse{} }
func (this *AddActionsResponse) String() string { return proto.CompactTextString(this) }
func (*AddActionsResponse) ProtoMessage()       {}

type BeginTransactionRequest struct {
	App              *string `protobuf:"bytes,1,req,name=app" json:"app,omitempty"`
	AllowMultipleEg  *bool   `protobuf:"varint,2,opt,name=allow_multiple_eg,def=0" json:"allow_multiple_eg,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *BeginTransactionRequest) Reset()         { *this = BeginTransactionRequest{} }
func (this *BeginTransactionRequest) String() string { return proto.CompactTextString(this) }
func (*BeginTransactionRequest) ProtoMessage()       {}

const Default_BeginTransactionRequest_AllowMultipleEg bool = false

func (this *BeginTransactionRequest) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *BeginTransactionRequest) GetAllowMultipleEg() bool {
	if this != nil && this.AllowMultipleEg != nil {
		return *this.AllowMultipleEg
	}
	return Default_BeginTransactionRequest_AllowMultipleEg
}

type CommitResponse struct {
	Cost             *Cost                     `protobuf:"bytes,1,opt,name=cost" json:"cost,omitempty"`
	Version          []*CommitResponse_Version `protobuf:"group,3,rep" json:"version,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (this *CommitResponse) Reset()         { *this = CommitResponse{} }
func (this *CommitResponse) String() string { return proto.CompactTextString(this) }
func (*CommitResponse) ProtoMessage()       {}

func (this *CommitResponse) GetCost() *Cost {
	if this != nil {
		return this.Cost
	}
	return nil
}

func (this *CommitResponse) GetVersion() []*CommitResponse_Version {
	if this != nil {
		return this.Version
	}
	return nil
}

type CommitResponse_Version struct {
	RootEntityKey *Reference `protobuf:"bytes,4,req,name=root_entity_key" json:"root_entity_key,omitempty"`
	Version       *int64     `protobuf:"varint,5,req,name=version" json:"version,omitempty"`
}

func (this *CommitResponse_Version) Reset() { *this = CommitResponse_Version{} }

func (this *CommitResponse_Version) GetRootEntityKey() *Reference {
	if this != nil {
		return this.RootEntityKey
	}
	return nil
}

func (this *CommitResponse_Version) GetVersion() int64 {
	if this != nil && this.Version != nil {
		return *this.Version
	}
	return 0
}

func init() {
	proto.RegisterEnum("datastore.Property_Meaning", Property_Meaning_name, Property_Meaning_value)
	proto.RegisterEnum("datastore.Property_FtsTokenizationOption", Property_FtsTokenizationOption_name, Property_FtsTokenizationOption_value)
	proto.RegisterEnum("datastore.EntityProto_Kind", EntityProto_Kind_name, EntityProto_Kind_value)
	proto.RegisterEnum("datastore.Index_Property_Direction", Index_Property_Direction_name, Index_Property_Direction_value)
	proto.RegisterEnum("datastore.CompositeIndex_State", CompositeIndex_State_name, CompositeIndex_State_value)
	proto.RegisterEnum("datastore.Snapshot_Status", Snapshot_Status_name, Snapshot_Status_value)
	proto.RegisterEnum("datastore.Query_Hint", Query_Hint_name, Query_Hint_value)
	proto.RegisterEnum("datastore.Query_Filter_Operator", Query_Filter_Operator_name, Query_Filter_Operator_value)
	proto.RegisterEnum("datastore.Query_Order_Direction", Query_Order_Direction_name, Query_Order_Direction_value)
	proto.RegisterEnum("datastore.Error_ErrorCode", Error_ErrorCode_name, Error_ErrorCode_value)
}
