// Code generated by protoc-gen-go.
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type SystemServiceError_ErrorCode int32

const (
	SystemServiceError_OK               SystemServiceError_ErrorCode = 0
	SystemServiceError_INTERNAL_ERROR   SystemServiceError_ErrorCode = 1
	SystemServiceError_BACKEND_REQUIRED SystemServiceError_ErrorCode = 2
	SystemServiceError_LIMIT_REACHED    SystemServiceError_ErrorCode = 3
)

var SystemServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
	2: "BACKEND_REQUIRED",
	3: "LIMIT_REACHED",
}
var SystemServiceError_ErrorCode_value = map[string]int32{
	"OK":               0,
	"INTERNAL_ERROR":   1,
	"BACKEND_REQUIRED": 2,
	"LIMIT_REACHED":    3,
}

func (x SystemServiceError_ErrorCode) Enum() *SystemServiceError_ErrorCode {
	p := new(SystemServiceError_ErrorCode)
	*p = x
	return p
}
func (x SystemServiceError_ErrorCode) String() string {
	return proto.EnumName(SystemServiceError_ErrorCode_name, int32(x))
}
func (x SystemServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *SystemServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(SystemServiceError_ErrorCode_value, data, "SystemServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = SystemServiceError_ErrorCode(value)
	return nil
}

type SystemServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *SystemServiceError) Reset()         { *this = SystemServiceError{} }
func (this *SystemServiceError) String() string { return proto.CompactTextString(this) }
func (*SystemServiceError) ProtoMessage()       {}

type SystemStat struct {
	Current          *float64 `protobuf:"fixed64,1,opt,name=current" json:"current,omitempty"`
	Average1M        *float64 `protobuf:"fixed64,3,opt,name=average1m" json:"average1m,omitempty"`
	Average10M       *float64 `protobuf:"fixed64,4,opt,name=average10m" json:"average10m,omitempty"`
	Total            *float64 `protobuf:"fixed64,2,opt,name=total" json:"total,omitempty"`
	Rate1M           *float64 `protobuf:"fixed64,5,opt,name=rate1m" json:"rate1m,omitempty"`
	Rate10M          *float64 `protobuf:"fixed64,6,opt,name=rate10m" json:"rate10m,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *SystemStat) Reset()         { *this = SystemStat{} }
func (this *SystemStat) String() string { return proto.CompactTextString(this) }
func (*SystemStat) ProtoMessage()       {}

func (this *SystemStat) GetCurrent() float64 {
	if this != nil && this.Current != nil {
		return *this.Current
	}
	return 0
}

func (this *SystemStat) GetAverage1M() float64 {
	if this != nil && this.Average1M != nil {
		return *this.Average1M
	}
	return 0
}

func (this *SystemStat) GetAverage10M() float64 {
	if this != nil && this.Average10M != nil {
		return *this.Average10M
	}
	return 0
}

func (this *SystemStat) GetTotal() float64 {
	if this != nil && this.Total != nil {
		return *this.Total
	}
	return 0
}

func (this *SystemStat) GetRate1M() float64 {
	if this != nil && this.Rate1M != nil {
		return *this.Rate1M
	}
	return 0
}

func (this *SystemStat) GetRate10M() float64 {
	if this != nil && this.Rate10M != nil {
		return *this.Rate10M
	}
	return 0
}

type GetSystemStatsRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *GetSystemStatsRequest) Reset()         { *this = GetSystemStatsRequest{} }
func (this *GetSystemStatsRequest) String() string { return proto.CompactTextString(this) }
func (*GetSystemStatsRequest) ProtoMessage()       {}

type GetSystemStatsResponse struct {
	Cpu              *SystemStat `protobuf:"bytes,1,opt,name=cpu" json:"cpu,omitempty"`
	Memory           *SystemStat `protobuf:"bytes,2,opt,name=memory" json:"memory,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (this *GetSystemStatsResponse) Reset()         { *this = GetSystemStatsResponse{} }
func (this *GetSystemStatsResponse) String() string { return proto.CompactTextString(this) }
func (*GetSystemStatsResponse) ProtoMessage()       {}

func (this *GetSystemStatsResponse) GetCpu() *SystemStat {
	if this != nil {
		return this.Cpu
	}
	return nil
}

func (this *GetSystemStatsResponse) GetMemory() *SystemStat {
	if this != nil {
		return this.Memory
	}
	return nil
}

type StartBackgroundRequestRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *StartBackgroundRequestRequest) Reset()         { *this = StartBackgroundRequestRequest{} }
func (this *StartBackgroundRequestRequest) String() string { return proto.CompactTextString(this) }
func (*StartBackgroundRequestRequest) ProtoMessage()       {}

type StartBackgroundRequestResponse struct {
	RequestId        *string `protobuf:"bytes,1,opt,name=request_id" json:"request_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StartBackgroundRequestResponse) Reset()         { *this = StartBackgroundRequestResponse{} }
func (this *StartBackgroundRequestResponse) String() string { return proto.CompactTextString(this) }
func (*StartBackgroundRequestResponse) ProtoMessage()       {}

func (this *StartBackgroundRequestResponse) GetRequestId() string {
	if this != nil && this.RequestId != nil {
		return *this.RequestId
	}
	return ""
}

func init() {
	proto.RegisterEnum("appengine.SystemServiceError_ErrorCode", SystemServiceError_ErrorCode_name, SystemServiceError_ErrorCode_value)
}
