// Code generated by protoc-gen-go.
// DO NOT EDIT!

package files

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type FileServiceErrors_ErrorCode int32

const (
	FileServiceErrors_OK                                 FileServiceErrors_ErrorCode = 0
	FileServiceErrors_API_TEMPORARILY_UNAVAILABLE        FileServiceErrors_ErrorCode = 1
	FileServiceErrors_REQUEST_TOO_LARGE                  FileServiceErrors_ErrorCode = 3
	FileServiceErrors_RESPONSE_TOO_LARGE                 FileServiceErrors_ErrorCode = 4
	FileServiceErrors_INVALID_FILE_NAME                  FileServiceErrors_ErrorCode = 5
	FileServiceErrors_OPERATION_NOT_SUPPORTED            FileServiceErrors_ErrorCode = 6
	FileServiceErrors_IO_ERROR                           FileServiceErrors_ErrorCode = 7
	FileServiceErrors_PERMISSION_DENIED                  FileServiceErrors_ErrorCode = 8
	FileServiceErrors_WRONG_CONTENT_TYPE                 FileServiceErrors_ErrorCode = 9
	FileServiceErrors_FILE_NOT_OPENED                    FileServiceErrors_ErrorCode = 10
	FileServiceErrors_WRONG_OPEN_MODE                    FileServiceErrors_ErrorCode = 11
	FileServiceErrors_EXCLUSIVE_LOCK_REQUIRED            FileServiceErrors_ErrorCode = 12
	FileServiceErrors_FILE_TEMPORARILY_UNAVAILABLE       FileServiceErrors_ErrorCode = 13
	FileServiceErrors_EXISTENCE_ERROR                    FileServiceErrors_ErrorCode = 100
	FileServiceErrors_FINALIZATION_ERROR                 FileServiceErrors_ErrorCode = 101
	FileServiceErrors_UNSUPPORTED_CONTENT_TYPE           FileServiceErrors_ErrorCode = 102
	FileServiceErrors_READ_ONLY                          FileServiceErrors_ErrorCode = 103
	FileServiceErrors_EXCLUSIVE_LOCK_FAILED              FileServiceErrors_ErrorCode = 104
	FileServiceErrors_EXISTENCE_ERROR_METADATA_NOT_FOUND FileServiceErrors_ErrorCode = 105
	FileServiceErrors_EXISTENCE_ERROR_METADATA_FOUND     FileServiceErrors_ErrorCode = 106
	FileServiceErrors_EXISTENCE_ERROR_SHARDING_MISMATCH  FileServiceErrors_ErrorCode = 107
	FileServiceErrors_FINALIZATION_IN_PROGRESS           FileServiceErrors_ErrorCode = 108
	FileServiceErrors_EXISTENCE_ERROR_OBJECT_NOT_FOUND   FileServiceErrors_ErrorCode = 109
	FileServiceErrors_EXISTENCE_ERROR_BUCKET_NOT_FOUND   FileServiceErrors_ErrorCode = 110
	FileServiceErrors_SEQUENCE_KEY_OUT_OF_ORDER          FileServiceErrors_ErrorCode = 300
	FileServiceErrors_OUT_OF_BOUNDS                      FileServiceErrors_ErrorCode = 500
	FileServiceErrors_GLOBS_NOT_SUPPORTED                FileServiceErrors_ErrorCode = 600
	FileServiceErrors_FILE_NAME_NOT_SPECIFIED            FileServiceErrors_ErrorCode = 701
	FileServiceErrors_FILE_NAME_SPECIFIED                FileServiceErrors_ErrorCode = 702
	FileServiceErrors_FILE_ALREADY_EXISTS                FileServiceErrors_ErrorCode = 703
	FileServiceErrors_UNSUPPORTED_FILE_SYSTEM            FileServiceErrors_ErrorCode = 704
	FileServiceErrors_INVALID_PARAMETER                  FileServiceErrors_ErrorCode = 705
	FileServiceErrors_SHUFFLER_INTERNAL_ERROR            FileServiceErrors_ErrorCode = 800
	FileServiceErrors_SHUFFLE_REQUEST_TOO_LARGE          FileServiceErrors_ErrorCode = 801
	FileServiceErrors_DUPLICATE_SHUFFLE_NAME             FileServiceErrors_ErrorCode = 802
	FileServiceErrors_SHUFFLE_NOT_AVAILABLE              FileServiceErrors_ErrorCode = 803
	FileServiceErrors_SHUFFLER_TEMPORARILY_UNAVAILABLE   FileServiceErrors_ErrorCode = 900
	FileServiceErrors_MAX_ERROR_CODE                     FileServiceErrors_ErrorCode = 9999
)

var FileServiceErrors_ErrorCode_name = map[int32]string{
	0:    "OK",
	1:    "API_TEMPORARILY_UNAVAILABLE",
	3:    "REQUEST_TOO_LARGE",
	4:    "RESPONSE_TOO_LARGE",
	5:    "INVALID_FILE_NAME",
	6:    "OPERATION_NOT_SUPPORTED",
	7:    "IO_ERROR",
	8:    "PERMISSION_DENIED",
	9:    "WRONG_CONTENT_TYPE",
	10:   "FILE_NOT_OPENED",
	11:   "WRONG_OPEN_MODE",
	12:   "EXCLUSIVE_LOCK_REQUIRED",
	13:   "FILE_TEMPORARILY_UNAVAILABLE",
	100:  "EXISTENCE_ERROR",
	101:  "FINALIZATION_ERROR",
	102:  "UNSUPPORTED_CONTENT_TYPE",
	103:  "READ_ONLY",
	104:  "EXCLUSIVE_LOCK_FAILED",
	105:  "EXISTENCE_ERROR_METADATA_NOT_FOUND",
	106:  "EXISTENCE_ERROR_METADATA_FOUND",
	107:  "EXISTENCE_ERROR_SHARDING_MISMATCH",
	108:  "FINALIZATION_IN_PROGRESS",
	109:  "EXISTENCE_ERROR_OBJECT_NOT_FOUND",
	110:  "EXISTENCE_ERROR_BUCKET_NOT_FOUND",
	300:  "SEQUENCE_KEY_OUT_OF_ORDER",
	500:  "OUT_OF_BOUNDS",
	600:  "GLOBS_NOT_SUPPORTED",
	701:  "FILE_NAME_NOT_SPECIFIED",
	702:  "FILE_NAME_SPECIFIED",
	703:  "FILE_ALREADY_EXISTS",
	704:  "UNSUPPORTED_FILE_SYSTEM",
	705:  "INVALID_PARAMETER",
	800:  "SHUFFLER_INTERNAL_ERROR",
	801:  "SHUFFLE_REQUEST_TOO_LARGE",
	802:  "DUPLICATE_SHUFFLE_NAME",
	803:  "SHUFFLE_NOT_AVAILABLE",
	900:  "SHUFFLER_TEMPORARILY_UNAVAILABLE",
	9999: "MAX_ERROR_CODE",
}
var FileServiceErrors_ErrorCode_value = map[string]int32{
	"OK": 0,
	"API_TEMPORARILY_UNAVAILABLE":        1,
	"REQUEST_TOO_LARGE":                  3,
	"RESPONSE_TOO_LARGE":                 4,
	"INVALID_FILE_NAME":                  5,
	"OPERATION_NOT_SUPPORTED":            6,
	"IO_ERROR":                           7,
	"PERMISSION_DENIED":                  8,
	"WRONG_CONTENT_TYPE":                 9,
	"FILE_NOT_OPENED":                    10,
	"WRONG_OPEN_MODE":                    11,
	"EXCLUSIVE_LOCK_REQUIRED":            12,
	"FILE_TEMPORARILY_UNAVAILABLE":       13,
	"EXISTENCE_ERROR":                    100,
	"FINALIZATION_ERROR":                 101,
	"UNSUPPORTED_CONTENT_TYPE":           102,
	"READ_ONLY":                          103,
	"EXCLUSIVE_LOCK_FAILED":              104,
	"EXISTENCE_ERROR_METADATA_NOT_FOUND": 105,
	"EXISTENCE_ERROR_METADATA_FOUND":     106,
	"EXISTENCE_ERROR_SHARDING_MISMATCH":  107,
	"FINALIZATION_IN_PROGRESS":           108,
	"EXISTENCE_ERROR_OBJECT_NOT_FOUND":   109,
	"EXISTENCE_ERROR_BUCKET_NOT_FOUND":   110,
	"SEQUENCE_KEY_OUT_OF_ORDER":          300,
	"OUT_OF_BOUNDS":                      500,
	"GLOBS_NOT_SUPPORTED":                600,
	"FILE_NAME_NOT_SPECIFIED":            701,
	"FILE_NAME_SPECIFIED":                702,
	"FILE_ALREADY_EXISTS":                703,
	"UNSUPPORTED_FILE_SYSTEM":            704,
	"INVALID_PARAMETER":                  705,
	"SHUFFLER_INTERNAL_ERROR":            800,
	"SHUFFLE_REQUEST_TOO_LARGE":          801,
	"DUPLICATE_SHUFFLE_NAME":             802,
	"SHUFFLE_NOT_AVAILABLE":              803,
	"SHUFFLER_TEMPORARILY_UNAVAILABLE":   900,
	"MAX_ERROR_CODE":                     9999,
}

func (x FileServiceErrors_ErrorCode) Enum() *FileServiceErrors_ErrorCode {
	p := new(FileServiceErrors_ErrorCode)
	*p = x
	return p
}
func (x FileServiceErrors_ErrorCode) String() string {
	return proto.EnumName(FileServiceErrors_ErrorCode_name, int32(x))
}
func (x FileServiceErrors_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *FileServiceErrors_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileServiceErrors_ErrorCode_value, data, "FileServiceErrors_ErrorCode")
	if err != nil {
		return err
	}
	*x = FileServiceErrors_ErrorCode(value)
	return nil
}

type FileContentType_ContentType int32

const (
	FileContentType_RAW          FileContentType_ContentType = 0
	FileContentType_DEPRECATED_1 FileContentType_ContentType = 2
	FileContentType_INVALID_TYPE FileContentType_ContentType = 127
)

var FileContentType_ContentType_name = map[int32]string{
	0:   "RAW",
	2:   "DEPRECATED_1",
	127: "INVALID_TYPE",
}
var FileContentType_ContentType_value = map[string]int32{
	"RAW":          0,
	"DEPRECATED_1": 2,
	"INVALID_TYPE": 127,
}

func (x FileContentType_ContentType) Enum() *FileContentType_ContentType {
	p := new(FileContentType_ContentType)
	*p = x
	return p
}
func (x FileContentType_ContentType) String() string {
	return proto.EnumName(FileContentType_ContentType_name, int32(x))
}
func (x FileContentType_ContentType) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *FileContentType_ContentType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FileContentType_ContentType_value, data, "FileContentType_ContentType")
	if err != nil {
		return err
	}
	*x = FileContentType_ContentType(value)
	return nil
}

type OpenRequest_OpenMode int32

const (
	OpenRequest_APPEND OpenRequest_OpenMode = 1
	OpenRequest_READ   OpenRequest_OpenMode = 2
)

var OpenRequest_OpenMode_name = map[int32]string{
	1: "APPEND",
	2: "READ",
}
var OpenRequest_OpenMode_value = map[string]int32{
	"APPEND": 1,
	"READ":   2,
}

func (x OpenRequest_OpenMode) Enum() *OpenRequest_OpenMode {
	p := new(OpenRequest_OpenMode)
	*p = x
	return p
}
func (x OpenRequest_OpenMode) String() string {
	return proto.EnumName(OpenRequest_OpenMode_name, int32(x))
}
func (x OpenRequest_OpenMode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *OpenRequest_OpenMode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(OpenRequest_OpenMode_value, data, "OpenRequest_OpenMode")
	if err != nil {
		return err
	}
	*x = OpenRequest_OpenMode(value)
	return nil
}

type ShuffleEnums_InputFormat int32

const (
	ShuffleEnums_RECORDS_KEY_VALUE_PROTO_INPUT ShuffleEnums_InputFormat = 1
)

var ShuffleEnums_InputFormat_name = map[int32]string{
	1: "RECORDS_KEY_VALUE_PROTO_INPUT",
}
var ShuffleEnums_InputFormat_value = map[string]int32{
	"RECORDS_KEY_VALUE_PROTO_INPUT": 1,
}

func (x ShuffleEnums_InputFormat) Enum() *ShuffleEnums_InputFormat {
	p := new(ShuffleEnums_InputFormat)
	*p = x
	return p
}
func (x ShuffleEnums_InputFormat) String() string {
	return proto.EnumName(ShuffleEnums_InputFormat_name, int32(x))
}
func (x ShuffleEnums_InputFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ShuffleEnums_InputFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_InputFormat_value, data, "ShuffleEnums_InputFormat")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_InputFormat(value)
	return nil
}

type ShuffleEnums_OutputFormat int32

const (
	ShuffleEnums_RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT ShuffleEnums_OutputFormat = 1
)

var ShuffleEnums_OutputFormat_name = map[int32]string{
	1: "RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT",
}
var ShuffleEnums_OutputFormat_value = map[string]int32{
	"RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT": 1,
}

func (x ShuffleEnums_OutputFormat) Enum() *ShuffleEnums_OutputFormat {
	p := new(ShuffleEnums_OutputFormat)
	*p = x
	return p
}
func (x ShuffleEnums_OutputFormat) String() string {
	return proto.EnumName(ShuffleEnums_OutputFormat_name, int32(x))
}
func (x ShuffleEnums_OutputFormat) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ShuffleEnums_OutputFormat) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_OutputFormat_value, data, "ShuffleEnums_OutputFormat")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_OutputFormat(value)
	return nil
}

type ShuffleEnums_Status int32

const (
	ShuffleEnums_UNKNOWN                      ShuffleEnums_Status = 1
	ShuffleEnums_RUNNING                      ShuffleEnums_Status = 2
	ShuffleEnums_SUCCESS                      ShuffleEnums_Status = 3
	ShuffleEnums_FAILURE                      ShuffleEnums_Status = 4
	ShuffleEnums_INVALID_INPUT                ShuffleEnums_Status = 5
	ShuffleEnums_OUTPUT_ALREADY_EXISTS        ShuffleEnums_Status = 6
	ShuffleEnums_INCORRECT_SHUFFLE_SIZE_BYTES ShuffleEnums_Status = 7
)

var ShuffleEnums_Status_name = map[int32]string{
	1: "UNKNOWN",
	2: "RUNNING",
	3: "SUCCESS",
	4: "FAILURE",
	5: "INVALID_INPUT",
	6: "OUTPUT_ALREADY_EXISTS",
	7: "INCORRECT_SHUFFLE_SIZE_BYTES",
}
var ShuffleEnums_Status_value = map[string]int32{
	"UNKNOWN":                      1,
	"RUNNING":                      2,
	"SUCCESS":                      3,
	"FAILURE":                      4,
	"INVALID_INPUT":                5,
	"OUTPUT_ALREADY_EXISTS":        6,
	"INCORRECT_SHUFFLE_SIZE_BYTES": 7,
}

func (x ShuffleEnums_Status) Enum() *ShuffleEnums_Status {
	p := new(ShuffleEnums_Status)
	*p = x
	return p
}
func (x ShuffleEnums_Status) String() string {
	return proto.EnumName(ShuffleEnums_Status_name, int32(x))
}
func (x ShuffleEnums_Status) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ShuffleEnums_Status) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ShuffleEnums_Status_value, data, "ShuffleEnums_Status")
	if err != nil {
		return err
	}
	*x = ShuffleEnums_Status(value)
	return nil
}

type StringProto struct {
	Value            *string `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StringProto) Reset()         { *this = StringProto{} }
func (this *StringProto) String() string { return proto.CompactTextString(this) }
func (*StringProto) ProtoMessage()       {}

func (this *StringProto) GetValue() string {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return ""
}

type Integer32Proto struct {
	Value            *int32 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Integer32Proto) Reset()         { *this = Integer32Proto{} }
func (this *Integer32Proto) String() string { return proto.CompactTextString(this) }
func (*Integer32Proto) ProtoMessage()       {}

func (this *Integer32Proto) GetValue() int32 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type Integer64Proto struct {
	Value            *int64 `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *Integer64Proto) Reset()         { *this = Integer64Proto{} }
func (this *Integer64Proto) String() string { return proto.CompactTextString(this) }
func (*Integer64Proto) ProtoMessage()       {}

func (this *Integer64Proto) GetValue() int64 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type BoolProto struct {
	Value            *bool  `protobuf:"varint,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *BoolProto) Reset()         { *this = BoolProto{} }
func (this *BoolProto) String() string { return proto.CompactTextString(this) }
func (*BoolProto) ProtoMessage()       {}

func (this *BoolProto) GetValue() bool {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return false
}

type DoubleProto struct {
	Value            *float64 `protobuf:"fixed64,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *DoubleProto) Reset()         { *this = DoubleProto{} }
func (this *DoubleProto) String() string { return proto.CompactTextString(this) }
func (*DoubleProto) ProtoMessage()       {}

func (this *DoubleProto) GetValue() float64 {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return 0
}

type BytesProto struct {
	Value            []byte `protobuf:"bytes,1,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *BytesProto) Reset()         { *this = BytesProto{} }
func (this *BytesProto) String() string { return proto.CompactTextString(this) }
func (*BytesProto) ProtoMessage()       {}

func (this *BytesProto) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type VoidProto struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *VoidProto) Reset()         { *this = VoidProto{} }
func (this *VoidProto) String() string { return proto.CompactTextString(this) }
func (*VoidProto) ProtoMessage()       {}

type FileServiceErrors struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *FileServiceErrors) Reset()         { *this = FileServiceErrors{} }
func (this *FileServiceErrors) String() string { return proto.CompactTextString(this) }
func (*FileServiceErrors) ProtoMessage()       {}

type KeyValue struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *KeyValue) Reset()         { *this = KeyValue{} }
func (this *KeyValue) String() string { return proto.CompactTextString(this) }
func (*KeyValue) ProtoMessage()       {}

func (this *KeyValue) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *KeyValue) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type KeyValues struct {
	Key              []byte   `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            [][]byte `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	Partial          *bool    `protobuf:"varint,3,opt,name=partial,def=0" json:"partial,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *KeyValues) Reset()         { *this = KeyValues{} }
func (this *KeyValues) String() string { return proto.CompactTextString(this) }
func (*KeyValues) ProtoMessage()       {}

const Default_KeyValues_Partial bool = false

func (this *KeyValues) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *KeyValues) GetValue() [][]byte {
	if this != nil {
		return this.Value
	}
	return nil
}

func (this *KeyValues) GetPartial() bool {
	if this != nil && this.Partial != nil {
		return *this.Partial
	}
	return Default_KeyValues_Partial
}

type FileContentType struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *FileContentType) Reset()         { *this = FileContentType{} }
func (this *FileContentType) String() string { return proto.CompactTextString(this) }
func (*FileContentType) ProtoMessage()       {}

type CreateRequest struct {
	Filesystem            *string                      `protobuf:"bytes,1,req,name=filesystem" json:"filesystem,omitempty"`
	ContentType           *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	Filename              *string                      `protobuf:"bytes,3,opt,name=filename" json:"filename,omitempty"`
	Parameters            []*CreateRequest_Parameter   `protobuf:"bytes,4,rep,name=parameters" json:"parameters,omitempty"`
	ExpirationTimeSeconds *int64                       `protobuf:"varint,5,opt,name=expiration_time_seconds" json:"expiration_time_seconds,omitempty"`
	XXX_unrecognized      []byte                       `json:"-"`
}

func (this *CreateRequest) Reset()         { *this = CreateRequest{} }
func (this *CreateRequest) String() string { return proto.CompactTextString(this) }
func (*CreateRequest) ProtoMessage()       {}

func (this *CreateRequest) GetFilesystem() string {
	if this != nil && this.Filesystem != nil {
		return *this.Filesystem
	}
	return ""
}

func (this *CreateRequest) GetContentType() FileContentType_ContentType {
	if this != nil && this.ContentType != nil {
		return *this.ContentType
	}
	return 0
}

func (this *CreateRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *CreateRequest) GetParameters() []*CreateRequest_Parameter {
	if this != nil {
		return this.Parameters
	}
	return nil
}

func (this *CreateRequest) GetExpirationTimeSeconds() int64 {
	if this != nil && this.ExpirationTimeSeconds != nil {
		return *this.ExpirationTimeSeconds
	}
	return 0
}

type CreateRequest_Parameter struct {
	Name             *string `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateRequest_Parameter) Reset()         { *this = CreateRequest_Parameter{} }
func (this *CreateRequest_Parameter) String() string { return proto.CompactTextString(this) }
func (*CreateRequest_Parameter) ProtoMessage()       {}

func (this *CreateRequest_Parameter) GetName() string {
	if this != nil && this.Name != nil {
		return *this.Name
	}
	return ""
}

func (this *CreateRequest_Parameter) GetValue() string {
	if this != nil && this.Value != nil {
		return *this.Value
	}
	return ""
}

type CreateResponse struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateResponse) Reset()         { *this = CreateResponse{} }
func (this *CreateResponse) String() string { return proto.CompactTextString(this) }
func (*CreateResponse) ProtoMessage()       {}

func (this *CreateResponse) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

type OpenRequest struct {
	Filename             *string                      `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	ContentType          *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	OpenMode             *OpenRequest_OpenMode        `protobuf:"varint,3,req,name=open_mode,enum=files.OpenRequest_OpenMode" json:"open_mode,omitempty"`
	ExclusiveLock        *bool                        `protobuf:"varint,4,opt,name=exclusive_lock,def=0" json:"exclusive_lock,omitempty"`
	BufferedOutput       *bool                        `protobuf:"varint,5,opt,name=buffered_output,def=0" json:"buffered_output,omitempty"`
	OpenLeaseTimeSeconds *int32                       `protobuf:"varint,6,opt,name=open_lease_time_seconds,def=30" json:"open_lease_time_seconds,omitempty"`
	XXX_unrecognized     []byte                       `json:"-"`
}

func (this *OpenRequest) Reset()         { *this = OpenRequest{} }
func (this *OpenRequest) String() string { return proto.CompactTextString(this) }
func (*OpenRequest) ProtoMessage()       {}

const Default_OpenRequest_ExclusiveLock bool = false
const Default_OpenRequest_BufferedOutput bool = false
const Default_OpenRequest_OpenLeaseTimeSeconds int32 = 30

func (this *OpenRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *OpenRequest) GetContentType() FileContentType_ContentType {
	if this != nil && this.ContentType != nil {
		return *this.ContentType
	}
	return 0
}

func (this *OpenRequest) GetOpenMode() OpenRequest_OpenMode {
	if this != nil && this.OpenMode != nil {
		return *this.OpenMode
	}
	return 0
}

func (this *OpenRequest) GetExclusiveLock() bool {
	if this != nil && this.ExclusiveLock != nil {
		return *this.ExclusiveLock
	}
	return Default_OpenRequest_ExclusiveLock
}

func (this *OpenRequest) GetBufferedOutput() bool {
	if this != nil && this.BufferedOutput != nil {
		return *this.BufferedOutput
	}
	return Default_OpenRequest_BufferedOutput
}

func (this *OpenRequest) GetOpenLeaseTimeSeconds() int32 {
	if this != nil && this.OpenLeaseTimeSeconds != nil {
		return *this.OpenLeaseTimeSeconds
	}
	return Default_OpenRequest_OpenLeaseTimeSeconds
}

type OpenResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *OpenResponse) Reset()         { *this = OpenResponse{} }
func (this *OpenResponse) String() string { return proto.CompactTextString(this) }
func (*OpenResponse) ProtoMessage()       {}

type CloseRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Finalize         *bool   `protobuf:"varint,2,opt,name=finalize,def=0" json:"finalize,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CloseRequest) Reset()         { *this = CloseRequest{} }
func (this *CloseRequest) String() string { return proto.CompactTextString(this) }
func (*CloseRequest) ProtoMessage()       {}

const Default_CloseRequest_Finalize bool = false

func (this *CloseRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *CloseRequest) GetFinalize() bool {
	if this != nil && this.Finalize != nil {
		return *this.Finalize
	}
	return Default_CloseRequest_Finalize
}

type CloseResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *CloseResponse) Reset()         { *this = CloseResponse{} }
func (this *CloseResponse) String() string { return proto.CompactTextString(this) }
func (*CloseResponse) ProtoMessage()       {}

type FileStat struct {
	Filename         *string                      `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	ContentType      *FileContentType_ContentType `protobuf:"varint,2,req,name=content_type,enum=files.FileContentType_ContentType" json:"content_type,omitempty"`
	Finalized        *bool                        `protobuf:"varint,3,req,name=finalized" json:"finalized,omitempty"`
	Length           *int64                       `protobuf:"varint,4,opt,name=length" json:"length,omitempty"`
	Ctime            *int64                       `protobuf:"varint,5,opt,name=ctime" json:"ctime,omitempty"`
	Mtime            *int64                       `protobuf:"varint,6,opt,name=mtime" json:"mtime,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (this *FileStat) Reset()         { *this = FileStat{} }
func (this *FileStat) String() string { return proto.CompactTextString(this) }
func (*FileStat) ProtoMessage()       {}

func (this *FileStat) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *FileStat) GetContentType() FileContentType_ContentType {
	if this != nil && this.ContentType != nil {
		return *this.ContentType
	}
	return 0
}

func (this *FileStat) GetFinalized() bool {
	if this != nil && this.Finalized != nil {
		return *this.Finalized
	}
	return false
}

func (this *FileStat) GetLength() int64 {
	if this != nil && this.Length != nil {
		return *this.Length
	}
	return 0
}

func (this *FileStat) GetCtime() int64 {
	if this != nil && this.Ctime != nil {
		return *this.Ctime
	}
	return 0
}

func (this *FileStat) GetMtime() int64 {
	if this != nil && this.Mtime != nil {
		return *this.Mtime
	}
	return 0
}

type StatRequest struct {
	Filename         *string `protobuf:"bytes,1,opt,name=filename" json:"filename,omitempty"`
	FileGlob         *string `protobuf:"bytes,2,opt,name=file_glob" json:"file_glob,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *StatRequest) Reset()         { *this = StatRequest{} }
func (this *StatRequest) String() string { return proto.CompactTextString(this) }
func (*StatRequest) ProtoMessage()       {}

func (this *StatRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *StatRequest) GetFileGlob() string {
	if this != nil && this.FileGlob != nil {
		return *this.FileGlob
	}
	return ""
}

type StatResponse struct {
	Stat             []*FileStat `protobuf:"bytes,1,rep,name=stat" json:"stat,omitempty"`
	MoreFilesFound   *bool       `protobuf:"varint,2,req,name=more_files_found,def=0" json:"more_files_found,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (this *StatResponse) Reset()         { *this = StatResponse{} }
func (this *StatResponse) String() string { return proto.CompactTextString(this) }
func (*StatResponse) ProtoMessage()       {}

const Default_StatResponse_MoreFilesFound bool = false

func (this *StatResponse) GetStat() []*FileStat {
	if this != nil {
		return this.Stat
	}
	return nil
}

func (this *StatResponse) GetMoreFilesFound() bool {
	if this != nil && this.MoreFilesFound != nil {
		return *this.MoreFilesFound
	}
	return Default_StatResponse_MoreFilesFound
}

type AppendRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Data             []byte  `protobuf:"bytes,2,req,name=data" json:"data,omitempty"`
	SequenceKey      *string `protobuf:"bytes,3,opt,name=sequence_key" json:"sequence_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *AppendRequest) Reset()         { *this = AppendRequest{} }
func (this *AppendRequest) String() string { return proto.CompactTextString(this) }
func (*AppendRequest) ProtoMessage()       {}

func (this *AppendRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *AppendRequest) GetData() []byte {
	if this != nil {
		return this.Data
	}
	return nil
}

func (this *AppendRequest) GetSequenceKey() string {
	if this != nil && this.SequenceKey != nil {
		return *this.SequenceKey
	}
	return ""
}

type AppendResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *AppendResponse) Reset()         { *this = AppendResponse{} }
func (this *AppendResponse) String() string { return proto.CompactTextString(this) }
func (*AppendResponse) ProtoMessage()       {}

type DeleteRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *DeleteRequest) Reset()         { *this = DeleteRequest{} }
func (this *DeleteRequest) String() string { return proto.CompactTextString(this) }
func (*DeleteRequest) ProtoMessage()       {}

func (this *DeleteRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

type DeleteResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *DeleteResponse) Reset()         { *this = DeleteResponse{} }
func (this *DeleteResponse) String() string { return proto.CompactTextString(this) }
func (*DeleteResponse) ProtoMessage()       {}

type ReadRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	Pos              *int64  `protobuf:"varint,2,req,name=pos" json:"pos,omitempty"`
	MaxBytes         *int64  `protobuf:"varint,3,req,name=max_bytes" json:"max_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ReadRequest) Reset()         { *this = ReadRequest{} }
func (this *ReadRequest) String() string { return proto.CompactTextString(this) }
func (*ReadRequest) ProtoMessage()       {}

func (this *ReadRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *ReadRequest) GetPos() int64 {
	if this != nil && this.Pos != nil {
		return *this.Pos
	}
	return 0
}

func (this *ReadRequest) GetMaxBytes() int64 {
	if this != nil && this.MaxBytes != nil {
		return *this.MaxBytes
	}
	return 0
}

type ReadResponse struct {
	Data             []byte `protobuf:"bytes,1,req,name=data" json:"data,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ReadResponse) Reset()         { *this = ReadResponse{} }
func (this *ReadResponse) String() string { return proto.CompactTextString(this) }
func (*ReadResponse) ProtoMessage()       {}

func (this *ReadResponse) GetData() []byte {
	if this != nil {
		return this.Data
	}
	return nil
}

type ReadKeyValueRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	StartKey         []byte  `protobuf:"bytes,2,req,name=start_key" json:"start_key,omitempty"`
	MaxBytes         *int64  `protobuf:"varint,3,req,name=max_bytes" json:"max_bytes,omitempty"`
	ValuePos         *int64  `protobuf:"varint,4,opt,name=value_pos" json:"value_pos,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ReadKeyValueRequest) Reset()         { *this = ReadKeyValueRequest{} }
func (this *ReadKeyValueRequest) String() string { return proto.CompactTextString(this) }
func (*ReadKeyValueRequest) ProtoMessage()       {}

func (this *ReadKeyValueRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

func (this *ReadKeyValueRequest) GetStartKey() []byte {
	if this != nil {
		return this.StartKey
	}
	return nil
}

func (this *ReadKeyValueRequest) GetMaxBytes() int64 {
	if this != nil && this.MaxBytes != nil {
		return *this.MaxBytes
	}
	return 0
}

func (this *ReadKeyValueRequest) GetValuePos() int64 {
	if this != nil && this.ValuePos != nil {
		return *this.ValuePos
	}
	return 0
}

type ReadKeyValueResponse struct {
	Data             []*ReadKeyValueResponse_KeyValue `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
	NextKey          []byte                           `protobuf:"bytes,2,opt,name=next_key" json:"next_key,omitempty"`
	TruncatedValue   *bool                            `protobuf:"varint,3,opt,name=truncated_value" json:"truncated_value,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (this *ReadKeyValueResponse) Reset()         { *this = ReadKeyValueResponse{} }
func (this *ReadKeyValueResponse) String() string { return proto.CompactTextString(this) }
func (*ReadKeyValueResponse) ProtoMessage()       {}

func (this *ReadKeyValueResponse) GetData() []*ReadKeyValueResponse_KeyValue {
	if this != nil {
		return this.Data
	}
	return nil
}

func (this *ReadKeyValueResponse) GetNextKey() []byte {
	if this != nil {
		return this.NextKey
	}
	return nil
}

func (this *ReadKeyValueResponse) GetTruncatedValue() bool {
	if this != nil && this.TruncatedValue != nil {
		return *this.TruncatedValue
	}
	return false
}

type ReadKeyValueResponse_KeyValue struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *ReadKeyValueResponse_KeyValue) Reset()         { *this = ReadKeyValueResponse_KeyValue{} }
func (this *ReadKeyValueResponse_KeyValue) String() string { return proto.CompactTextString(this) }
func (*ReadKeyValueResponse_KeyValue) ProtoMessage()       {}

func (this *ReadKeyValueResponse_KeyValue) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *ReadKeyValueResponse_KeyValue) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type ShuffleEnums struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *ShuffleEnums) Reset()         { *this = ShuffleEnums{} }
func (this *ShuffleEnums) String() string { return proto.CompactTextString(this) }
func (*ShuffleEnums) ProtoMessage()       {}

type ShuffleInputSpecification struct {
	Format           *ShuffleEnums_InputFormat `protobuf:"varint,1,opt,name=format,enum=files.ShuffleEnums_InputFormat,def=1" json:"format,omitempty"`
	Path             *string                   `protobuf:"bytes,2,req,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (this *ShuffleInputSpecification) Reset()         { *this = ShuffleInputSpecification{} }
func (this *ShuffleInputSpecification) String() string { return proto.CompactTextString(this) }
func (*ShuffleInputSpecification) ProtoMessage()       {}

const Default_ShuffleInputSpecification_Format ShuffleEnums_InputFormat = ShuffleEnums_RECORDS_KEY_VALUE_PROTO_INPUT

func (this *ShuffleInputSpecification) GetFormat() ShuffleEnums_InputFormat {
	if this != nil && this.Format != nil {
		return *this.Format
	}
	return Default_ShuffleInputSpecification_Format
}

func (this *ShuffleInputSpecification) GetPath() string {
	if this != nil && this.Path != nil {
		return *this.Path
	}
	return ""
}

type ShuffleOutputSpecification struct {
	Format           *ShuffleEnums_OutputFormat `protobuf:"varint,1,opt,name=format,enum=files.ShuffleEnums_OutputFormat,def=1" json:"format,omitempty"`
	Path             []string                   `protobuf:"bytes,2,rep,name=path" json:"path,omitempty"`
	XXX_unrecognized []byte                     `json:"-"`
}

func (this *ShuffleOutputSpecification) Reset()         { *this = ShuffleOutputSpecification{} }
func (this *ShuffleOutputSpecification) String() string { return proto.CompactTextString(this) }
func (*ShuffleOutputSpecification) ProtoMessage()       {}

const Default_ShuffleOutputSpecification_Format ShuffleEnums_OutputFormat = ShuffleEnums_RECORDS_KEY_MULTI_VALUE_PROTO_OUTPUT

func (this *ShuffleOutputSpecification) GetFormat() ShuffleEnums_OutputFormat {
	if this != nil && this.Format != nil {
		return *this.Format
	}
	return Default_ShuffleOutputSpecification_Format
}

func (this *ShuffleOutputSpecification) GetPath() []string {
	if this != nil {
		return this.Path
	}
	return nil
}

type ShuffleRequest struct {
	ShuffleName      *string                      `protobuf:"bytes,1,req,name=shuffle_name" json:"shuffle_name,omitempty"`
	Input            []*ShuffleInputSpecification `protobuf:"bytes,2,rep,name=input" json:"input,omitempty"`
	Output           *ShuffleOutputSpecification  `protobuf:"bytes,3,req,name=output" json:"output,omitempty"`
	ShuffleSizeBytes *int64                       `protobuf:"varint,4,req,name=shuffle_size_bytes" json:"shuffle_size_bytes,omitempty"`
	Callback         *ShuffleRequest_Callback     `protobuf:"bytes,5,req,name=callback" json:"callback,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (this *ShuffleRequest) Reset()         { *this = ShuffleRequest{} }
func (this *ShuffleRequest) String() string { return proto.CompactTextString(this) }
func (*ShuffleRequest) ProtoMessage()       {}

func (this *ShuffleRequest) GetShuffleName() string {
	if this != nil && this.ShuffleName != nil {
		return *this.ShuffleName
	}
	return ""
}

func (this *ShuffleRequest) GetInput() []*ShuffleInputSpecification {
	if this != nil {
		return this.Input
	}
	return nil
}

func (this *ShuffleRequest) GetOutput() *ShuffleOutputSpecification {
	if this != nil {
		return this.Output
	}
	return nil
}

func (this *ShuffleRequest) GetShuffleSizeBytes() int64 {
	if this != nil && this.ShuffleSizeBytes != nil {
		return *this.ShuffleSizeBytes
	}
	return 0
}

func (this *ShuffleRequest) GetCallback() *ShuffleRequest_Callback {
	if this != nil {
		return this.Callback
	}
	return nil
}

type ShuffleRequest_Callback struct {
	Url              *string `protobuf:"bytes,1,req,name=url" json:"url,omitempty"`
	AppVersionId     *string `protobuf:"bytes,2,opt,name=app_version_id" json:"app_version_id,omitempty"`
	Method           *string `protobuf:"bytes,3,opt,name=method,def=POST" json:"method,omitempty"`
	Queue            *string `protobuf:"bytes,4,opt,name=queue,def=default" json:"queue,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ShuffleRequest_Callback) Reset()         { *this = ShuffleRequest_Callback{} }
func (this *ShuffleRequest_Callback) String() string { return proto.CompactTextString(this) }
func (*ShuffleRequest_Callback) ProtoMessage()       {}

const Default_ShuffleRequest_Callback_Method string = "POST"
const Default_ShuffleRequest_Callback_Queue string = "default"

func (this *ShuffleRequest_Callback) GetUrl() string {
	if this != nil && this.Url != nil {
		return *this.Url
	}
	return ""
}

func (this *ShuffleRequest_Callback) GetAppVersionId() string {
	if this != nil && this.AppVersionId != nil {
		return *this.AppVersionId
	}
	return ""
}

func (this *ShuffleRequest_Callback) GetMethod() string {
	if this != nil && this.Method != nil {
		return *this.Method
	}
	return Default_ShuffleRequest_Callback_Method
}

func (this *ShuffleRequest_Callback) GetQueue() string {
	if this != nil && this.Queue != nil {
		return *this.Queue
	}
	return Default_ShuffleRequest_Callback_Queue
}

type ShuffleResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *ShuffleResponse) Reset()         { *this = ShuffleResponse{} }
func (this *ShuffleResponse) String() string { return proto.CompactTextString(this) }
func (*ShuffleResponse) ProtoMessage()       {}

type GetShuffleStatusRequest struct {
	ShuffleName      *string `protobuf:"bytes,1,req,name=shuffle_name" json:"shuffle_name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *GetShuffleStatusRequest) Reset()         { *this = GetShuffleStatusRequest{} }
func (this *GetShuffleStatusRequest) String() string { return proto.CompactTextString(this) }
func (*GetShuffleStatusRequest) ProtoMessage()       {}

func (this *GetShuffleStatusRequest) GetShuffleName() string {
	if this != nil && this.ShuffleName != nil {
		return *this.ShuffleName
	}
	return ""
}

type GetShuffleStatusResponse struct {
	Status           *ShuffleEnums_Status `protobuf:"varint,1,req,name=status,enum=files.ShuffleEnums_Status" json:"status,omitempty"`
	Description      *string              `protobuf:"bytes,2,opt,name=description" json:"description,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (this *GetShuffleStatusResponse) Reset()         { *this = GetShuffleStatusResponse{} }
func (this *GetShuffleStatusResponse) String() string { return proto.CompactTextString(this) }
func (*GetShuffleStatusResponse) ProtoMessage()       {}

func (this *GetShuffleStatusResponse) GetStatus() ShuffleEnums_Status {
	if this != nil && this.Status != nil {
		return *this.Status
	}
	return 0
}

func (this *GetShuffleStatusResponse) GetDescription() string {
	if this != nil && this.Description != nil {
		return *this.Description
	}
	return ""
}

type GetCapabilitiesRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *GetCapabilitiesRequest) Reset()         { *this = GetCapabilitiesRequest{} }
func (this *GetCapabilitiesRequest) String() string { return proto.CompactTextString(this) }
func (*GetCapabilitiesRequest) ProtoMessage()       {}

type GetCapabilitiesResponse struct {
	Filesystem       []string `protobuf:"bytes,1,rep,name=filesystem" json:"filesystem,omitempty"`
	ShuffleAvailable *bool    `protobuf:"varint,2,req,name=shuffle_available" json:"shuffle_available,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *GetCapabilitiesResponse) Reset()         { *this = GetCapabilitiesResponse{} }
func (this *GetCapabilitiesResponse) String() string { return proto.CompactTextString(this) }
func (*GetCapabilitiesResponse) ProtoMessage()       {}

func (this *GetCapabilitiesResponse) GetFilesystem() []string {
	if this != nil {
		return this.Filesystem
	}
	return nil
}

func (this *GetCapabilitiesResponse) GetShuffleAvailable() bool {
	if this != nil && this.ShuffleAvailable != nil {
		return *this.ShuffleAvailable
	}
	return false
}

type FinalizeRequest struct {
	Filename         *string `protobuf:"bytes,1,req,name=filename" json:"filename,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *FinalizeRequest) Reset()         { *this = FinalizeRequest{} }
func (this *FinalizeRequest) String() string { return proto.CompactTextString(this) }
func (*FinalizeRequest) ProtoMessage()       {}

func (this *FinalizeRequest) GetFilename() string {
	if this != nil && this.Filename != nil {
		return *this.Filename
	}
	return ""
}

type FinalizeResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *FinalizeResponse) Reset()         { *this = FinalizeResponse{} }
func (this *FinalizeResponse) String() string { return proto.CompactTextString(this) }
func (*FinalizeResponse) ProtoMessage()       {}

type GetDefaultGsBucketNameRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *GetDefaultGsBucketNameRequest) Reset()         { *this = GetDefaultGsBucketNameRequest{} }
func (this *GetDefaultGsBucketNameRequest) String() string { return proto.CompactTextString(this) }
func (*GetDefaultGsBucketNameRequest) ProtoMessage()       {}

type GetDefaultGsBucketNameResponse struct {
	DefaultGsBucketName *string `protobuf:"bytes,1,opt,name=default_gs_bucket_name" json:"default_gs_bucket_name,omitempty"`
	XXX_unrecognized    []byte  `json:"-"`
}

func (this *GetDefaultGsBucketNameResponse) Reset()         { *this = GetDefaultGsBucketNameResponse{} }
func (this *GetDefaultGsBucketNameResponse) String() string { return proto.CompactTextString(this) }
func (*GetDefaultGsBucketNameResponse) ProtoMessage()       {}

func (this *GetDefaultGsBucketNameResponse) GetDefaultGsBucketName() string {
	if this != nil && this.DefaultGsBucketName != nil {
		return *this.DefaultGsBucketName
	}
	return ""
}

type ListDirRequest struct {
	Path             *string `protobuf:"bytes,1,req,name=path" json:"path,omitempty"`
	Marker           *string `protobuf:"bytes,2,opt,name=marker" json:"marker,omitempty"`
	MaxKeys          *int64  `protobuf:"varint,3,opt,name=max_keys" json:"max_keys,omitempty"`
	Prefix           *string `protobuf:"bytes,4,opt,name=prefix" json:"prefix,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *ListDirRequest) Reset()         { *this = ListDirRequest{} }
func (this *ListDirRequest) String() string { return proto.CompactTextString(this) }
func (*ListDirRequest) ProtoMessage()       {}

func (this *ListDirRequest) GetPath() string {
	if this != nil && this.Path != nil {
		return *this.Path
	}
	return ""
}

func (this *ListDirRequest) GetMarker() string {
	if this != nil && this.Marker != nil {
		return *this.Marker
	}
	return ""
}

func (this *ListDirRequest) GetMaxKeys() int64 {
	if this != nil && this.MaxKeys != nil {
		return *this.MaxKeys
	}
	return 0
}

func (this *ListDirRequest) GetPrefix() string {
	if this != nil && this.Prefix != nil {
		return *this.Prefix
	}
	return ""
}

type ListDirResponse struct {
	Filenames        []string `protobuf:"bytes,1,rep,name=filenames" json:"filenames,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ListDirResponse) Reset()         { *this = ListDirResponse{} }
func (this *ListDirResponse) String() string { return proto.CompactTextString(this) }
func (*ListDirResponse) ProtoMessage()       {}

func (this *ListDirResponse) GetFilenames() []string {
	if this != nil {
		return this.Filenames
	}
	return nil
}

func init() {
	proto.RegisterEnum("files.FileServiceErrors_ErrorCode", FileServiceErrors_ErrorCode_name, FileServiceErrors_ErrorCode_value)
	proto.RegisterEnum("files.FileContentType_ContentType", FileContentType_ContentType_name, FileContentType_ContentType_value)
	proto.RegisterEnum("files.OpenRequest_OpenMode", OpenRequest_OpenMode_name, OpenRequest_OpenMode_value)
	proto.RegisterEnum("files.ShuffleEnums_InputFormat", ShuffleEnums_InputFormat_name, ShuffleEnums_InputFormat_value)
	proto.RegisterEnum("files.ShuffleEnums_OutputFormat", ShuffleEnums_OutputFormat_name, ShuffleEnums_OutputFormat_value)
	proto.RegisterEnum("files.ShuffleEnums_Status", ShuffleEnums_Status_name, ShuffleEnums_Status_value)
}
