// Code generated by protoc-gen-go.
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type UserServiceError_ErrorCode int32

const (
	UserServiceError_OK                    UserServiceError_ErrorCode = 0
	UserServiceError_REDIRECT_URL_TOO_LONG UserServiceError_ErrorCode = 1
	UserServiceError_NOT_ALLOWED           UserServiceError_ErrorCode = 2
	UserServiceError_OAUTH_INVALID_TOKEN   UserServiceError_ErrorCode = 3
	UserServiceError_OAUTH_INVALID_REQUEST UserServiceError_ErrorCode = 4
	UserServiceError_OAUTH_ERROR           UserServiceError_ErrorCode = 5
)

var UserServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "REDIRECT_URL_TOO_LONG",
	2: "NOT_ALLOWED",
	3: "OAUTH_INVALID_TOKEN",
	4: "OAUTH_INVALID_REQUEST",
	5: "OAUTH_ERROR",
}
var UserServiceError_ErrorCode_value = map[string]int32{
	"OK": 0,
	"REDIRECT_URL_TOO_LONG": 1,
	"NOT_ALLOWED":           2,
	"OAUTH_INVALID_TOKEN":   3,
	"OAUTH_INVALID_REQUEST": 4,
	"OAUTH_ERROR":           5,
}

func (x UserServiceError_ErrorCode) Enum() *UserServiceError_ErrorCode {
	p := new(UserServiceError_ErrorCode)
	*p = x
	return p
}
func (x UserServiceError_ErrorCode) String() string {
	return proto.EnumName(UserServiceError_ErrorCode_name, int32(x))
}
func (x UserServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *UserServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(UserServiceError_ErrorCode_value, data, "UserServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = UserServiceError_ErrorCode(value)
	return nil
}

type UserServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *UserServiceError) Reset()         { *this = UserServiceError{} }
func (this *UserServiceError) String() string { return proto.CompactTextString(this) }
func (*UserServiceError) ProtoMessage()       {}

type CreateLoginURLRequest struct {
	DestinationUrl    *string `protobuf:"bytes,1,req,name=destination_url" json:"destination_url,omitempty"`
	AuthDomain        *string `protobuf:"bytes,2,opt,name=auth_domain" json:"auth_domain,omitempty"`
	FederatedIdentity *string `protobuf:"bytes,3,opt,name=federated_identity" json:"federated_identity,omitempty"`
	XXX_unrecognized  []byte  `json:"-"`
}

func (this *CreateLoginURLRequest) Reset()         { *this = CreateLoginURLRequest{} }
func (this *CreateLoginURLRequest) String() string { return proto.CompactTextString(this) }
func (*CreateLoginURLRequest) ProtoMessage()       {}

func (this *CreateLoginURLRequest) GetDestinationUrl() string {
	if this != nil && this.DestinationUrl != nil {
		return *this.DestinationUrl
	}
	return ""
}

func (this *CreateLoginURLRequest) GetAuthDomain() string {
	if this != nil && this.AuthDomain != nil {
		return *this.AuthDomain
	}
	return ""
}

func (this *CreateLoginURLRequest) GetFederatedIdentity() string {
	if this != nil && this.FederatedIdentity != nil {
		return *this.FederatedIdentity
	}
	return ""
}

type CreateLoginURLResponse struct {
	LoginUrl         *string `protobuf:"bytes,1,req,name=login_url" json:"login_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateLoginURLResponse) Reset()         { *this = CreateLoginURLResponse{} }
func (this *CreateLoginURLResponse) String() string { return proto.CompactTextString(this) }
func (*CreateLoginURLResponse) ProtoMessage()       {}

func (this *CreateLoginURLResponse) GetLoginUrl() string {
	if this != nil && this.LoginUrl != nil {
		return *this.LoginUrl
	}
	return ""
}

type CreateLogoutURLRequest struct {
	DestinationUrl   *string `protobuf:"bytes,1,req,name=destination_url" json:"destination_url,omitempty"`
	AuthDomain       *string `protobuf:"bytes,2,opt,name=auth_domain" json:"auth_domain,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateLogoutURLRequest) Reset()         { *this = CreateLogoutURLRequest{} }
func (this *CreateLogoutURLRequest) String() string { return proto.CompactTextString(this) }
func (*CreateLogoutURLRequest) ProtoMessage()       {}

func (this *CreateLogoutURLRequest) GetDestinationUrl() string {
	if this != nil && this.DestinationUrl != nil {
		return *this.DestinationUrl
	}
	return ""
}

func (this *CreateLogoutURLRequest) GetAuthDomain() string {
	if this != nil && this.AuthDomain != nil {
		return *this.AuthDomain
	}
	return ""
}

type CreateLogoutURLResponse struct {
	LogoutUrl        *string `protobuf:"bytes,1,req,name=logout_url" json:"logout_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateLogoutURLResponse) Reset()         { *this = CreateLogoutURLResponse{} }
func (this *CreateLogoutURLResponse) String() string { return proto.CompactTextString(this) }
func (*CreateLogoutURLResponse) ProtoMessage()       {}

func (this *CreateLogoutURLResponse) GetLogoutUrl() string {
	if this != nil && this.LogoutUrl != nil {
		return *this.LogoutUrl
	}
	return ""
}

type GetOAuthUserRequest struct {
	Scope            *string `protobuf:"bytes,1,opt,name=scope" json:"scope,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *GetOAuthUserRequest) Reset()         { *this = GetOAuthUserRequest{} }
func (this *GetOAuthUserRequest) String() string { return proto.CompactTextString(this) }
func (*GetOAuthUserRequest) ProtoMessage()       {}

func (this *GetOAuthUserRequest) GetScope() string {
	if this != nil && this.Scope != nil {
		return *this.Scope
	}
	return ""
}

type GetOAuthUserResponse struct {
	Email            *string `protobuf:"bytes,1,req,name=email" json:"email,omitempty"`
	UserId           *string `protobuf:"bytes,2,req,name=user_id" json:"user_id,omitempty"`
	AuthDomain       *string `protobuf:"bytes,3,req,name=auth_domain" json:"auth_domain,omitempty"`
	UserOrganization *string `protobuf:"bytes,4,opt,name=user_organization" json:"user_organization,omitempty"`
	IsAdmin          *bool   `protobuf:"varint,5,opt,name=is_admin,def=0" json:"is_admin,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *GetOAuthUserResponse) Reset()         { *this = GetOAuthUserResponse{} }
func (this *GetOAuthUserResponse) String() string { return proto.CompactTextString(this) }
func (*GetOAuthUserResponse) ProtoMessage()       {}

const Default_GetOAuthUserResponse_IsAdmin bool = false

func (this *GetOAuthUserResponse) GetEmail() string {
	if this != nil && this.Email != nil {
		return *this.Email
	}
	return ""
}

func (this *GetOAuthUserResponse) GetUserId() string {
	if this != nil && this.UserId != nil {
		return *this.UserId
	}
	return ""
}

func (this *GetOAuthUserResponse) GetAuthDomain() string {
	if this != nil && this.AuthDomain != nil {
		return *this.AuthDomain
	}
	return ""
}

func (this *GetOAuthUserResponse) GetUserOrganization() string {
	if this != nil && this.UserOrganization != nil {
		return *this.UserOrganization
	}
	return ""
}

func (this *GetOAuthUserResponse) GetIsAdmin() bool {
	if this != nil && this.IsAdmin != nil {
		return *this.IsAdmin
	}
	return Default_GetOAuthUserResponse_IsAdmin
}

type CheckOAuthSignatureRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *CheckOAuthSignatureRequest) Reset()         { *this = CheckOAuthSignatureRequest{} }
func (this *CheckOAuthSignatureRequest) String() string { return proto.CompactTextString(this) }
func (*CheckOAuthSignatureRequest) ProtoMessage()       {}

type CheckOAuthSignatureResponse struct {
	OauthConsumerKey *string `protobuf:"bytes,1,req,name=oauth_consumer_key" json:"oauth_consumer_key,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CheckOAuthSignatureResponse) Reset()         { *this = CheckOAuthSignatureResponse{} }
func (this *CheckOAuthSignatureResponse) String() string { return proto.CompactTextString(this) }
func (*CheckOAuthSignatureResponse) ProtoMessage()       {}

func (this *CheckOAuthSignatureResponse) GetOauthConsumerKey() string {
	if this != nil && this.OauthConsumerKey != nil {
		return *this.OauthConsumerKey
	}
	return ""
}

type CreateFederatedLoginRequest struct {
	ClaimedId        *string `protobuf:"bytes,1,req,name=claimed_id" json:"claimed_id,omitempty"`
	ContinueUrl      *string `protobuf:"bytes,2,req,name=continue_url" json:"continue_url,omitempty"`
	Authority        *string `protobuf:"bytes,3,opt,name=authority" json:"authority,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateFederatedLoginRequest) Reset()         { *this = CreateFederatedLoginRequest{} }
func (this *CreateFederatedLoginRequest) String() string { return proto.CompactTextString(this) }
func (*CreateFederatedLoginRequest) ProtoMessage()       {}

func (this *CreateFederatedLoginRequest) GetClaimedId() string {
	if this != nil && this.ClaimedId != nil {
		return *this.ClaimedId
	}
	return ""
}

func (this *CreateFederatedLoginRequest) GetContinueUrl() string {
	if this != nil && this.ContinueUrl != nil {
		return *this.ContinueUrl
	}
	return ""
}

func (this *CreateFederatedLoginRequest) GetAuthority() string {
	if this != nil && this.Authority != nil {
		return *this.Authority
	}
	return ""
}

type CreateFederatedLoginResponse struct {
	RedirectedUrl    *string `protobuf:"bytes,1,req,name=redirected_url" json:"redirected_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateFederatedLoginResponse) Reset()         { *this = CreateFederatedLoginResponse{} }
func (this *CreateFederatedLoginResponse) String() string { return proto.CompactTextString(this) }
func (*CreateFederatedLoginResponse) ProtoMessage()       {}

func (this *CreateFederatedLoginResponse) GetRedirectedUrl() string {
	if this != nil && this.RedirectedUrl != nil {
		return *this.RedirectedUrl
	}
	return ""
}

type CreateFederatedLogoutRequest struct {
	DestinationUrl   *string `protobuf:"bytes,1,req,name=destination_url" json:"destination_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateFederatedLogoutRequest) Reset()         { *this = CreateFederatedLogoutRequest{} }
func (this *CreateFederatedLogoutRequest) String() string { return proto.CompactTextString(this) }
func (*CreateFederatedLogoutRequest) ProtoMessage()       {}

func (this *CreateFederatedLogoutRequest) GetDestinationUrl() string {
	if this != nil && this.DestinationUrl != nil {
		return *this.DestinationUrl
	}
	return ""
}

type CreateFederatedLogoutResponse struct {
	LogoutUrl        *string `protobuf:"bytes,1,req,name=logout_url" json:"logout_url,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateFederatedLogoutResponse) Reset()         { *this = CreateFederatedLogoutResponse{} }
func (this *CreateFederatedLogoutResponse) String() string { return proto.CompactTextString(this) }
func (*CreateFederatedLogoutResponse) ProtoMessage()       {}

func (this *CreateFederatedLogoutResponse) GetLogoutUrl() string {
	if this != nil && this.LogoutUrl != nil {
		return *this.LogoutUrl
	}
	return ""
}

func init() {
	proto.RegisterEnum("appengine.UserServiceError_ErrorCode", UserServiceError_ErrorCode_name, UserServiceError_ErrorCode_value)
}
