// Code generated by protoc-gen-go.
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type AppIdentityServiceError_ErrorCode int32

const (
	AppIdentityServiceError_SUCCESS                   AppIdentityServiceError_ErrorCode = 0
	AppIdentityServiceError_UNKNOWN_SCOPE             AppIdentityServiceError_ErrorCode = 9
	AppIdentityServiceError_BLOB_TOO_LARGE            AppIdentityServiceError_ErrorCode = 1000
	AppIdentityServiceError_DEADLINE_EXCEEDED         AppIdentityServiceError_ErrorCode = 1001
	AppIdentityServiceError_NOT_A_VALID_APP           AppIdentityServiceError_ErrorCode = 1002
	AppIdentityServiceError_UNKNOWN_ERROR             AppIdentityServiceError_ErrorCode = 1003
	AppIdentityServiceError_GAIAMINT_NOT_INITIAILIZED AppIdentityServiceError_ErrorCode = 1004
	AppIdentityServiceError_NOT_ALLOWED               AppIdentityServiceError_ErrorCode = 1005
)

var AppIdentityServiceError_ErrorCode_name = map[int32]string{
	0:    "SUCCESS",
	9:    "UNKNOWN_SCOPE",
	1000: "BLOB_TOO_LARGE",
	1001: "DEADLINE_EXCEEDED",
	1002: "NOT_A_VALID_APP",
	1003: "UNKNOWN_ERROR",
	1004: "GAIAMINT_NOT_INITIAILIZED",
	1005: "NOT_ALLOWED",
}
var AppIdentityServiceError_ErrorCode_value = map[string]int32{
	"SUCCESS":                   0,
	"UNKNOWN_SCOPE":             9,
	"BLOB_TOO_LARGE":            1000,
	"DEADLINE_EXCEEDED":         1001,
	"NOT_A_VALID_APP":           1002,
	"UNKNOWN_ERROR":             1003,
	"GAIAMINT_NOT_INITIAILIZED": 1004,
	"NOT_ALLOWED":               1005,
}

func (x AppIdentityServiceError_ErrorCode) Enum() *AppIdentityServiceError_ErrorCode {
	p := new(AppIdentityServiceError_ErrorCode)
	*p = x
	return p
}
func (x AppIdentityServiceError_ErrorCode) String() string {
	return proto.EnumName(AppIdentityServiceError_ErrorCode_name, int32(x))
}
func (x AppIdentityServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *AppIdentityServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(AppIdentityServiceError_ErrorCode_value, data, "AppIdentityServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = AppIdentityServiceError_ErrorCode(value)
	return nil
}

type AppIdentityServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *AppIdentityServiceError) Reset()         { *this = AppIdentityServiceError{} }
func (this *AppIdentityServiceError) String() string { return proto.CompactTextString(this) }
func (*AppIdentityServiceError) ProtoMessage()       {}

type SignForAppRequest struct {
	BytesToSign      []byte `protobuf:"bytes,1,opt,name=bytes_to_sign" json:"bytes_to_sign,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *SignForAppRequest) Reset()         { *this = SignForAppRequest{} }
func (this *SignForAppRequest) String() string { return proto.CompactTextString(this) }
func (*SignForAppRequest) ProtoMessage()       {}

func (this *SignForAppRequest) GetBytesToSign() []byte {
	if this != nil {
		return this.BytesToSign
	}
	return nil
}

type SignForAppResponse struct {
	KeyName          *string `protobuf:"bytes,1,opt,name=key_name" json:"key_name,omitempty"`
	SignatureBytes   []byte  `protobuf:"bytes,2,opt,name=signature_bytes" json:"signature_bytes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *SignForAppResponse) Reset()         { *this = SignForAppResponse{} }
func (this *SignForAppResponse) String() string { return proto.CompactTextString(this) }
func (*SignForAppResponse) ProtoMessage()       {}

func (this *SignForAppResponse) GetKeyName() string {
	if this != nil && this.KeyName != nil {
		return *this.KeyName
	}
	return ""
}

func (this *SignForAppResponse) GetSignatureBytes() []byte {
	if this != nil {
		return this.SignatureBytes
	}
	return nil
}

type GetPublicCertificateForAppRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *GetPublicCertificateForAppRequest) Reset()         { *this = GetPublicCertificateForAppRequest{} }
func (this *GetPublicCertificateForAppRequest) String() string { return proto.CompactTextString(this) }
func (*GetPublicCertificateForAppRequest) ProtoMessage()       {}

type PublicCertificate struct {
	KeyName            *string `protobuf:"bytes,1,opt,name=key_name" json:"key_name,omitempty"`
	X509CertificatePem *string `protobuf:"bytes,2,opt,name=x509_certificate_pem" json:"x509_certificate_pem,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (this *PublicCertificate) Reset()         { *this = PublicCertificate{} }
func (this *PublicCertificate) String() string { return proto.CompactTextString(this) }
func (*PublicCertificate) ProtoMessage()       {}

func (this *PublicCertificate) GetKeyName() string {
	if this != nil && this.KeyName != nil {
		return *this.KeyName
	}
	return ""
}

func (this *PublicCertificate) GetX509CertificatePem() string {
	if this != nil && this.X509CertificatePem != nil {
		return *this.X509CertificatePem
	}
	return ""
}

type GetPublicCertificateForAppResponse struct {
	PublicCertificateList      []*PublicCertificate `protobuf:"bytes,1,rep,name=public_certificate_list" json:"public_certificate_list,omitempty"`
	MaxClientCacheTimeInSecond *int64               `protobuf:"varint,2,opt,name=max_client_cache_time_in_second" json:"max_client_cache_time_in_second,omitempty"`
	XXX_unrecognized           []byte               `json:"-"`
}

func (this *GetPublicCertificateForAppResponse) Reset()         { *this = GetPublicCertificateForAppResponse{} }
func (this *GetPublicCertificateForAppResponse) String() string { return proto.CompactTextString(this) }
func (*GetPublicCertificateForAppResponse) ProtoMessage()       {}

func (this *GetPublicCertificateForAppResponse) GetPublicCertificateList() []*PublicCertificate {
	if this != nil {
		return this.PublicCertificateList
	}
	return nil
}

func (this *GetPublicCertificateForAppResponse) GetMaxClientCacheTimeInSecond() int64 {
	if this != nil && this.MaxClientCacheTimeInSecond != nil {
		return *this.MaxClientCacheTimeInSecond
	}
	return 0
}

type GetServiceAccountNameRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *GetServiceAccountNameRequest) Reset()         { *this = GetServiceAccountNameRequest{} }
func (this *GetServiceAccountNameRequest) String() string { return proto.CompactTextString(this) }
func (*GetServiceAccountNameRequest) ProtoMessage()       {}

type GetServiceAccountNameResponse struct {
	ServiceAccountName *string `protobuf:"bytes,1,opt,name=service_account_name" json:"service_account_name,omitempty"`
	XXX_unrecognized   []byte  `json:"-"`
}

func (this *GetServiceAccountNameResponse) Reset()         { *this = GetServiceAccountNameResponse{} }
func (this *GetServiceAccountNameResponse) String() string { return proto.CompactTextString(this) }
func (*GetServiceAccountNameResponse) ProtoMessage()       {}

func (this *GetServiceAccountNameResponse) GetServiceAccountName() string {
	if this != nil && this.ServiceAccountName != nil {
		return *this.ServiceAccountName
	}
	return ""
}

type GetAccessTokenRequest struct {
	Scope            []string `protobuf:"bytes,1,rep,name=scope" json:"scope,omitempty"`
	ServiceAccountId *int64   `protobuf:"varint,2,opt,name=service_account_id" json:"service_account_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *GetAccessTokenRequest) Reset()         { *this = GetAccessTokenRequest{} }
func (this *GetAccessTokenRequest) String() string { return proto.CompactTextString(this) }
func (*GetAccessTokenRequest) ProtoMessage()       {}

func (this *GetAccessTokenRequest) GetScope() []string {
	if this != nil {
		return this.Scope
	}
	return nil
}

func (this *GetAccessTokenRequest) GetServiceAccountId() int64 {
	if this != nil && this.ServiceAccountId != nil {
		return *this.ServiceAccountId
	}
	return 0
}

type GetAccessTokenResponse struct {
	AccessToken      *string `protobuf:"bytes,1,opt,name=access_token" json:"access_token,omitempty"`
	ExpirationTime   *int64  `protobuf:"varint,2,opt,name=expiration_time" json:"expiration_time,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *GetAccessTokenResponse) Reset()         { *this = GetAccessTokenResponse{} }
func (this *GetAccessTokenResponse) String() string { return proto.CompactTextString(this) }
func (*GetAccessTokenResponse) ProtoMessage()       {}

func (this *GetAccessTokenResponse) GetAccessToken() string {
	if this != nil && this.AccessToken != nil {
		return *this.AccessToken
	}
	return ""
}

func (this *GetAccessTokenResponse) GetExpirationTime() int64 {
	if this != nil && this.ExpirationTime != nil {
		return *this.ExpirationTime
	}
	return 0
}

func init() {
	proto.RegisterEnum("appengine.AppIdentityServiceError_ErrorCode", AppIdentityServiceError_ErrorCode_name, AppIdentityServiceError_ErrorCode_value)
}
