// Code generated by protoc-gen-go from "channel_service.proto"
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type ChannelServiceError_ErrorCode int32

const (
	ChannelServiceError_OK                             ChannelServiceError_ErrorCode = 0
	ChannelServiceError_INTERNAL_ERROR                 ChannelServiceError_ErrorCode = 1
	ChannelServiceError_INVALID_CHANNEL_KEY            ChannelServiceError_ErrorCode = 2
	ChannelServiceError_BAD_MESSAGE                    ChannelServiceError_ErrorCode = 3
	ChannelServiceError_INVALID_CHANNEL_TOKEN_DURATION ChannelServiceError_ErrorCode = 4
	ChannelServiceError_APPID_ALIAS_REQUIRED           ChannelServiceError_ErrorCode = 5
)

var ChannelServiceError_ErrorCode_name = map[int32]string{
	0: "OK",
	1: "INTERNAL_ERROR",
	2: "INVALID_CHANNEL_KEY",
	3: "BAD_MESSAGE",
	4: "INVALID_CHANNEL_TOKEN_DURATION",
	5: "APPID_ALIAS_REQUIRED",
}
var ChannelServiceError_ErrorCode_value = map[string]int32{
	"OK":                             0,
	"INTERNAL_ERROR":                 1,
	"INVALID_CHANNEL_KEY":            2,
	"BAD_MESSAGE":                    3,
	"INVALID_CHANNEL_TOKEN_DURATION": 4,
	"APPID_ALIAS_REQUIRED":           5,
}

func (x ChannelServiceError_ErrorCode) Enum() *ChannelServiceError_ErrorCode {
	p := new(ChannelServiceError_ErrorCode)
	*p = x
	return p
}
func (x ChannelServiceError_ErrorCode) String() string {
	return proto.EnumName(ChannelServiceError_ErrorCode_name, int32(x))
}
func (x ChannelServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *ChannelServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ChannelServiceError_ErrorCode_value, data, "ChannelServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = ChannelServiceError_ErrorCode(value)
	return nil
}

type ChannelServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *ChannelServiceError) Reset()         { *this = ChannelServiceError{} }
func (this *ChannelServiceError) String() string { return proto.CompactTextString(this) }
func (*ChannelServiceError) ProtoMessage()       {}

type CreateChannelRequest struct {
	ApplicationKey   *string `protobuf:"bytes,1,req,name=application_key" json:"application_key,omitempty"`
	DurationMinutes  *int32  `protobuf:"varint,2,opt,name=duration_minutes" json:"duration_minutes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateChannelRequest) Reset()         { *this = CreateChannelRequest{} }
func (this *CreateChannelRequest) String() string { return proto.CompactTextString(this) }
func (*CreateChannelRequest) ProtoMessage()       {}

func (this *CreateChannelRequest) GetApplicationKey() string {
	if this != nil && this.ApplicationKey != nil {
		return *this.ApplicationKey
	}
	return ""
}

func (this *CreateChannelRequest) GetDurationMinutes() int32 {
	if this != nil && this.DurationMinutes != nil {
		return *this.DurationMinutes
	}
	return 0
}

type CreateChannelResponse struct {
	Token            *string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
	DurationMinutes  *int32  `protobuf:"varint,3,opt,name=duration_minutes" json:"duration_minutes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *CreateChannelResponse) Reset()         { *this = CreateChannelResponse{} }
func (this *CreateChannelResponse) String() string { return proto.CompactTextString(this) }
func (*CreateChannelResponse) ProtoMessage()       {}

func (this *CreateChannelResponse) GetToken() string {
	if this != nil && this.Token != nil {
		return *this.Token
	}
	return ""
}

func (this *CreateChannelResponse) GetDurationMinutes() int32 {
	if this != nil && this.DurationMinutes != nil {
		return *this.DurationMinutes
	}
	return 0
}

type SendMessageRequest struct {
	ApplicationKey   *string `protobuf:"bytes,1,req,name=application_key" json:"application_key,omitempty"`
	Message          *string `protobuf:"bytes,2,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *SendMessageRequest) Reset()         { *this = SendMessageRequest{} }
func (this *SendMessageRequest) String() string { return proto.CompactTextString(this) }
func (*SendMessageRequest) ProtoMessage()       {}

func (this *SendMessageRequest) GetApplicationKey() string {
	if this != nil && this.ApplicationKey != nil {
		return *this.ApplicationKey
	}
	return ""
}

func (this *SendMessageRequest) GetMessage() string {
	if this != nil && this.Message != nil {
		return *this.Message
	}
	return ""
}

type ChannelPresenceRequest struct {
	ApplicationKey   []string `protobuf:"bytes,1,rep,name=application_key" json:"application_key,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *ChannelPresenceRequest) Reset()         { *this = ChannelPresenceRequest{} }
func (this *ChannelPresenceRequest) String() string { return proto.CompactTextString(this) }
func (*ChannelPresenceRequest) ProtoMessage()       {}

type ChannelPresenceResponse struct {
	QueryResult      []*ChannelPresenceResponse_QueryResult `protobuf:"bytes,1,rep,name=query_result" json:"query_result,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (this *ChannelPresenceResponse) Reset()         { *this = ChannelPresenceResponse{} }
func (this *ChannelPresenceResponse) String() string { return proto.CompactTextString(this) }
func (*ChannelPresenceResponse) ProtoMessage()       {}

type ChannelPresenceResponse_QueryResult struct {
	ApplicationKey   *string                        `protobuf:"bytes,1,req,name=application_key" json:"application_key,omitempty"`
	IsAvailable      *bool                          `protobuf:"varint,2,req,name=is_available" json:"is_available,omitempty"`
	ErrorCode        *ChannelServiceError_ErrorCode `protobuf:"varint,3,req,name=error_code,enum=appengine.ChannelServiceError_ErrorCode" json:"error_code,omitempty"`
	XXX_unrecognized []byte                         `json:"-"`
}

func (this *ChannelPresenceResponse_QueryResult) Reset() {
	*this = ChannelPresenceResponse_QueryResult{}
}
func (this *ChannelPresenceResponse_QueryResult) String() string { return proto.CompactTextString(this) }
func (*ChannelPresenceResponse_QueryResult) ProtoMessage()       {}

func (this *ChannelPresenceResponse_QueryResult) GetApplicationKey() string {
	if this != nil && this.ApplicationKey != nil {
		return *this.ApplicationKey
	}
	return ""
}

func (this *ChannelPresenceResponse_QueryResult) GetIsAvailable() bool {
	if this != nil && this.IsAvailable != nil {
		return *this.IsAvailable
	}
	return false
}

func (this *ChannelPresenceResponse_QueryResult) GetErrorCode() ChannelServiceError_ErrorCode {
	if this != nil && this.ErrorCode != nil {
		return *this.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterEnum("appengine.ChannelServiceError_ErrorCode", ChannelServiceError_ErrorCode_name, ChannelServiceError_ErrorCode_value)
}
