// Code generated by protoc-gen-go.
// DO NOT EDIT!

package appengine

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type TaskQueueServiceError_ErrorCode int32

const (
	TaskQueueServiceError_OK                              TaskQueueServiceError_ErrorCode = 0
	TaskQueueServiceError_UNKNOWN_QUEUE                   TaskQueueServiceError_ErrorCode = 1
	TaskQueueServiceError_TRANSIENT_ERROR                 TaskQueueServiceError_ErrorCode = 2
	TaskQueueServiceError_INTERNAL_ERROR                  TaskQueueServiceError_ErrorCode = 3
	TaskQueueServiceError_TASK_TOO_LARGE                  TaskQueueServiceError_ErrorCode = 4
	TaskQueueServiceError_INVALID_TASK_NAME               TaskQueueServiceError_ErrorCode = 5
	TaskQueueServiceError_INVALID_QUEUE_NAME              TaskQueueServiceError_ErrorCode = 6
	TaskQueueServiceError_INVALID_URL                     TaskQueueServiceError_ErrorCode = 7
	TaskQueueServiceError_INVALID_QUEUE_RATE              TaskQueueServiceError_ErrorCode = 8
	TaskQueueServiceError_PERMISSION_DENIED               TaskQueueServiceError_ErrorCode = 9
	TaskQueueServiceError_TASK_ALREADY_EXISTS             TaskQueueServiceError_ErrorCode = 10
	TaskQueueServiceError_TOMBSTONED_TASK                 TaskQueueServiceError_ErrorCode = 11
	TaskQueueServiceError_INVALID_ETA                     TaskQueueServiceError_ErrorCode = 12
	TaskQueueServiceError_INVALID_REQUEST                 TaskQueueServiceError_ErrorCode = 13
	TaskQueueServiceError_UNKNOWN_TASK                    TaskQueueServiceError_ErrorCode = 14
	TaskQueueServiceError_TOMBSTONED_QUEUE                TaskQueueServiceError_ErrorCode = 15
	TaskQueueServiceError_DUPLICATE_TASK_NAME             TaskQueueServiceError_ErrorCode = 16
	TaskQueueServiceError_SKIPPED                         TaskQueueServiceError_ErrorCode = 17
	TaskQueueServiceError_TOO_MANY_TASKS                  TaskQueueServiceError_ErrorCode = 18
	TaskQueueServiceError_INVALID_PAYLOAD                 TaskQueueServiceError_ErrorCode = 19
	TaskQueueServiceError_INVALID_RETRY_PARAMETERS        TaskQueueServiceError_ErrorCode = 20
	TaskQueueServiceError_INVALID_QUEUE_MODE              TaskQueueServiceError_ErrorCode = 21
	TaskQueueServiceError_ACL_LOOKUP_ERROR                TaskQueueServiceError_ErrorCode = 22
	TaskQueueServiceError_TRANSACTIONAL_REQUEST_TOO_LARGE TaskQueueServiceError_ErrorCode = 23
	TaskQueueServiceError_INCORRECT_CREATOR_NAME          TaskQueueServiceError_ErrorCode = 24
	TaskQueueServiceError_TASK_LEASE_EXPIRED              TaskQueueServiceError_ErrorCode = 25
	TaskQueueServiceError_QUEUE_PAUSED                    TaskQueueServiceError_ErrorCode = 26
	TaskQueueServiceError_INVALID_TAG                     TaskQueueServiceError_ErrorCode = 27
	TaskQueueServiceError_DATASTORE_ERROR                 TaskQueueServiceError_ErrorCode = 10000
)

var TaskQueueServiceError_ErrorCode_name = map[int32]string{
	0:     "OK",
	1:     "UNKNOWN_QUEUE",
	2:     "TRANSIENT_ERROR",
	3:     "INTERNAL_ERROR",
	4:     "TASK_TOO_LARGE",
	5:     "INVALID_TASK_NAME",
	6:     "INVALID_QUEUE_NAME",
	7:     "INVALID_URL",
	8:     "INVALID_QUEUE_RATE",
	9:     "PERMISSION_DENIED",
	10:    "TASK_ALREADY_EXISTS",
	11:    "TOMBSTONED_TASK",
	12:    "INVALID_ETA",
	13:    "INVALID_REQUEST",
	14:    "UNKNOWN_TASK",
	15:    "TOMBSTONED_QUEUE",
	16:    "DUPLICATE_TASK_NAME",
	17:    "SKIPPED",
	18:    "TOO_MANY_TASKS",
	19:    "INVALID_PAYLOAD",
	20:    "INVALID_RETRY_PARAMETERS",
	21:    "INVALID_QUEUE_MODE",
	22:    "ACL_LOOKUP_ERROR",
	23:    "TRANSACTIONAL_REQUEST_TOO_LARGE",
	24:    "INCORRECT_CREATOR_NAME",
	25:    "TASK_LEASE_EXPIRED",
	26:    "QUEUE_PAUSED",
	27:    "INVALID_TAG",
	10000: "DATASTORE_ERROR",
}
var TaskQueueServiceError_ErrorCode_value = map[string]int32{
	"OK":                              0,
	"UNKNOWN_QUEUE":                   1,
	"TRANSIENT_ERROR":                 2,
	"INTERNAL_ERROR":                  3,
	"TASK_TOO_LARGE":                  4,
	"INVALID_TASK_NAME":               5,
	"INVALID_QUEUE_NAME":              6,
	"INVALID_URL":                     7,
	"INVALID_QUEUE_RATE":              8,
	"PERMISSION_DENIED":               9,
	"TASK_ALREADY_EXISTS":             10,
	"TOMBSTONED_TASK":                 11,
	"INVALID_ETA":                     12,
	"INVALID_REQUEST":                 13,
	"UNKNOWN_TASK":                    14,
	"TOMBSTONED_QUEUE":                15,
	"DUPLICATE_TASK_NAME":             16,
	"SKIPPED":                         17,
	"TOO_MANY_TASKS":                  18,
	"INVALID_PAYLOAD":                 19,
	"INVALID_RETRY_PARAMETERS":        20,
	"INVALID_QUEUE_MODE":              21,
	"ACL_LOOKUP_ERROR":                22,
	"TRANSACTIONAL_REQUEST_TOO_LARGE": 23,
	"INCORRECT_CREATOR_NAME":          24,
	"TASK_LEASE_EXPIRED":              25,
	"QUEUE_PAUSED":                    26,
	"INVALID_TAG":                     27,
	"DATASTORE_ERROR":                 10000,
}

func (x TaskQueueServiceError_ErrorCode) Enum() *TaskQueueServiceError_ErrorCode {
	p := new(TaskQueueServiceError_ErrorCode)
	*p = x
	return p
}
func (x TaskQueueServiceError_ErrorCode) String() string {
	return proto.EnumName(TaskQueueServiceError_ErrorCode_name, int32(x))
}
func (x TaskQueueServiceError_ErrorCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *TaskQueueServiceError_ErrorCode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskQueueServiceError_ErrorCode_value, data, "TaskQueueServiceError_ErrorCode")
	if err != nil {
		return err
	}
	*x = TaskQueueServiceError_ErrorCode(value)
	return nil
}

type TaskQueueMode_Mode int32

const (
	TaskQueueMode_PUSH TaskQueueMode_Mode = 0
	TaskQueueMode_PULL TaskQueueMode_Mode = 1
)

var TaskQueueMode_Mode_name = map[int32]string{
	0: "PUSH",
	1: "PULL",
}
var TaskQueueMode_Mode_value = map[string]int32{
	"PUSH": 0,
	"PULL": 1,
}

func (x TaskQueueMode_Mode) Enum() *TaskQueueMode_Mode {
	p := new(TaskQueueMode_Mode)
	*p = x
	return p
}
func (x TaskQueueMode_Mode) String() string {
	return proto.EnumName(TaskQueueMode_Mode_name, int32(x))
}
func (x TaskQueueMode_Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *TaskQueueMode_Mode) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskQueueMode_Mode_value, data, "TaskQueueMode_Mode")
	if err != nil {
		return err
	}
	*x = TaskQueueMode_Mode(value)
	return nil
}

type TaskQueueAddRequest_RequestMethod int32

const (
	TaskQueueAddRequest_GET    TaskQueueAddRequest_RequestMethod = 1
	TaskQueueAddRequest_POST   TaskQueueAddRequest_RequestMethod = 2
	TaskQueueAddRequest_HEAD   TaskQueueAddRequest_RequestMethod = 3
	TaskQueueAddRequest_PUT    TaskQueueAddRequest_RequestMethod = 4
	TaskQueueAddRequest_DELETE TaskQueueAddRequest_RequestMethod = 5
)

var TaskQueueAddRequest_RequestMethod_name = map[int32]string{
	1: "GET",
	2: "POST",
	3: "HEAD",
	4: "PUT",
	5: "DELETE",
}
var TaskQueueAddRequest_RequestMethod_value = map[string]int32{
	"GET":    1,
	"POST":   2,
	"HEAD":   3,
	"PUT":    4,
	"DELETE": 5,
}

func (x TaskQueueAddRequest_RequestMethod) Enum() *TaskQueueAddRequest_RequestMethod {
	p := new(TaskQueueAddRequest_RequestMethod)
	*p = x
	return p
}
func (x TaskQueueAddRequest_RequestMethod) String() string {
	return proto.EnumName(TaskQueueAddRequest_RequestMethod_name, int32(x))
}
func (x TaskQueueAddRequest_RequestMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *TaskQueueAddRequest_RequestMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskQueueAddRequest_RequestMethod_value, data, "TaskQueueAddRequest_RequestMethod")
	if err != nil {
		return err
	}
	*x = TaskQueueAddRequest_RequestMethod(value)
	return nil
}

type TaskQueueQueryTasksResponse_Task_RequestMethod int32

const (
	TaskQueueQueryTasksResponse_Task_GET    TaskQueueQueryTasksResponse_Task_RequestMethod = 1
	TaskQueueQueryTasksResponse_Task_POST   TaskQueueQueryTasksResponse_Task_RequestMethod = 2
	TaskQueueQueryTasksResponse_Task_HEAD   TaskQueueQueryTasksResponse_Task_RequestMethod = 3
	TaskQueueQueryTasksResponse_Task_PUT    TaskQueueQueryTasksResponse_Task_RequestMethod = 4
	TaskQueueQueryTasksResponse_Task_DELETE TaskQueueQueryTasksResponse_Task_RequestMethod = 5
)

var TaskQueueQueryTasksResponse_Task_RequestMethod_name = map[int32]string{
	1: "GET",
	2: "POST",
	3: "HEAD",
	4: "PUT",
	5: "DELETE",
}
var TaskQueueQueryTasksResponse_Task_RequestMethod_value = map[string]int32{
	"GET":    1,
	"POST":   2,
	"HEAD":   3,
	"PUT":    4,
	"DELETE": 5,
}

func (x TaskQueueQueryTasksResponse_Task_RequestMethod) Enum() *TaskQueueQueryTasksResponse_Task_RequestMethod {
	p := new(TaskQueueQueryTasksResponse_Task_RequestMethod)
	*p = x
	return p
}
func (x TaskQueueQueryTasksResponse_Task_RequestMethod) String() string {
	return proto.EnumName(TaskQueueQueryTasksResponse_Task_RequestMethod_name, int32(x))
}
func (x TaskQueueQueryTasksResponse_Task_RequestMethod) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}
func (x *TaskQueueQueryTasksResponse_Task_RequestMethod) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(TaskQueueQueryTasksResponse_Task_RequestMethod_value, data, "TaskQueueQueryTasksResponse_Task_RequestMethod")
	if err != nil {
		return err
	}
	*x = TaskQueueQueryTasksResponse_Task_RequestMethod(value)
	return nil
}

type Transaction struct {
	Handle           *uint64 `protobuf:"fixed64,1,req,name=handle" json:"handle,omitempty"`
	App              *string `protobuf:"bytes,2,req,name=app" json:"app,omitempty"`
	MarkChanges      *bool   `protobuf:"varint,3,opt,name=mark_changes,def=0" json:"mark_changes,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (this *Transaction) Reset()         { *this = Transaction{} }
func (this *Transaction) String() string { return proto.CompactTextString(this) }
func (*Transaction) ProtoMessage()       {}

const Default_Transaction_MarkChanges bool = false

func (this *Transaction) GetHandle() uint64 {
	if this != nil && this.Handle != nil {
		return *this.Handle
	}
	return 0
}

func (this *Transaction) GetApp() string {
	if this != nil && this.App != nil {
		return *this.App
	}
	return ""
}

func (this *Transaction) GetMarkChanges() bool {
	if this != nil && this.MarkChanges != nil {
		return *this.MarkChanges
	}
	return Default_Transaction_MarkChanges
}

type TaskQueueServiceError struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueServiceError) Reset()         { *this = TaskQueueServiceError{} }
func (this *TaskQueueServiceError) String() string { return proto.CompactTextString(this) }
func (*TaskQueueServiceError) ProtoMessage()       {}

type TaskPayload struct {
	XXX_extensions   map[int32]proto.Extension `json:"-"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (this *TaskPayload) Reset()         { *this = TaskPayload{} }
func (this *TaskPayload) String() string { return proto.CompactTextString(this) }
func (*TaskPayload) ProtoMessage()       {}

func (this *TaskPayload) Marshal() ([]byte, error) {
	return proto.MarshalMessageSet(this.ExtensionMap())
}
func (this *TaskPayload) Unmarshal(buf []byte) error {
	return proto.UnmarshalMessageSet(buf, this.ExtensionMap())
}

// ensure TaskPayload satisfies proto.Marshaler and proto.Unmarshaler
var _ proto.Marshaler = (*TaskPayload)(nil)
var _ proto.Unmarshaler = (*TaskPayload)(nil)

var extRange_TaskPayload = []proto.ExtensionRange{
	{10, 2147483646},
}

func (*TaskPayload) ExtensionRangeArray() []proto.ExtensionRange {
	return extRange_TaskPayload
}
func (this *TaskPayload) ExtensionMap() map[int32]proto.Extension {
	if this.XXX_extensions == nil {
		this.XXX_extensions = make(map[int32]proto.Extension)
	}
	return this.XXX_extensions
}

type TaskQueueRetryParameters struct {
	RetryLimit       *int32   `protobuf:"varint,1,opt,name=retry_limit" json:"retry_limit,omitempty"`
	AgeLimitSec      *int64   `protobuf:"varint,2,opt,name=age_limit_sec" json:"age_limit_sec,omitempty"`
	MinBackoffSec    *float64 `protobuf:"fixed64,3,opt,name=min_backoff_sec,def=0.1" json:"min_backoff_sec,omitempty"`
	MaxBackoffSec    *float64 `protobuf:"fixed64,4,opt,name=max_backoff_sec,def=3600" json:"max_backoff_sec,omitempty"`
	MaxDoublings     *int32   `protobuf:"varint,5,opt,name=max_doublings,def=16" json:"max_doublings,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueRetryParameters) Reset()         { *this = TaskQueueRetryParameters{} }
func (this *TaskQueueRetryParameters) String() string { return proto.CompactTextString(this) }
func (*TaskQueueRetryParameters) ProtoMessage()       {}

const Default_TaskQueueRetryParameters_MinBackoffSec float64 = 0.1
const Default_TaskQueueRetryParameters_MaxBackoffSec float64 = 3600
const Default_TaskQueueRetryParameters_MaxDoublings int32 = 16

func (this *TaskQueueRetryParameters) GetRetryLimit() int32 {
	if this != nil && this.RetryLimit != nil {
		return *this.RetryLimit
	}
	return 0
}

func (this *TaskQueueRetryParameters) GetAgeLimitSec() int64 {
	if this != nil && this.AgeLimitSec != nil {
		return *this.AgeLimitSec
	}
	return 0
}

func (this *TaskQueueRetryParameters) GetMinBackoffSec() float64 {
	if this != nil && this.MinBackoffSec != nil {
		return *this.MinBackoffSec
	}
	return Default_TaskQueueRetryParameters_MinBackoffSec
}

func (this *TaskQueueRetryParameters) GetMaxBackoffSec() float64 {
	if this != nil && this.MaxBackoffSec != nil {
		return *this.MaxBackoffSec
	}
	return Default_TaskQueueRetryParameters_MaxBackoffSec
}

func (this *TaskQueueRetryParameters) GetMaxDoublings() int32 {
	if this != nil && this.MaxDoublings != nil {
		return *this.MaxDoublings
	}
	return Default_TaskQueueRetryParameters_MaxDoublings
}

type TaskQueueAcl struct {
	UserEmail        [][]byte `protobuf:"bytes,1,rep,name=user_email" json:"user_email,omitempty"`
	WriterEmail      [][]byte `protobuf:"bytes,2,rep,name=writer_email" json:"writer_email,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueAcl) Reset()         { *this = TaskQueueAcl{} }
func (this *TaskQueueAcl) String() string { return proto.CompactTextString(this) }
func (*TaskQueueAcl) ProtoMessage()       {}

type TaskQueueHttpHeader struct {
	Key              []byte `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            []byte `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueHttpHeader) Reset()         { *this = TaskQueueHttpHeader{} }
func (this *TaskQueueHttpHeader) String() string { return proto.CompactTextString(this) }
func (*TaskQueueHttpHeader) ProtoMessage()       {}

func (this *TaskQueueHttpHeader) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *TaskQueueHttpHeader) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type TaskQueueMode struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueMode) Reset()         { *this = TaskQueueMode{} }
func (this *TaskQueueMode) String() string { return proto.CompactTextString(this) }
func (*TaskQueueMode) ProtoMessage()       {}

type TaskQueueAddRequest struct {
	QueueName        []byte                             `protobuf:"bytes,1,req,name=queue_name" json:"queue_name,omitempty"`
	TaskName         []byte                             `protobuf:"bytes,2,req,name=task_name" json:"task_name,omitempty"`
	EtaUsec          *int64                             `protobuf:"varint,3,req,name=eta_usec" json:"eta_usec,omitempty"`
	Method           *TaskQueueAddRequest_RequestMethod `protobuf:"varint,5,opt,name=method,enum=appengine.TaskQueueAddRequest_RequestMethod,def=2" json:"method,omitempty"`
	Url              []byte                             `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Header           []*TaskQueueAddRequest_Header      `protobuf:"group,6,rep" json:"header,omitempty"`
	Body             []byte                             `protobuf:"bytes,9,opt,name=body" json:"body,omitempty"`
	Transaction      *Transaction                       `protobuf:"bytes,10,opt,name=transaction" json:"transaction,omitempty"`
	AppId            []byte                             `protobuf:"bytes,11,opt,name=app_id" json:"app_id,omitempty"`
	Crontimetable    *TaskQueueAddRequest_CronTimetable `protobuf:"group,12,opt,name=CronTimetable" json:"crontimetable,omitempty"`
	Description      []byte                             `protobuf:"bytes,15,opt,name=description" json:"description,omitempty"`
	Payload          *TaskPayload                       `protobuf:"bytes,16,opt,name=payload" json:"payload,omitempty"`
	RetryParameters  *TaskQueueRetryParameters          `protobuf:"bytes,17,opt,name=retry_parameters" json:"retry_parameters,omitempty"`
	Mode             *TaskQueueMode_Mode                `protobuf:"varint,18,opt,name=mode,enum=appengine.TaskQueueMode_Mode,def=0" json:"mode,omitempty"`
	Tag              []byte                             `protobuf:"bytes,19,opt,name=tag" json:"tag,omitempty"`
	XXX_unrecognized []byte                             `json:"-"`
}

func (this *TaskQueueAddRequest) Reset()         { *this = TaskQueueAddRequest{} }
func (this *TaskQueueAddRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueAddRequest) ProtoMessage()       {}

const Default_TaskQueueAddRequest_Method TaskQueueAddRequest_RequestMethod = TaskQueueAddRequest_POST
const Default_TaskQueueAddRequest_Mode TaskQueueMode_Mode = TaskQueueMode_PUSH

func (this *TaskQueueAddRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueAddRequest) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

func (this *TaskQueueAddRequest) GetEtaUsec() int64 {
	if this != nil && this.EtaUsec != nil {
		return *this.EtaUsec
	}
	return 0
}

func (this *TaskQueueAddRequest) GetMethod() TaskQueueAddRequest_RequestMethod {
	if this != nil && this.Method != nil {
		return *this.Method
	}
	return Default_TaskQueueAddRequest_Method
}

func (this *TaskQueueAddRequest) GetUrl() []byte {
	if this != nil {
		return this.Url
	}
	return nil
}

func (this *TaskQueueAddRequest) GetBody() []byte {
	if this != nil {
		return this.Body
	}
	return nil
}

func (this *TaskQueueAddRequest) GetTransaction() *Transaction {
	if this != nil {
		return this.Transaction
	}
	return nil
}

func (this *TaskQueueAddRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueAddRequest) GetCrontimetable() *TaskQueueAddRequest_CronTimetable {
	if this != nil {
		return this.Crontimetable
	}
	return nil
}

func (this *TaskQueueAddRequest) GetDescription() []byte {
	if this != nil {
		return this.Description
	}
	return nil
}

func (this *TaskQueueAddRequest) GetPayload() *TaskPayload {
	if this != nil {
		return this.Payload
	}
	return nil
}

func (this *TaskQueueAddRequest) GetRetryParameters() *TaskQueueRetryParameters {
	if this != nil {
		return this.RetryParameters
	}
	return nil
}

func (this *TaskQueueAddRequest) GetMode() TaskQueueMode_Mode {
	if this != nil && this.Mode != nil {
		return *this.Mode
	}
	return Default_TaskQueueAddRequest_Mode
}

func (this *TaskQueueAddRequest) GetTag() []byte {
	if this != nil {
		return this.Tag
	}
	return nil
}

type TaskQueueAddRequest_Header struct {
	Key   []byte `protobuf:"bytes,7,req,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,8,req,name=value" json:"value,omitempty"`
}

func (this *TaskQueueAddRequest_Header) Reset() { *this = TaskQueueAddRequest_Header{} }

func (this *TaskQueueAddRequest_Header) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *TaskQueueAddRequest_Header) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type TaskQueueAddRequest_CronTimetable struct {
	Schedule []byte `protobuf:"bytes,13,req,name=schedule" json:"schedule,omitempty"`
	Timezone []byte `protobuf:"bytes,14,req,name=timezone" json:"timezone,omitempty"`
}

func (this *TaskQueueAddRequest_CronTimetable) Reset() { *this = TaskQueueAddRequest_CronTimetable{} }

func (this *TaskQueueAddRequest_CronTimetable) GetSchedule() []byte {
	if this != nil {
		return this.Schedule
	}
	return nil
}

func (this *TaskQueueAddRequest_CronTimetable) GetTimezone() []byte {
	if this != nil {
		return this.Timezone
	}
	return nil
}

type TaskQueueAddResponse struct {
	ChosenTaskName   []byte `protobuf:"bytes,1,opt,name=chosen_task_name" json:"chosen_task_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueAddResponse) Reset()         { *this = TaskQueueAddResponse{} }
func (this *TaskQueueAddResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueAddResponse) ProtoMessage()       {}

func (this *TaskQueueAddResponse) GetChosenTaskName() []byte {
	if this != nil {
		return this.ChosenTaskName
	}
	return nil
}

type TaskQueueBulkAddRequest struct {
	AddRequest       []*TaskQueueAddRequest `protobuf:"bytes,1,rep,name=add_request" json:"add_request,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (this *TaskQueueBulkAddRequest) Reset()         { *this = TaskQueueBulkAddRequest{} }
func (this *TaskQueueBulkAddRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueBulkAddRequest) ProtoMessage()       {}

type TaskQueueBulkAddResponse struct {
	Taskresult       []*TaskQueueBulkAddResponse_TaskResult `protobuf:"group,1,rep,name=TaskResult" json:"taskresult,omitempty"`
	XXX_unrecognized []byte                                 `json:"-"`
}

func (this *TaskQueueBulkAddResponse) Reset()         { *this = TaskQueueBulkAddResponse{} }
func (this *TaskQueueBulkAddResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueBulkAddResponse) ProtoMessage()       {}

type TaskQueueBulkAddResponse_TaskResult struct {
	Result         *TaskQueueServiceError_ErrorCode `protobuf:"varint,2,req,name=result,enum=appengine.TaskQueueServiceError_ErrorCode" json:"result,omitempty"`
	ChosenTaskName []byte                           `protobuf:"bytes,3,opt,name=chosen_task_name" json:"chosen_task_name,omitempty"`
}

func (this *TaskQueueBulkAddResponse_TaskResult) Reset() {
	*this = TaskQueueBulkAddResponse_TaskResult{}
}

func (this *TaskQueueBulkAddResponse_TaskResult) GetResult() TaskQueueServiceError_ErrorCode {
	if this != nil && this.Result != nil {
		return *this.Result
	}
	return 0
}

func (this *TaskQueueBulkAddResponse_TaskResult) GetChosenTaskName() []byte {
	if this != nil {
		return this.ChosenTaskName
	}
	return nil
}

type TaskQueueDeleteRequest struct {
	QueueName        []byte   `protobuf:"bytes,1,req,name=queue_name" json:"queue_name,omitempty"`
	TaskName         [][]byte `protobuf:"bytes,2,rep,name=task_name" json:"task_name,omitempty"`
	AppId            []byte   `protobuf:"bytes,3,opt,name=app_id" json:"app_id,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueDeleteRequest) Reset()         { *this = TaskQueueDeleteRequest{} }
func (this *TaskQueueDeleteRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteRequest) ProtoMessage()       {}

func (this *TaskQueueDeleteRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueDeleteRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

type TaskQueueDeleteResponse struct {
	Result           []TaskQueueServiceError_ErrorCode `protobuf:"varint,3,rep,name=result,enum=appengine.TaskQueueServiceError_ErrorCode" json:"result,omitempty"`
	XXX_unrecognized []byte                            `json:"-"`
}

func (this *TaskQueueDeleteResponse) Reset()         { *this = TaskQueueDeleteResponse{} }
func (this *TaskQueueDeleteResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteResponse) ProtoMessage()       {}

type TaskQueueForceRunRequest struct {
	AppId            []byte `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	TaskName         []byte `protobuf:"bytes,3,req,name=task_name" json:"task_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueForceRunRequest) Reset()         { *this = TaskQueueForceRunRequest{} }
func (this *TaskQueueForceRunRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueForceRunRequest) ProtoMessage()       {}

func (this *TaskQueueForceRunRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueForceRunRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueForceRunRequest) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

type TaskQueueForceRunResponse struct {
	Result           *TaskQueueServiceError_ErrorCode `protobuf:"varint,3,req,name=result,enum=appengine.TaskQueueServiceError_ErrorCode" json:"result,omitempty"`
	XXX_unrecognized []byte                           `json:"-"`
}

func (this *TaskQueueForceRunResponse) Reset()         { *this = TaskQueueForceRunResponse{} }
func (this *TaskQueueForceRunResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueForceRunResponse) ProtoMessage()       {}

func (this *TaskQueueForceRunResponse) GetResult() TaskQueueServiceError_ErrorCode {
	if this != nil && this.Result != nil {
		return *this.Result
	}
	return 0
}

type TaskQueueUpdateQueueRequest struct {
	AppId                 []byte                    `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	QueueName             []byte                    `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	BucketRefillPerSecond *float64                  `protobuf:"fixed64,3,req,name=bucket_refill_per_second" json:"bucket_refill_per_second,omitempty"`
	BucketCapacity        *int32                    `protobuf:"varint,4,req,name=bucket_capacity" json:"bucket_capacity,omitempty"`
	UserSpecifiedRate     *string                   `protobuf:"bytes,5,opt,name=user_specified_rate" json:"user_specified_rate,omitempty"`
	RetryParameters       *TaskQueueRetryParameters `protobuf:"bytes,6,opt,name=retry_parameters" json:"retry_parameters,omitempty"`
	MaxConcurrentRequests *int32                    `protobuf:"varint,7,opt,name=max_concurrent_requests" json:"max_concurrent_requests,omitempty"`
	Mode                  *TaskQueueMode_Mode       `protobuf:"varint,8,opt,name=mode,enum=appengine.TaskQueueMode_Mode,def=0" json:"mode,omitempty"`
	Acl                   *TaskQueueAcl             `protobuf:"bytes,9,opt,name=acl" json:"acl,omitempty"`
	HeaderOverride        []*TaskQueueHttpHeader    `protobuf:"bytes,10,rep,name=header_override" json:"header_override,omitempty"`
	XXX_unrecognized      []byte                    `json:"-"`
}

func (this *TaskQueueUpdateQueueRequest) Reset()         { *this = TaskQueueUpdateQueueRequest{} }
func (this *TaskQueueUpdateQueueRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueUpdateQueueRequest) ProtoMessage()       {}

const Default_TaskQueueUpdateQueueRequest_Mode TaskQueueMode_Mode = TaskQueueMode_PUSH

func (this *TaskQueueUpdateQueueRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueUpdateQueueRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueUpdateQueueRequest) GetBucketRefillPerSecond() float64 {
	if this != nil && this.BucketRefillPerSecond != nil {
		return *this.BucketRefillPerSecond
	}
	return 0
}

func (this *TaskQueueUpdateQueueRequest) GetBucketCapacity() int32 {
	if this != nil && this.BucketCapacity != nil {
		return *this.BucketCapacity
	}
	return 0
}

func (this *TaskQueueUpdateQueueRequest) GetUserSpecifiedRate() string {
	if this != nil && this.UserSpecifiedRate != nil {
		return *this.UserSpecifiedRate
	}
	return ""
}

func (this *TaskQueueUpdateQueueRequest) GetRetryParameters() *TaskQueueRetryParameters {
	if this != nil {
		return this.RetryParameters
	}
	return nil
}

func (this *TaskQueueUpdateQueueRequest) GetMaxConcurrentRequests() int32 {
	if this != nil && this.MaxConcurrentRequests != nil {
		return *this.MaxConcurrentRequests
	}
	return 0
}

func (this *TaskQueueUpdateQueueRequest) GetMode() TaskQueueMode_Mode {
	if this != nil && this.Mode != nil {
		return *this.Mode
	}
	return Default_TaskQueueUpdateQueueRequest_Mode
}

func (this *TaskQueueUpdateQueueRequest) GetAcl() *TaskQueueAcl {
	if this != nil {
		return this.Acl
	}
	return nil
}

type TaskQueueUpdateQueueResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueUpdateQueueResponse) Reset()         { *this = TaskQueueUpdateQueueResponse{} }
func (this *TaskQueueUpdateQueueResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueUpdateQueueResponse) ProtoMessage()       {}

type TaskQueueFetchQueuesRequest struct {
	AppId            []byte `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	MaxRows          *int32 `protobuf:"varint,2,req,name=max_rows" json:"max_rows,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueFetchQueuesRequest) Reset()         { *this = TaskQueueFetchQueuesRequest{} }
func (this *TaskQueueFetchQueuesRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchQueuesRequest) ProtoMessage()       {}

func (this *TaskQueueFetchQueuesRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueFetchQueuesRequest) GetMaxRows() int32 {
	if this != nil && this.MaxRows != nil {
		return *this.MaxRows
	}
	return 0
}

type TaskQueueFetchQueuesResponse struct {
	Queue            []*TaskQueueFetchQueuesResponse_Queue `protobuf:"group,1,rep" json:"queue,omitempty"`
	XXX_unrecognized []byte                                `json:"-"`
}

func (this *TaskQueueFetchQueuesResponse) Reset()         { *this = TaskQueueFetchQueuesResponse{} }
func (this *TaskQueueFetchQueuesResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchQueuesResponse) ProtoMessage()       {}

type TaskQueueFetchQueuesResponse_Queue struct {
	QueueName             []byte                    `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	BucketRefillPerSecond *float64                  `protobuf:"fixed64,3,req,name=bucket_refill_per_second" json:"bucket_refill_per_second,omitempty"`
	BucketCapacity        *float64                  `protobuf:"fixed64,4,req,name=bucket_capacity" json:"bucket_capacity,omitempty"`
	UserSpecifiedRate     *string                   `protobuf:"bytes,5,opt,name=user_specified_rate" json:"user_specified_rate,omitempty"`
	Paused                *bool                     `protobuf:"varint,6,req,name=paused,def=0" json:"paused,omitempty"`
	RetryParameters       *TaskQueueRetryParameters `protobuf:"bytes,7,opt,name=retry_parameters" json:"retry_parameters,omitempty"`
	MaxConcurrentRequests *int32                    `protobuf:"varint,8,opt,name=max_concurrent_requests" json:"max_concurrent_requests,omitempty"`
	Mode                  *TaskQueueMode_Mode       `protobuf:"varint,9,opt,name=mode,enum=appengine.TaskQueueMode_Mode,def=0" json:"mode,omitempty"`
	Acl                   *TaskQueueAcl             `protobuf:"bytes,10,opt,name=acl" json:"acl,omitempty"`
	HeaderOverride        []*TaskQueueHttpHeader    `protobuf:"bytes,11,rep,name=header_override" json:"header_override,omitempty"`
	CreatorName           *string                   `protobuf:"bytes,12,opt,name=creator_name,def=apphosting" json:"creator_name,omitempty"`
}

func (this *TaskQueueFetchQueuesResponse_Queue) Reset() { *this = TaskQueueFetchQueuesResponse_Queue{} }

const Default_TaskQueueFetchQueuesResponse_Queue_Paused bool = false
const Default_TaskQueueFetchQueuesResponse_Queue_Mode TaskQueueMode_Mode = TaskQueueMode_PUSH
const Default_TaskQueueFetchQueuesResponse_Queue_CreatorName string = "apphosting"

func (this *TaskQueueFetchQueuesResponse_Queue) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetBucketRefillPerSecond() float64 {
	if this != nil && this.BucketRefillPerSecond != nil {
		return *this.BucketRefillPerSecond
	}
	return 0
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetBucketCapacity() float64 {
	if this != nil && this.BucketCapacity != nil {
		return *this.BucketCapacity
	}
	return 0
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetUserSpecifiedRate() string {
	if this != nil && this.UserSpecifiedRate != nil {
		return *this.UserSpecifiedRate
	}
	return ""
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetPaused() bool {
	if this != nil && this.Paused != nil {
		return *this.Paused
	}
	return Default_TaskQueueFetchQueuesResponse_Queue_Paused
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetRetryParameters() *TaskQueueRetryParameters {
	if this != nil {
		return this.RetryParameters
	}
	return nil
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetMaxConcurrentRequests() int32 {
	if this != nil && this.MaxConcurrentRequests != nil {
		return *this.MaxConcurrentRequests
	}
	return 0
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetMode() TaskQueueMode_Mode {
	if this != nil && this.Mode != nil {
		return *this.Mode
	}
	return Default_TaskQueueFetchQueuesResponse_Queue_Mode
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetAcl() *TaskQueueAcl {
	if this != nil {
		return this.Acl
	}
	return nil
}

func (this *TaskQueueFetchQueuesResponse_Queue) GetCreatorName() string {
	if this != nil && this.CreatorName != nil {
		return *this.CreatorName
	}
	return Default_TaskQueueFetchQueuesResponse_Queue_CreatorName
}

type TaskQueueFetchQueueStatsRequest struct {
	AppId            []byte   `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	QueueName        [][]byte `protobuf:"bytes,2,rep,name=queue_name" json:"queue_name,omitempty"`
	MaxNumTasks      *int32   `protobuf:"varint,3,opt,name=max_num_tasks,def=0" json:"max_num_tasks,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueFetchQueueStatsRequest) Reset()         { *this = TaskQueueFetchQueueStatsRequest{} }
func (this *TaskQueueFetchQueueStatsRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchQueueStatsRequest) ProtoMessage()       {}

const Default_TaskQueueFetchQueueStatsRequest_MaxNumTasks int32 = 0

func (this *TaskQueueFetchQueueStatsRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueFetchQueueStatsRequest) GetMaxNumTasks() int32 {
	if this != nil && this.MaxNumTasks != nil {
		return *this.MaxNumTasks
	}
	return Default_TaskQueueFetchQueueStatsRequest_MaxNumTasks
}

type TaskQueueScannerQueueInfo struct {
	ExecutedLastMinute      *int64   `protobuf:"varint,1,req,name=executed_last_minute" json:"executed_last_minute,omitempty"`
	ExecutedLastHour        *int64   `protobuf:"varint,2,req,name=executed_last_hour" json:"executed_last_hour,omitempty"`
	SamplingDurationSeconds *float64 `protobuf:"fixed64,3,req,name=sampling_duration_seconds" json:"sampling_duration_seconds,omitempty"`
	RequestsInFlight        *int32   `protobuf:"varint,4,opt,name=requests_in_flight" json:"requests_in_flight,omitempty"`
	EnforcedRate            *float64 `protobuf:"fixed64,5,opt,name=enforced_rate" json:"enforced_rate,omitempty"`
	XXX_unrecognized        []byte   `json:"-"`
}

func (this *TaskQueueScannerQueueInfo) Reset()         { *this = TaskQueueScannerQueueInfo{} }
func (this *TaskQueueScannerQueueInfo) String() string { return proto.CompactTextString(this) }
func (*TaskQueueScannerQueueInfo) ProtoMessage()       {}

func (this *TaskQueueScannerQueueInfo) GetExecutedLastMinute() int64 {
	if this != nil && this.ExecutedLastMinute != nil {
		return *this.ExecutedLastMinute
	}
	return 0
}

func (this *TaskQueueScannerQueueInfo) GetExecutedLastHour() int64 {
	if this != nil && this.ExecutedLastHour != nil {
		return *this.ExecutedLastHour
	}
	return 0
}

func (this *TaskQueueScannerQueueInfo) GetSamplingDurationSeconds() float64 {
	if this != nil && this.SamplingDurationSeconds != nil {
		return *this.SamplingDurationSeconds
	}
	return 0
}

func (this *TaskQueueScannerQueueInfo) GetRequestsInFlight() int32 {
	if this != nil && this.RequestsInFlight != nil {
		return *this.RequestsInFlight
	}
	return 0
}

func (this *TaskQueueScannerQueueInfo) GetEnforcedRate() float64 {
	if this != nil && this.EnforcedRate != nil {
		return *this.EnforcedRate
	}
	return 0
}

type TaskQueueFetchQueueStatsResponse struct {
	Queuestats       []*TaskQueueFetchQueueStatsResponse_QueueStats `protobuf:"group,1,rep,name=QueueStats" json:"queuestats,omitempty"`
	XXX_unrecognized []byte                                         `json:"-"`
}

func (this *TaskQueueFetchQueueStatsResponse) Reset()         { *this = TaskQueueFetchQueueStatsResponse{} }
func (this *TaskQueueFetchQueueStatsResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchQueueStatsResponse) ProtoMessage()       {}

type TaskQueueFetchQueueStatsResponse_QueueStats struct {
	NumTasks      *int32                     `protobuf:"varint,2,req,name=num_tasks" json:"num_tasks,omitempty"`
	OldestEtaUsec *int64                     `protobuf:"varint,3,req,name=oldest_eta_usec" json:"oldest_eta_usec,omitempty"`
	ScannerInfo   *TaskQueueScannerQueueInfo `protobuf:"bytes,4,opt,name=scanner_info" json:"scanner_info,omitempty"`
}

func (this *TaskQueueFetchQueueStatsResponse_QueueStats) Reset() {
	*this = TaskQueueFetchQueueStatsResponse_QueueStats{}
}

func (this *TaskQueueFetchQueueStatsResponse_QueueStats) GetNumTasks() int32 {
	if this != nil && this.NumTasks != nil {
		return *this.NumTasks
	}
	return 0
}

func (this *TaskQueueFetchQueueStatsResponse_QueueStats) GetOldestEtaUsec() int64 {
	if this != nil && this.OldestEtaUsec != nil {
		return *this.OldestEtaUsec
	}
	return 0
}

func (this *TaskQueueFetchQueueStatsResponse_QueueStats) GetScannerInfo() *TaskQueueScannerQueueInfo {
	if this != nil {
		return this.ScannerInfo
	}
	return nil
}

type TaskQueuePauseQueueRequest struct {
	AppId            []byte `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	Pause            *bool  `protobuf:"varint,3,req,name=pause" json:"pause,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueuePauseQueueRequest) Reset()         { *this = TaskQueuePauseQueueRequest{} }
func (this *TaskQueuePauseQueueRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueuePauseQueueRequest) ProtoMessage()       {}

func (this *TaskQueuePauseQueueRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueuePauseQueueRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueuePauseQueueRequest) GetPause() bool {
	if this != nil && this.Pause != nil {
		return *this.Pause
	}
	return false
}

type TaskQueuePauseQueueResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueuePauseQueueResponse) Reset()         { *this = TaskQueuePauseQueueResponse{} }
func (this *TaskQueuePauseQueueResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueuePauseQueueResponse) ProtoMessage()       {}

type TaskQueuePurgeQueueRequest struct {
	AppId            []byte `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueuePurgeQueueRequest) Reset()         { *this = TaskQueuePurgeQueueRequest{} }
func (this *TaskQueuePurgeQueueRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueuePurgeQueueRequest) ProtoMessage()       {}

func (this *TaskQueuePurgeQueueRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueuePurgeQueueRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

type TaskQueuePurgeQueueResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueuePurgeQueueResponse) Reset()         { *this = TaskQueuePurgeQueueResponse{} }
func (this *TaskQueuePurgeQueueResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueuePurgeQueueResponse) ProtoMessage()       {}

type TaskQueueDeleteQueueRequest struct {
	AppId            []byte `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueDeleteQueueRequest) Reset()         { *this = TaskQueueDeleteQueueRequest{} }
func (this *TaskQueueDeleteQueueRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteQueueRequest) ProtoMessage()       {}

func (this *TaskQueueDeleteQueueRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueDeleteQueueRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

type TaskQueueDeleteQueueResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueDeleteQueueResponse) Reset()         { *this = TaskQueueDeleteQueueResponse{} }
func (this *TaskQueueDeleteQueueResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteQueueResponse) ProtoMessage()       {}

type TaskQueueDeleteGroupRequest struct {
	AppId            []byte `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueDeleteGroupRequest) Reset()         { *this = TaskQueueDeleteGroupRequest{} }
func (this *TaskQueueDeleteGroupRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteGroupRequest) ProtoMessage()       {}

func (this *TaskQueueDeleteGroupRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

type TaskQueueDeleteGroupResponse struct {
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueDeleteGroupResponse) Reset()         { *this = TaskQueueDeleteGroupResponse{} }
func (this *TaskQueueDeleteGroupResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueDeleteGroupResponse) ProtoMessage()       {}

type TaskQueueQueryTasksRequest struct {
	AppId            []byte `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	StartTaskName    []byte `protobuf:"bytes,3,opt,name=start_task_name" json:"start_task_name,omitempty"`
	StartEtaUsec     *int64 `protobuf:"varint,4,opt,name=start_eta_usec" json:"start_eta_usec,omitempty"`
	StartTag         []byte `protobuf:"bytes,6,opt,name=start_tag" json:"start_tag,omitempty"`
	MaxRows          *int32 `protobuf:"varint,5,opt,name=max_rows,def=1" json:"max_rows,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueQueryTasksRequest) Reset()         { *this = TaskQueueQueryTasksRequest{} }
func (this *TaskQueueQueryTasksRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueQueryTasksRequest) ProtoMessage()       {}

const Default_TaskQueueQueryTasksRequest_MaxRows int32 = 1

func (this *TaskQueueQueryTasksRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueQueryTasksRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueQueryTasksRequest) GetStartTaskName() []byte {
	if this != nil {
		return this.StartTaskName
	}
	return nil
}

func (this *TaskQueueQueryTasksRequest) GetStartEtaUsec() int64 {
	if this != nil && this.StartEtaUsec != nil {
		return *this.StartEtaUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksRequest) GetStartTag() []byte {
	if this != nil {
		return this.StartTag
	}
	return nil
}

func (this *TaskQueueQueryTasksRequest) GetMaxRows() int32 {
	if this != nil && this.MaxRows != nil {
		return *this.MaxRows
	}
	return Default_TaskQueueQueryTasksRequest_MaxRows
}

type TaskQueueQueryTasksResponse struct {
	Task             []*TaskQueueQueryTasksResponse_Task `protobuf:"group,1,rep" json:"task,omitempty"`
	XXX_unrecognized []byte                              `json:"-"`
}

func (this *TaskQueueQueryTasksResponse) Reset()         { *this = TaskQueueQueryTasksResponse{} }
func (this *TaskQueueQueryTasksResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueQueryTasksResponse) ProtoMessage()       {}

type TaskQueueQueryTasksResponse_Task struct {
	TaskName         []byte                                          `protobuf:"bytes,2,req,name=task_name" json:"task_name,omitempty"`
	EtaUsec          *int64                                          `protobuf:"varint,3,req,name=eta_usec" json:"eta_usec,omitempty"`
	Url              []byte                                          `protobuf:"bytes,4,opt,name=url" json:"url,omitempty"`
	Method           *TaskQueueQueryTasksResponse_Task_RequestMethod `protobuf:"varint,5,opt,name=method,enum=appengine.TaskQueueQueryTasksResponse_Task_RequestMethod" json:"method,omitempty"`
	RetryCount       *int32                                          `protobuf:"varint,6,opt,name=retry_count,def=0" json:"retry_count,omitempty"`
	Header           []*TaskQueueQueryTasksResponse_Task_Header      `protobuf:"group,7,rep" json:"header,omitempty"`
	BodySize         *int32                                          `protobuf:"varint,10,opt,name=body_size" json:"body_size,omitempty"`
	Body             []byte                                          `protobuf:"bytes,11,opt,name=body" json:"body,omitempty"`
	CreationTimeUsec *int64                                          `protobuf:"varint,12,req,name=creation_time_usec" json:"creation_time_usec,omitempty"`
	Crontimetable    *TaskQueueQueryTasksResponse_Task_CronTimetable `protobuf:"group,13,opt,name=CronTimetable" json:"crontimetable,omitempty"`
	Runlog           *TaskQueueQueryTasksResponse_Task_RunLog        `protobuf:"group,16,opt,name=RunLog" json:"runlog,omitempty"`
	Description      []byte                                          `protobuf:"bytes,21,opt,name=description" json:"description,omitempty"`
	Payload          *TaskPayload                                    `protobuf:"bytes,22,opt,name=payload" json:"payload,omitempty"`
	RetryParameters  *TaskQueueRetryParameters                       `protobuf:"bytes,23,opt,name=retry_parameters" json:"retry_parameters,omitempty"`
	FirstTryUsec     *int64                                          `protobuf:"varint,24,opt,name=first_try_usec" json:"first_try_usec,omitempty"`
	Tag              []byte                                          `protobuf:"bytes,25,opt,name=tag" json:"tag,omitempty"`
	ExecutionCount   *int32                                          `protobuf:"varint,26,opt,name=execution_count,def=0" json:"execution_count,omitempty"`
}

func (this *TaskQueueQueryTasksResponse_Task) Reset() { *this = TaskQueueQueryTasksResponse_Task{} }

const Default_TaskQueueQueryTasksResponse_Task_RetryCount int32 = 0
const Default_TaskQueueQueryTasksResponse_Task_ExecutionCount int32 = 0

func (this *TaskQueueQueryTasksResponse_Task) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetEtaUsec() int64 {
	if this != nil && this.EtaUsec != nil {
		return *this.EtaUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task) GetUrl() []byte {
	if this != nil {
		return this.Url
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetMethod() TaskQueueQueryTasksResponse_Task_RequestMethod {
	if this != nil && this.Method != nil {
		return *this.Method
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task) GetRetryCount() int32 {
	if this != nil && this.RetryCount != nil {
		return *this.RetryCount
	}
	return Default_TaskQueueQueryTasksResponse_Task_RetryCount
}

func (this *TaskQueueQueryTasksResponse_Task) GetBodySize() int32 {
	if this != nil && this.BodySize != nil {
		return *this.BodySize
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task) GetBody() []byte {
	if this != nil {
		return this.Body
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetCreationTimeUsec() int64 {
	if this != nil && this.CreationTimeUsec != nil {
		return *this.CreationTimeUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task) GetCrontimetable() *TaskQueueQueryTasksResponse_Task_CronTimetable {
	if this != nil {
		return this.Crontimetable
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetRunlog() *TaskQueueQueryTasksResponse_Task_RunLog {
	if this != nil {
		return this.Runlog
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetDescription() []byte {
	if this != nil {
		return this.Description
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetPayload() *TaskPayload {
	if this != nil {
		return this.Payload
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetRetryParameters() *TaskQueueRetryParameters {
	if this != nil {
		return this.RetryParameters
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetFirstTryUsec() int64 {
	if this != nil && this.FirstTryUsec != nil {
		return *this.FirstTryUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task) GetTag() []byte {
	if this != nil {
		return this.Tag
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task) GetExecutionCount() int32 {
	if this != nil && this.ExecutionCount != nil {
		return *this.ExecutionCount
	}
	return Default_TaskQueueQueryTasksResponse_Task_ExecutionCount
}

type TaskQueueQueryTasksResponse_Task_Header struct {
	Key   []byte `protobuf:"bytes,8,req,name=key" json:"key,omitempty"`
	Value []byte `protobuf:"bytes,9,req,name=value" json:"value,omitempty"`
}

func (this *TaskQueueQueryTasksResponse_Task_Header) Reset() {
	*this = TaskQueueQueryTasksResponse_Task_Header{}
}

func (this *TaskQueueQueryTasksResponse_Task_Header) GetKey() []byte {
	if this != nil {
		return this.Key
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task_Header) GetValue() []byte {
	if this != nil {
		return this.Value
	}
	return nil
}

type TaskQueueQueryTasksResponse_Task_CronTimetable struct {
	Schedule []byte `protobuf:"bytes,14,req,name=schedule" json:"schedule,omitempty"`
	Timezone []byte `protobuf:"bytes,15,req,name=timezone" json:"timezone,omitempty"`
}

func (this *TaskQueueQueryTasksResponse_Task_CronTimetable) Reset() {
	*this = TaskQueueQueryTasksResponse_Task_CronTimetable{}
}

func (this *TaskQueueQueryTasksResponse_Task_CronTimetable) GetSchedule() []byte {
	if this != nil {
		return this.Schedule
	}
	return nil
}

func (this *TaskQueueQueryTasksResponse_Task_CronTimetable) GetTimezone() []byte {
	if this != nil {
		return this.Timezone
	}
	return nil
}

type TaskQueueQueryTasksResponse_Task_RunLog struct {
	DispatchedUsec *int64 `protobuf:"varint,17,req,name=dispatched_usec" json:"dispatched_usec,omitempty"`
	LagUsec        *int64 `protobuf:"varint,18,req,name=lag_usec" json:"lag_usec,omitempty"`
	ElapsedUsec    *int64 `protobuf:"varint,19,req,name=elapsed_usec" json:"elapsed_usec,omitempty"`
	ResponseCode   *int64 `protobuf:"varint,20,opt,name=response_code" json:"response_code,omitempty"`
}

func (this *TaskQueueQueryTasksResponse_Task_RunLog) Reset() {
	*this = TaskQueueQueryTasksResponse_Task_RunLog{}
}

func (this *TaskQueueQueryTasksResponse_Task_RunLog) GetDispatchedUsec() int64 {
	if this != nil && this.DispatchedUsec != nil {
		return *this.DispatchedUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task_RunLog) GetLagUsec() int64 {
	if this != nil && this.LagUsec != nil {
		return *this.LagUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task_RunLog) GetElapsedUsec() int64 {
	if this != nil && this.ElapsedUsec != nil {
		return *this.ElapsedUsec
	}
	return 0
}

func (this *TaskQueueQueryTasksResponse_Task_RunLog) GetResponseCode() int64 {
	if this != nil && this.ResponseCode != nil {
		return *this.ResponseCode
	}
	return 0
}

type TaskQueueFetchTaskRequest struct {
	AppId            []byte `protobuf:"bytes,1,opt,name=app_id" json:"app_id,omitempty"`
	QueueName        []byte `protobuf:"bytes,2,req,name=queue_name" json:"queue_name,omitempty"`
	TaskName         []byte `protobuf:"bytes,3,req,name=task_name" json:"task_name,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueFetchTaskRequest) Reset()         { *this = TaskQueueFetchTaskRequest{} }
func (this *TaskQueueFetchTaskRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchTaskRequest) ProtoMessage()       {}

func (this *TaskQueueFetchTaskRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueFetchTaskRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueFetchTaskRequest) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

type TaskQueueFetchTaskResponse struct {
	Task             *TaskQueueQueryTasksResponse `protobuf:"bytes,1,req,name=task" json:"task,omitempty"`
	XXX_unrecognized []byte                       `json:"-"`
}

func (this *TaskQueueFetchTaskResponse) Reset()         { *this = TaskQueueFetchTaskResponse{} }
func (this *TaskQueueFetchTaskResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueFetchTaskResponse) ProtoMessage()       {}

func (this *TaskQueueFetchTaskResponse) GetTask() *TaskQueueQueryTasksResponse {
	if this != nil {
		return this.Task
	}
	return nil
}

type TaskQueueUpdateStorageLimitRequest struct {
	AppId            []byte `protobuf:"bytes,1,req,name=app_id" json:"app_id,omitempty"`
	Limit            *int64 `protobuf:"varint,2,req,name=limit" json:"limit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueUpdateStorageLimitRequest) Reset()         { *this = TaskQueueUpdateStorageLimitRequest{} }
func (this *TaskQueueUpdateStorageLimitRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueUpdateStorageLimitRequest) ProtoMessage()       {}

func (this *TaskQueueUpdateStorageLimitRequest) GetAppId() []byte {
	if this != nil {
		return this.AppId
	}
	return nil
}

func (this *TaskQueueUpdateStorageLimitRequest) GetLimit() int64 {
	if this != nil && this.Limit != nil {
		return *this.Limit
	}
	return 0
}

type TaskQueueUpdateStorageLimitResponse struct {
	NewLimit         *int64 `protobuf:"varint,1,req,name=new_limit" json:"new_limit,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueUpdateStorageLimitResponse) Reset() {
	*this = TaskQueueUpdateStorageLimitResponse{}
}
func (this *TaskQueueUpdateStorageLimitResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueUpdateStorageLimitResponse) ProtoMessage()       {}

func (this *TaskQueueUpdateStorageLimitResponse) GetNewLimit() int64 {
	if this != nil && this.NewLimit != nil {
		return *this.NewLimit
	}
	return 0
}

type TaskQueueQueryAndOwnTasksRequest struct {
	QueueName        []byte   `protobuf:"bytes,1,req,name=queue_name" json:"queue_name,omitempty"`
	LeaseSeconds     *float64 `protobuf:"fixed64,2,req,name=lease_seconds" json:"lease_seconds,omitempty"`
	MaxTasks         *int64   `protobuf:"varint,3,req,name=max_tasks" json:"max_tasks,omitempty"`
	GroupByTag       *bool    `protobuf:"varint,4,opt,name=group_by_tag,def=0" json:"group_by_tag,omitempty"`
	Tag              []byte   `protobuf:"bytes,5,opt,name=tag" json:"tag,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueQueryAndOwnTasksRequest) Reset()         { *this = TaskQueueQueryAndOwnTasksRequest{} }
func (this *TaskQueueQueryAndOwnTasksRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueQueryAndOwnTasksRequest) ProtoMessage()       {}

const Default_TaskQueueQueryAndOwnTasksRequest_GroupByTag bool = false

func (this *TaskQueueQueryAndOwnTasksRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueQueryAndOwnTasksRequest) GetLeaseSeconds() float64 {
	if this != nil && this.LeaseSeconds != nil {
		return *this.LeaseSeconds
	}
	return 0
}

func (this *TaskQueueQueryAndOwnTasksRequest) GetMaxTasks() int64 {
	if this != nil && this.MaxTasks != nil {
		return *this.MaxTasks
	}
	return 0
}

func (this *TaskQueueQueryAndOwnTasksRequest) GetGroupByTag() bool {
	if this != nil && this.GroupByTag != nil {
		return *this.GroupByTag
	}
	return Default_TaskQueueQueryAndOwnTasksRequest_GroupByTag
}

func (this *TaskQueueQueryAndOwnTasksRequest) GetTag() []byte {
	if this != nil {
		return this.Tag
	}
	return nil
}

type TaskQueueQueryAndOwnTasksResponse struct {
	Task             []*TaskQueueQueryAndOwnTasksResponse_Task `protobuf:"group,1,rep" json:"task,omitempty"`
	XXX_unrecognized []byte                                    `json:"-"`
}

func (this *TaskQueueQueryAndOwnTasksResponse) Reset()         { *this = TaskQueueQueryAndOwnTasksResponse{} }
func (this *TaskQueueQueryAndOwnTasksResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueQueryAndOwnTasksResponse) ProtoMessage()       {}

type TaskQueueQueryAndOwnTasksResponse_Task struct {
	TaskName   []byte `protobuf:"bytes,2,req,name=task_name" json:"task_name,omitempty"`
	EtaUsec    *int64 `protobuf:"varint,3,req,name=eta_usec" json:"eta_usec,omitempty"`
	RetryCount *int32 `protobuf:"varint,4,opt,name=retry_count,def=0" json:"retry_count,omitempty"`
	Body       []byte `protobuf:"bytes,5,opt,name=body" json:"body,omitempty"`
	Tag        []byte `protobuf:"bytes,6,opt,name=tag" json:"tag,omitempty"`
}

func (this *TaskQueueQueryAndOwnTasksResponse_Task) Reset() {
	*this = TaskQueueQueryAndOwnTasksResponse_Task{}
}

const Default_TaskQueueQueryAndOwnTasksResponse_Task_RetryCount int32 = 0

func (this *TaskQueueQueryAndOwnTasksResponse_Task) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

func (this *TaskQueueQueryAndOwnTasksResponse_Task) GetEtaUsec() int64 {
	if this != nil && this.EtaUsec != nil {
		return *this.EtaUsec
	}
	return 0
}

func (this *TaskQueueQueryAndOwnTasksResponse_Task) GetRetryCount() int32 {
	if this != nil && this.RetryCount != nil {
		return *this.RetryCount
	}
	return Default_TaskQueueQueryAndOwnTasksResponse_Task_RetryCount
}

func (this *TaskQueueQueryAndOwnTasksResponse_Task) GetBody() []byte {
	if this != nil {
		return this.Body
	}
	return nil
}

func (this *TaskQueueQueryAndOwnTasksResponse_Task) GetTag() []byte {
	if this != nil {
		return this.Tag
	}
	return nil
}

type TaskQueueModifyTaskLeaseRequest struct {
	QueueName        []byte   `protobuf:"bytes,1,req,name=queue_name" json:"queue_name,omitempty"`
	TaskName         []byte   `protobuf:"bytes,2,req,name=task_name" json:"task_name,omitempty"`
	EtaUsec          *int64   `protobuf:"varint,3,req,name=eta_usec" json:"eta_usec,omitempty"`
	LeaseSeconds     *float64 `protobuf:"fixed64,4,req,name=lease_seconds" json:"lease_seconds,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (this *TaskQueueModifyTaskLeaseRequest) Reset()         { *this = TaskQueueModifyTaskLeaseRequest{} }
func (this *TaskQueueModifyTaskLeaseRequest) String() string { return proto.CompactTextString(this) }
func (*TaskQueueModifyTaskLeaseRequest) ProtoMessage()       {}

func (this *TaskQueueModifyTaskLeaseRequest) GetQueueName() []byte {
	if this != nil {
		return this.QueueName
	}
	return nil
}

func (this *TaskQueueModifyTaskLeaseRequest) GetTaskName() []byte {
	if this != nil {
		return this.TaskName
	}
	return nil
}

func (this *TaskQueueModifyTaskLeaseRequest) GetEtaUsec() int64 {
	if this != nil && this.EtaUsec != nil {
		return *this.EtaUsec
	}
	return 0
}

func (this *TaskQueueModifyTaskLeaseRequest) GetLeaseSeconds() float64 {
	if this != nil && this.LeaseSeconds != nil {
		return *this.LeaseSeconds
	}
	return 0
}

type TaskQueueModifyTaskLeaseResponse struct {
	UpdatedEtaUsec   *int64 `protobuf:"varint,1,req,name=updated_eta_usec" json:"updated_eta_usec,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (this *TaskQueueModifyTaskLeaseResponse) Reset()         { *this = TaskQueueModifyTaskLeaseResponse{} }
func (this *TaskQueueModifyTaskLeaseResponse) String() string { return proto.CompactTextString(this) }
func (*TaskQueueModifyTaskLeaseResponse) ProtoMessage()       {}

func (this *TaskQueueModifyTaskLeaseResponse) GetUpdatedEtaUsec() int64 {
	if this != nil && this.UpdatedEtaUsec != nil {
		return *this.UpdatedEtaUsec
	}
	return 0
}

func init() {
	proto.RegisterEnum("appengine.TaskQueueServiceError_ErrorCode", TaskQueueServiceError_ErrorCode_name, TaskQueueServiceError_ErrorCode_value)
	proto.RegisterEnum("appengine.TaskQueueMode_Mode", TaskQueueMode_Mode_name, TaskQueueMode_Mode_value)
	proto.RegisterEnum("appengine.TaskQueueAddRequest_RequestMethod", TaskQueueAddRequest_RequestMethod_name, TaskQueueAddRequest_RequestMethod_value)
	proto.RegisterEnum("appengine.TaskQueueQueryTasksResponse_Task_RequestMethod", TaskQueueQueryTasksResponse_Task_RequestMethod_name, TaskQueueQueryTasksResponse_Task_RequestMethod_value)
}
